### ISSUE TITLE
`test/Test/Main.purs` vs `test/Main.purs`

### ISSUE THREAD

**Issue by thought2** [purescript/spago#1014]
Old spago init created `test/Main.purs`

Readme docs for new spago tell that new spago creates `test/Main.purs`
but
`spago init` (0.93.13) creates `test/Test/Main.purs`

personally I prefer `test/Test/Main.purs` as it corresponds to the actual module name.

**Comment by f-f** [comment]
Ah yes, the documentation needs fixing
