### ISSUE TITLE
Reinstate the `spago docs` command

### ISSUE THREAD

**Issue by f-f** [purescript/spago#1020]
We currently do not have a `spago docs` command in the PureScript codebase.

We would need to port it from the [old codebase](https://github.com/purescript/spago-legacy/blob/11e68ece50ede286660452ef370baa3ab5c33c02/src/Spago/Build.hs#L500), with the difference that since both projects are in PureScript we could just use it as a library instead of calling a separate node process.

So a tentative checklist for things to do could be:
- update [`docs-search`](https://github.com/purescript/purescript-docs-search) to use the new Spago
- add it as a dependency
- port [the implementation for the `docs` command from Haskell](https://github.com/purescript/spago-legacy/blob/11e68ece50ede286660452ef370baa3ab5c33c02/src/Spago/Build.hs#L500)
- since the `docs` command injects a Halogen app in the generated html, we'd need to bundle that app when bunling/publishing Spago and put it where Spago can find it at runtime, so it can copy it over

**Comment by CharlesTaylor7** [comment]
I have a draft PR for the first item:
https://github.com/purescript/purescript-docs-search/pull/69

**Comment by f-f** [comment]
@CharlesTaylor7 lovely, thanks! There's an unfortunate amount of incidental complexity in trying to get that repo up to date, so let's try something different.
I have ported the codebase [here inside this repo](https://github.com/purescript/spago/tree/master/docs-search) so we can do the change without the complications of CI and keeping backwards compatibility with the existing stuff.

Can you apply the same changes here? We won't have to get it working, it would just need to compile to merge this in.

**Comment by CharlesTaylor7** [comment]
@f-f Ok, understood. I made a new draft PR against this repo: https://github.com/purescript/spago/pull/1023

**Comment by CharlesTaylor7** [comment]
Rough todo list of remaining work:
- [ ] In `docs-search`, remove `argonaut-generic` dep and related generic instances in favor of `codec-argonaut` codecs.
- [ ] In `docs-search`, Swap out doc types and ast types for the ones defined in `language-purescript`
- [ ] Enable search indexing in the `spago docs` command
- [ ] Bundle `docs-search`s halogen app during spago publish. Inject the app at runtime after indexing.
