### ISSUE TITLE
Document that we don't support a watcher anymore

### ISSUE THREAD

**Issue by f-f** [purescript/spago#1029]
We should document that this conflicts with workflows using the language server (`purs ide server`) and we should redirect users that still want to go at it to tools like [watchexec](https://github.com/watchexec/watchexec) or [pscid](https://github.com/kritzcreek/pscid)

**Comment by CharlesTaylor7** [comment]
I have started using `watchexec` recently at your recommendation.
It's been a great drop-in replacement and something I'm planning to use in my non-purescript projects too!

**Comment by flip111** [comment]
Here is a blog post comparing different file watchers https://anarc.at/blog/2019-11-20-file-monitoring-tools/

The feature could be added again to spago one day, nodejs [has an API for it](https://nodejs.org/api/fs.html#fspromiseswatchfilename-options)

**Comment by f-f** [comment]
The issue is not that it's hard to implement a watcher (we had one), but that's hard to have it do the right thing in every situation. It just adds a lot of complexity to the implementation for no clear gain - there are a lot of watchers out there that do a perfectly good job at it

**Comment by flip111** [comment]
When i look at the feature-set of `watchexec` it's pretty impressive. To re-implement all of that is not worth it, and you probably want those features.
