### ISSUE TITLE
Organize `spago build --pedantic-packages` output

### ISSUE THREAD

**Issue by CharlesTaylor7** [purescript/spago#1042]
It'd be easier to use the feedback of this command if all the `spago install` recommendations were listed at the end of the output:

https://github.com/purescript/spago/pull/1041#discussion_r1345795122

**Comment by JordanMartinez** [comment]
What would the output look like? 

Something like this where a single command can be easily copy-pasted into the terminal and executed?
```sh
spago install -p package-a dep1 && spago install --test-deps -p package-a dep2 dep3 && spago install -p package-b dep4 dep5 && spago install --test-deps -p package-a dep6
```
Or this where each command is listed separately, such that a failure in a previous command doesn't cause a problem in the next one?
```sh
spago install -p package-a dep1
spago install --test-deps -p package-a dep2 dep3
spago install -p package-b dep4 dep5
spago install --test-deps -p package-a dep6
```

**Comment by f-f** [comment]
I would prefer the second option, easier to parse if it's over multiple short lines vs one long line

**Comment by f-f** [comment]
Also, I think we should add a `uninstall` command, so we'd be able to suggest a command to run for unused dependencies as well (right now it will just ask you to remove them from the config)

**Comment by JordanMartinez** [comment]
This is now unblocked :grin:
