### ISSUE TITLE
For pedantic builds, limit install recommendations for test deps

### ISSUE THREAD

**Issue by CharlesTaylor7** [purescript/spago#1043]
https://github.com/purescript/spago/pull/1041#discussion_r1345795122

When you run `spago build -p spago --pedantic-packages` you might see:

```console
Run the following command to install them all:
  spago install -p spago aff-promise ansi console control enums exceptions formatters node-fs-aff routing-duplex unfoldable unicode
  
  ...
  
  Run the following command to install them all:
  spago install --test-deps -p spago console enums identity newtype node-fs-aff quickcheck
```

But we'd prefer it to be something like:
```console
Run the following command to install them all:
  spago install -p spago aff-promise ansi console control enums exceptions formatters node-fs-aff routing-duplex unfoldable unicode
  
  ...
  
  Run the following command to install them all:
  spago install --test-deps -p spago identity newtype quickcheck
```
Basically the duplicated recommendations between the missing project deps,  and the missing test deps, have been deduplicated.

**Comment by CharlesTaylor7** [comment]
@f-f What do you think about introducing a command that fixes up the deps in your spago.yaml files?

Spago already knows exactly what's missing and what's unnecessary, so if we had `spago install --fixup` or `spago install --missing-pedantic-deps`, it could edit the files for you and skip the middle step of copying the terminal output from `spago build --pedantic-packages`.

**Comment by f-f** [comment]
Yes, I like this! We could change the `--pedantic-packages` flag from being a flag to take different values, so we'd have:
- `--pedantic-packages=notify` to only error out
- or `--pedantic-packages=autofix` to have spago just fix your packages automatically
