### ISSUE TITLE
Migrate `pedantic-packages` from workspace config to package config

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#1049]
As mentioned here: https://github.com/purescript/spago/pull/1045#discussion_r1349488225

**Comment by f-f** [comment]
Actually I am not sure now if it should be workspace-wide or if it makes sense for users to be able to define this per-package 🤔

**Comment by JordanMartinez** [comment]
Because....?

**Comment by f-f** [comment]
Yeah, can't think of reasons for going either way 😄

**Comment by JordanMartinez** [comment]
My reason for it being in packages is because of one-off scripts where I don't care about this particular warning. Or packages that act as examples, benchmarks, etc. Stuff where the extra packages don't actually matter.

**Comment by f-f** [comment]
Ah yes, this makes sense. Packages it is then!
