### ISSUE TITLE
`spago run` without specifying a package

### ISSUE THREAD

**Issue by CharlesTaylor7** [purescript/spago#1050]
I have a UX request, instead of needing to run:
`spago run -p foo -m Foo`

I would like to run:
`spago run -m Foo`

The compiled modules in `output` are unique, so specifying the package feels redundant as a user.

I do understand that, it's easier from spago's standpoint if it only has to build the necessary package to get the desired module. 
I'm of the opinion that the improved UX for simple cases, warrants allowing a full workspace build when the requested module hasn't been built yet.

**Comment by f-f** [comment]
You can use `spago run -p foo` if the `foo` package has a `run` section defined - this is documented in the [configuration file docs](https://github.com/purescript/spago#the-configuration-file) but it looks like we should mention it more prominently in the docs for the run command
