### ISSUE TITLE
Rework how we apply PSA options and get back to building all together

### ISSUE THREAD

**Issue by f-f** [purescript/spago#1051]
Now that we have #1018, building all the packages vs building the package that depends on everything else take very different amount of time even though they are doing the same work:
```
spago build  18.07s user 3.75s system 219% cpu 9.960 total
```
vs
```
spago build -p spago-bin  9.58s user 2.26s system 178% cpu 6.631 total
```

I am not sure now if the latter command is doing "the right thing" (e.g. if the dependencies have psa options then it's probably ignoring those?), but if we are fine with this then we should add a `default_package` option to the workspace section, so that running `spago build` will select the default package instead of all of them.

If we are not fine with this - i.e. we should always compile all the things with the correct PSA options - then I think the only way possible would be to go back to compiling all together, and fix the two reasons why we are compiling in topological order by instead:
- using the graph check to see if there are circular dependencies between workspace packages
- and reworking the PSA path decisions so that it can "do the right thing" even when we are compiling everything together (this will probably need to be assisted by the graph)

**Comment by f-f** [comment]
cc @JordanMartinez

**Comment by f-f** [comment]
If we go with the second option here, then we are done with #988

**Comment by JordanMartinez** [comment]
> if the dependencies have psa options then it's probably ignoring those?

Could you clarify this?

I think we could speed things up by adding caching where right now we're recomputing the same thing. Perhaps adding some time values to the Debug logger would also help us see where the delay comes from.

**Comment by JordanMartinez** [comment]
Per our conversation via Discord chat, we agreed to go back to building everything all at once in `spago build` as that means we call `purs compile` once rather than once for each workspace package. This is fine because we already do the duplicate module check.

**Comment by f-f** [comment]
Clarification on the above: we would apply the PSA options (for tests as well, see #1068) discriminating by path rather than compiling separately, as introduced in #1045
