### ISSUE TITLE
Instructions on package.publish could be more clear

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1056]
You can get this error when trying to publish
```
Did not find publishing config: add a valid one in package.publish
```

It's not clear here what to do. Initially [the docs say](https://github.com/purescript/spago#publish-my-library) to follow this instruction so this should be self explanatory. One should add a publish section to the configuration. Configuration explanation can be found here https://github.com/purescript/spago#the-configuration-file

**Comment by f-f** [comment]
Yes, we should link to that section, but we could also print out an example publishing config, maybe even including the package location as you suggest in #1060
