### ISSUE TITLE
License field

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1059]
Under `package -> publish` there should be a `license` field.

Some issues with this field:
1. The configuration https://github.com/purescript/spago#the-configuration-file points to the website https://spdx.dev/ The spdx website is not clear, i don't know where to click there and see a list of licenses. By the way this website has a clear list of licenses so why not link there instead? https://opensource.org/licenses/
2. The LICENSE file can contain any kind of license that you want, does SPDX have a format for "any license"? If no, then the SPDX format should not be REQUIRED (but can still be used). In case the license SPDX then the point where the license is used (in documentation i guess) should just point to the full license file in the github repository
3. For the usual licenses https://choosealicense.com/ one could just check the license file and update this field automatically. This plays well with "one point is source of truth"

**Comment by f-f** [comment]
1. this is a good suggestion
2. SPDX does not have a field for "any license", and we're not going to support it. The PureScript Registry is only going to support open source code with a clearly defined license, and explicitly supports only SPDX licenses, no exceptions. We could document this policy here as well.
3. this would entail parsing LICENSE files, which is absolutely a business we're not going to get into. We could detect a LICENSE file though, and nudge the user to make sure it coincides with the license that it's being provided in this field

**Comment by flip111** [comment]
For 3. i didn't mean a sophisticated parser but only if the full text matches

**Comment by f-f** [comment]
It's still a big project - see [this big thing made by GitHub](https://github.com/licensee/licensee) that does exactly this

**Comment by flip111** [comment]
From that project the exact matcher implementation is only a few lines of code though https://github.com/licensee/licensee/blob/main/lib/licensee/matchers/exact.rb#L9-L11 i suspect the exact matches will already cover most license files.

**Comment by f-f** [comment]
Sure, I'd be willing to merge a PR that implements this if it's only a few lines of code

**Comment by fsoikin** [comment]
I'm afraid it's not just a few lines of code. Sure, the match itself is just a single comparison, but there is quite a lot going on behind the scenes there. Basically they have [a set of licenses kept in files on disk](https://github.com/licensee/licensee/tree/main/vendor/choosealicense.com/_licenses), but they don't compare them directly for exact match. Instead, they do [a whole lot of complicated manipulations](https://github.com/licensee/licensee/blob/main/lib/licensee/content_helper.rb) apparently intended to "normalize" the content and protect against common mistakes, such as duplicated words, whitespace, and so on. Which, to me, indicates that simply comparing for exact match probably won't be a good solution.

**Comment by f-f** [comment]
Agreed - I'll close this for now, let's reopen if we have a low-cost high-leverage solution for this, but otherwise I don't see it as worth spending lots of lines of code on.
