### ISSUE TITLE
Support PureScript's `--exclude-files` CLI arg

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#1064]
`purescript@0.15.10` allows one to exclude files from compiler input via the `--exclude-files` argument. 

```
-x,--exclude-files ARG   Glob of .purs files to exclude from the supplied files.
```

How should this flag be supported given that we currently make the following assumptions:
- a given package always contains its files in `src/**/*.purs`
- a given package's test (if it exists) always exists in `test/**/*.purs`

AFAICT, the purpose of the `--exclude-files` is to allow one to have multiple packages within the same `src` directory.

**Comment by JordanMartinez** [comment]
Seems related to https://github.com/purescript/registry-dev/issues/594

**Comment by f-f** [comment]
Why would we want to support this? 

Spago has a specific idea of what a package is, and that does not play well with "splitting a `src` directory between multiple packages"

**Comment by f-f** [comment]
And I mentioned colocation in our chat earlier today - I think I got confused, doesn't seem related

**Comment by f-f** [comment]
Me and Jordan had a call earlier today and agreed that we won't support this unless we have a good usecase
