### ISSUE TITLE
Cache more things in the DB so we don't hit the disk

### ISSUE THREAD

**Issue by f-f** [purescript/spago#1083]
Now that we have a database, we should not [be reading and writing caches](https://github.com/purescript/spago/blob/14dc0e20038596300f06a39cfcd76c6a89f8b6b1/src/Spago/Config.purs#L490-L510) on disk, but just add a database table to have them into

**Comment by f-f** [comment]
We should also cache the results of `getManifestFromIndex` since those are immutable.

**Comment by JordanMartinez** [comment]
@finnhodgkin If you're interested, this may be another one worth looking into.

**Comment by f-f** [comment]
The part where we cache the result of `getManifestFromIndex` in the database is still very much needed - basically we need a `manifest` table that whose primary key is a composite of Package name + Version.

Since we are going to have lockfiles for all builds (see #917), I don't think the part where we cache package sets in the database makes sense anymore

**Comment by finnhodgkin** [comment]
> @finnhodgkin If you're interested, this may be another one worth looking into.

I'm not sure how much free time I'll have in the next week or two but happy to take a look if I find some.

**Comment by f-f** [comment]
Something else to pile on this "bring things in the database": right now we write a file and check its modification time to decide if we should be fetching the registry repo. This is slow, and not portable between OSs, so we should just have a table for it.
