### ISSUE TITLE
Add `uninstall` command

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#1091]
See https://github.com/purescript/spago/issues/1042#issuecomment-1762918583

Blocks #1042

**Comment by JordanMartinez** [comment]
Thinking through this more, I'm assuming this command would
1. Read the config file for the given package
2. Write out a new version of the config file with the corresponding dependency removed

But a few questions:
1. Let's say the package that is trying to be uninstalled isn't listed for that package's config. Do we warn the user? Or die because we couldn't uninstall it? Or potentially, do we list other packages that have that package installed (in case we chose the wrong package in the first place)?
2. What does `spago uninstall foo` do in a multi-package workspace? Is this simply not allowed? Or does it only work if the workspace config has a root package?
3. Should we run a pedantic packages check afterwards, in case uninstalling a dependency in package A (e.g. `package-a`'s `src` part) somehow affects package B (e.g. `package-a`'s `test` part)?

**Comment by f-f** [comment]
1. I'd say we do the same as `spago install` does: warn the user and move on with removing other packages that exist in the list, and terminate successfully
2. As above let's mirror the install command: ask the user to specify a package unless we are in a single-package project (this does not imply that the package is in the root - I'm not sure what the `install` command does in that case. But we have many places in the codebase where we select the only package if none are selected)
3. Ah this is an interesting one - I would say we don't check anything? If the user removed a package then I'd assume they plan to deal with the possible consequences, such as a broken build

**Comment by JordanMartinez** [comment]
Regarding question 3 above, there may be some changes to how we handle this case based on what to do [when the source package declares unused dependencies that the test package does not declare but uses](https://github.com/purescript/spago/pull/1092#discussion_r1362759323).
