### ISSUE TITLE
Slow to start compilation when many packages are in the workspace

### ISSUE THREAD

**Issue by finnhodgkin** [purescript/spago#1094]
I'm getting long pauses before compilation starts on projects with many workspace packages - above 100 - or if there are many nested dependencies. I'm guessing most projects won't reach the size where this starts to bite, but I'm getting waits of 5-10 seconds on a project with 50-100 packages.

I've created a [minimal reproduction repo](https://github.com/finnhodgkin/spago-dependency-tester) to see if I could spot any obviously lagging parts. The main bottleneck appears to be the transitive dependency fetching, specifically the many `Map.union` calls used to combine the different package deps. Swapping the unions to a single map that's updated less seems to speed things up nicely.

Setup | On master | After tweak
-- | -- | --
500 packages, each dependent on the last | 3m 44s | 19s
200 packages, each dependent on the last | 12s | 1.3s
100 packages, each dependent on the first 10 packages | 17s | 0.8s

All run on an m1 macbook with a very unscientifc timings setup... 

PR to follow that'll probably have a bunch of really obvious gotchas but is working locally and gets through the tests - thought I may as well 🤷

**Comment by f-f** [comment]
Amazing investigation - this is exactly the stress testing that we need before putting this in the hands of everyone. Appreciate this a lot ❤️

**Comment by f-f** [comment]
Fixed in #1095
