### ISSUE TITLE
Generated libraries not in version control will be ignored by workspace

### ISSUE THREAD

**Issue by finnhodgkin** [purescript/spago#1100]
Added for https://github.com/purescript/spago/issues/918

I didn't think of this because we don't do it anymore, but up until about a month ago at my work we would .gitignore all generated libraries. With spago@next these libs would also be ignored by the workspace. 

Rather than checking if a file is in .gitignore, could we add ignore globs for `node_modules` and/or nested `.spago` folders? Something like:
```purescript
result <- liftAff $ Glob.match' Paths.cwd [ "**/spago.yaml" ]
  { ignore: [ "spago.yaml", "**/node_modules/**", "**/.spago/**" ] }
```
From:
https://github.com/purescript/spago/blob/5884baed477b7a5920d0e0c5a686401ab413a0f5/src/Spago/Config.purs#L185-L192

This would have the added benefit of removing the slightly slow `Git.isIgnored` check on each yaml file.

**Comment by f-f** [comment]
Hmm, I'm a bit hesitant to go with this - if we hardcode a list, then surely at some point someone will want to configure it, so we'd need to add yet another config key for it..

I think it's worth thinking:
- if we can leave the git check in and deal with generated code in some other way - e.g. committing the `spago.yaml` files, but leave out the source files
- in case we really want to get rid of the git check, if we can both avoid a hardcoded list and a config setting

**Comment by finnhodgkin** [comment]
>  if we hardcode a list, then surely at some point someone will want to configure it

That's fair.

Sorry, I probably shouldn't have raised this issue given that it's not a problem for me anymore. Shall we just close this one? At least until someone who is actually impacted raises it again. No point making changes if the only user is me in the past...

**Comment by f-f** [comment]
Sounds good! I'll make sure to reference this the next time someone will bring this usecase up 🙂
