### ISSUE TITLE
pedantic_packages: packages marked unused after installing other packages

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/spago#1103]
The pedantic_packages check is quite nice. However, it appears that it will incorrectly mark dependencies as unused after a `spago install`.

For example, given the following files, Spago should warn that we have an undeclared transitive dependency on `effect`:

<details>
  <summary>project files</summary>

```yaml
workspace:
  package_set:
    registry: 43.1.0

package:
  name: tester
  dependencies:
    - console
    - prelude
  build:
    pedantic_packages: true
```

```purs
-- src/Main.purs
module Main where

import Prelude

import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = log "wat"
```
</details>

Indeed we get an error:

```console
❌ Sources for package 'tester' import the following transitive dependencies - please add them to the project dependencies, or remove the imports:
  effect
    from `Main`, which imports:
      Effect

Run the following command to install them all:
  spago install -p tester effect
```

However, if I then run the given install command to install `effect` — which is correct — all of a sudden my other dependencies are all marked as unused.

```console
➜ spago install -p tester effect
Reading Spago workspace configuration...
Read the package set from the registry

✅ Selecting package to build: tester

Adding 1 packages to the config in spago.yaml
Downloading dependencies...
Building...
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.

Looking for unused and undeclared transitive dependencies...

❌ Sources for package 'tester' declares unused dependencies - please remove them from the project config:
  - console
  - prelude
```

Obviously I can't remove those dependencies; if I instead just run another `spago build` everything is OK (though we should probably confirm that we didn't find any unused / undeclared dependencies instead of the lingering "Looking for ..." message).

```console
➜ spago build
Reading Spago workspace configuration...
Read the package set from the registry

✅ Selecting package to build: tester

Downloading dependencies...
Building...
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.

Looking for unused and undeclared transitive dependencies...
```

**Comment by f-f** [comment]
Ha, interesting. Note that `spago install` is now basically `spago build --deps-only` - it looks like it's running the pedantic packages check, but not considering the project sources when building (because it's been set as `deps_only`!). The bug should be somewhere in https://github.com/purescript/spago/blob/master/src/Spago/Command/Build.purs

**Comment by f-f** [comment]
Indeed. We get the globs only for the dependencies
https://github.com/purescript/spago/blob/23b22c980de7a6df9daa781e812df387a254af17/src/Spago/Command/Build.purs#L104-L106
..then we build with these globs, which is correct
https://github.com/purescript/spago/blob/23b22c980de7a6df9daa781e812df387a254af17/src/Spago/Command/Build.purs#L124
..but then we also get the graph with these same globs, which is not correct. We should be asking for the project sources too
https://github.com/purescript/spago/blob/23b22c980de7a6df9daa781e812df387a254af17/src/Spago/Command/Build.purs#L150

**Comment by f-f** [comment]
I think we should always get the graph with all the project globs, and then filter it later. Right now it's a chaotic situation, since we get the graph in multiple places with different parameters, and don't even cache that (so we might end up calling `purs graph` multiple times, which is slow

**Comment by JordanMartinez** [comment]
This is more involved than just a glob fix. When installing packages, we update the yaml doc and overwrite the `spago.yaml` file. However, we don't update the corresponding `workspace` value to include these new deps in the corresponding package's dependencies.

**Comment by JordanMartinez** [comment]
> This is more involved than just a glob fix. When installing packages, we update the yaml doc and overwrite the `spago.yaml` file. However, we don't update the corresponding `workspace` value to include these new deps in the corresponding package's dependencies.

To clarify, I'm not going to pursue this issue until I get more guidance from @f-f as to how I should approach this in a way that is satisfactory to him.

**Comment by f-f** [comment]
I have the feeling the fix with the best leverage here is to just not run the pedandic check when the `deps_only` flag is set: Spago is being asked to compile the dependency sources, so it's only fair if no project sources are considered in this. If no project sources are considered then there's no way we can properly check for improper dependencies.

That would mean changing this line
https://github.com/purescript/spago/blob/478e379f5b45fca632112443f8d6c72b1a25a3c7/src/Spago/Command/Build.purs#L148
to be
```purescript
unless (Array.null pedanticPkgs || depsOnly) do
```
