### ISSUE TITLE
Node shebang in minified and bundled browser app code

### ISSUE THREAD

**Issue by onslaughtq** [purescript/spago#1112]
It appears that there is a node shebang being output in our minified code when bundling our app for the browser. This is causing issues for a few of the users of our application, because security software is identifying our bundled/minified code as a shell script.

Should the shebang be there, or is this a mistake?
https://github.com/purescript/spago/blob/2f272e6d7db00645600318e327207d78a0b97c84/src/Spago/Command/Bundle.purs#L62C57-L62C57

**Comment by JordanMartinez** [comment]
Looks like a mistake to me. That should only appear if the platform chosen is Node.

**Comment by f-f** [comment]
Yep it's a bug

**Comment by onslaughtq** [comment]
Awesome, thank you!
