### ISSUE TITLE
Design of the `BuildInfo.purs` file

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#1128]
There's three questions I have.

#### Question 1: 1 record vs multiple values

In https://github.com/purescript/spago/pull/1126#issuecomment-1834665101, I asked why we currently output the `BuildInfo.purs` file's content as a single top-level record with all of the data there rather than outputting each field as its own top-level value.

In other words, why this
```purs
module Spago.Generated.BuildInfo where

buildInfo :: { packages :: <recordType>, pursVersion :: String, spagoVersion :: String }
buildInfo =
  { packages: { "foo": "1.2.3", "bar": "1.2.3" }
  , pursVersion: "1.2.3"
  , spagoVersion: "1.2.3"
  }
```
instead of this?
```purs
module Spago.Generated.BuildInfo where

packages :: <recordType>
packages =
  { "foo": "1.2.3"
  , "bar": "1.2.3"
  }

pursVersion :: String
pursVersion = "1.2.3"

spagoVersion :: String
spagoVersion = "1.2.3"
```

To me the latter makes more sense because then one can use such values via `BuildInfo.packages.foo` rather than `BuildInfo.buildInfo.packages.foo`.

#### Question 2: Adding inline directives

Related to the above. Since more and more people are using `purs-backend-es`, wouldn't it make sense to add inline directives for this value? That way, if some code should only be run when compiled with `purs >= 1.2.3`, the resulting code would optimize away that check? As of right now, I don't think it is optimized away.

#### Question 3: Publishing

What happens if a user happens to publish a library that uses the `Spago.Generated.BuildInfo` module? Wouldn't that cause problems for package sets and/or anyone using that library due to getting a duplicate module error in both situations? Are there any checks in the Registry to prevent this from happening?

**Comment by f-f** [comment]
Well I guess the easiest option is to just forbid it in the Registry - cc @thomashoneyman: we already have a list of forbidden module names in the Registry, how about we add this one too?

**Comment by thomashoneyman** [comment]
Sure, that's easy enough. Spago would inherit the check as far as publishing goes, too.
https://github.com/purescript/registry-dev/blob/d7d35c94cc286528e506a6a7ca78d22c84b251c9/lib/src/Operation/Validation.purs#L201-L207
