### ISSUE TITLE
No packages found due to `spago.yml` instead of `spago.yaml`

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#1136]
I ran `spago init` and then proceeded to manually setup a multi-package repo because no such command exists in spago right now. In doing so, I used the file name `spago.yml` rather than `spago.yaml`. So, `spago build` errored with no packages found. Since `*.yml` AFAIK is a valid yaml file extension, it may be worth notifying the user if a `spago.yml` file exists that they need to use `spago.yaml` instead.

**Comment by f-f** [comment]
The main reason why we have refused to deal with both extensions so far is that it's just a lot of corner cases. E.g. the situation where one has both a `spago.yaml` and a `spago.yml` is nonsensical. So I think we should try to see if a `spago.yml` is there, and tell the user to move it to the `.yaml` extension.

**Comment by flip111** [comment]
Would be good to look for `spago.yml` and then tell the user to rename this file, or offer to rename it

**Comment by flip111** [comment]
The error was on `build` not on `init`. So it could happen on a lot of other commands too that you expect it to put on a wrongly named config file. Should the check go here https://github.com/purescript/spago/blob/master/bin/src/Main.purs#L519 instead of adding the check individually for each command?

**Comment by f-f** [comment]
No, the check would go around the place where we try to read the config(s), so we're able to return a meaningful error (i.e. pointing to the actual path that we were trying to read, etc)

So somewhere around here: https://github.com/purescript/spago/blob/6fe57d88040c5031441b298c4f16a42bf270974a/src/Spago/Config.purs#L157-L159

**Comment by f-f** [comment]
Fixed in #1155
