### ISSUE TITLE
Building a second time gives "Cloning" message again

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1147]
```
» spago build
Reading Spago workspace configuration...

✅ Selecting package to build: project

Downloading dependencies...
Cloning https://github.com/purescript-contrib/purescript-aff.git
Cloning https://github.com/hdgarrood/purescript-ansi.git
Cloning https://github.com/coot/purescript-argonaut-aeson-generic.git
Cloning https://github.com/purescript-contrib/purescript-argonaut-codecs.git
Cloning https://github.com/purescript-contrib/purescript-argonaut-core.git
<...snip...>
```

When i run this a second time i get the same output again. However i suspect (correct me if i'm wrong) that it is not actually cloning again but using a cache. So if i'm wrong, it would be good if to use a cache, and if i'm right, i would prefer the message to be something like `Using cached version of <url>`

**Comment by f-f** [comment]
Yeah I noticed it as well, and it's weird. The second time it's indeed using the cache, so it should not print that message.

**Comment by flip111** [comment]
For full info: i aborted the first command halfway while "cloning", then it started from the start again on second run. Forgot to mention that.

**Comment by f-f** [comment]
Oh that's a good bit of info - this is expected then, since Spago might not have managed to finish the clone during the first execution

**Comment by f-f** [comment]
Cloning happens in parallel, so you're not guaranteed that the previous ones are done even if you get the log line about the next repo.

**Comment by flip111** [comment]
When i did it about ~30 repos started with cloning, then i aborted. Then on second try the same repos in the same order appeared. I don't believe that ~30 repos were still cloning. Perhaps looking deeper or with debug output would be good
