### ISSUE TITLE
Improve json output

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1151]
At the moment the json output `--json-errors` is mixed together with other output. For reading the output with a tool this is not so convenient because one has to search where the line with json is. The json output could be written to a file. Or it could use another out pipe. I noticed all spago output is written to stderr.

Is it only the help that is written to stdout?

**Comment by f-f** [comment]
Some other things are written to stdout, e.g. the output of `spago sources`, or `spago ls`, etc.
The general policy is that log messages go to stdout, while "result output", i.e. "stuff that you would pipe into other things" (such as the cases above) goes to stdout.

Output from other programs (such as `purs`) is piped directly.

You can use the `--quiet` flag to shut all the logging from Spago if you'd only like the output from the compiler, e.g. with `spago build --json-errors --quiet`

**Comment by flip111** [comment]
Hints to `--quiet` can be given [here](https://github.com/purescript/spago/blob/bcf3cd4ce34d101cebeff82510d743b10a7e0a23/bin/src/Flags.purs#L41) and [here](https://github.com/purescript/spago/blob/bcf3cd4ce34d101cebeff82510d743b10a7e0a23/README.md?plain=1#L336)
