### ISSUE TITLE
`spago.lock.yaml` uses OS-dependent path separator

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#1158]
If you run `spago build` on Windows, it'll update this repo's `spago.lack.yaml`'s `path:` fields to use `\` rather than `/`, causing a diff. Not exactly good for cross-OS development...

**Comment by f-f** [comment]
Oh? How is not CI catching this? We have tests for the lockfile..

**Comment by fsoikin** [comment]
It's because none of those tests have any non-root projects in doubly nested directories. You have to have a project like `docs-search/client-halogen` to get a path separator.

**Comment by f-f** [comment]
Yeah I was debugging #1240 on windows and noticed that - it looks like we'll need some more tests to catch this 🙂
