### ISSUE TITLE
`test:` or `tests:` in spago.yaml?

### ISSUE THREAD

**Issue by ad-si** [purescript/spago#1159]
The documentation says `test:` and `spago init` also creates a YAML file with `test:`.
However, `spago test` only seems to work with `tests:`.

**Comment by f-f** [comment]
We don't use the `tests` key - can you put together a small repro to demonstrate the problem?

The code that parses the configuration only looks for `test`: https://github.com/purescript/spago/blob/b450892d69aa3013861fde6c73299d2c17aba3dc/core/src/Config.purs#L91

**Comment by ad-si** [comment]
Haha, I know what's going on:
When I have a `tests:` field, it uses the default settings (since it ignores the `tests:` field).
When I rename it to `test:` I get an error because my `test.main` field was incorrect (`Test.Main.purs` instead of `Test.Main`).

Maybe there should be a warning if you specify undefined fields?

**Comment by JordanMartinez** [comment]
> Maybe there should be a warning if you specify undefined fields?

That'd probably be useful for clarifying what schema we expect, especially as the config file changes during this alpha work.

**Comment by f-f** [comment]
Good points - I opened #1165 to track this
