### ISSUE TITLE
json is cut off

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1160]
In php i run

```php
<?php

exec('spago build --json-errors --quiet', $output);
```

The json line is cut off after 65536 characters. I don't believe it's a php problem because when i use `cat` on a file with more characters the line is longer. When i run spago directly in the terminal the problem does not manifest. I believe it has something to do with the way nodejs writes to the output buffer.

When you google for `nodejs stdout cut off` quite a few old but i guess still relevant github issues pop-up. Some write actions can be asynchronous and are not guaranteed to finalize the nodejs process terminates.

**Comment by f-f** [comment]
Interesting - cc @JordanMartinez: do you have any ideas on how to improve this? I am not as well-versed in node streams as you are 😄

**Comment by MonoidMusician** [comment]
Yeah, how node works is that it buffers 65536 characters to write at a time (synchronously), and then it will not print any more until it reaches the next asynchronous tick in the event loop. I've run into this a lot when I have long-running synchronous code: I will see 65536 characters printed and then have to wait until it finishes that and reaches a new `Aff` action to see any more. I don't know how this interacts with the end of the process or with spago/execa.

**Comment by f-f** [comment]
Great then! Let's banish `Process.exit` and see if that fixes it
