### ISSUE TITLE
PSA stash option

### ISSUE THREAD

**Issue by onslaughtq** [purescript/spago#1162]
When using spago legacy, we had previously passed "--stash" as a purs argument.  Is there a way to pass this flag with the new version of spago?

**Comment by f-f** [comment]
We don't support stash because it just breaks down when using the IDE, since that will recompile your modules and "hide" the warnings from Spago.

To properly support it we'd need to patch the compiler to persist warnings.

**Comment by onslaughtq** [comment]
What's the current recommendation to see errors/warnings on a second build then?  If I do "spago build --strict" and miss fixing an error, the second time I run "spago build --strict", the error doesn't show up anymore

**Comment by f-f** [comment]
Indeed, and I don't have a good recommendation unfortunately - any solution that is not directly integrated in the compiler is going to be imprecise

At work we ended up with thousands of warnings and on other projects I work on (e.g. Spago itself) we have strict turned on, and whenever I want to make sure that there are no warnings I just remove `output`, issue a full rebuild, and go brew a coffee.
