### ISSUE TITLE
Support extra esbuild argument for GJS

### ISSUE THREAD

**Issue by TristanCacqueray** [purescript/spago#1163]
Hello, when running purescript with https://gjs.guide/ , the FFI needs such binding:

```js
import GLib from 'gi://GLib';
```

Which makes esbuild fail with:

```
✘ [ERROR] Could not resolve "gi://GLib"

    output/GLib.Variant/foreign.js:4:17:
      4 │ import GLib from 'gi://GLib';
        ╵                  ~~~~~~~~~~~

  You can mark the path "gi://GLib" as external to exclude it from the bundle, which will remove
  this error.
```

To make this work, we need to pass the following arguments: `"--external:gi://*"  "--external:resource://*"`.
Would it be possible to do that with spago, e.g. with a "ESBUILD_EXTRA_ARGS" env or something?

**Comment by f-f** [comment]
This is possible but not well documented - you can add these extra arguments as flags or in the config file, as spago itself does:
https://github.com/purescript/spago/blob/b450892d69aa3013861fde6c73299d2c17aba3dc/bin/spago.yaml#L28-L35

PR for documenting the flag as well would be welcome of course 🙂

**Comment by TristanCacqueray** [comment]
I see, thanks... now I need to migrate to this new spago :joy:
