### ISSUE TITLE
Issue warnings when the configuration has unrecognised fields

### ISSUE THREAD

**Issue by f-f** [purescript/spago#1165]
As noted e.g. in #1159, the fact that we just ignore fields that we don't parse means that it's possible to get the names of the fields wrong and not know about it.

I am not sure how the fix for this one would look like - I think either we'll end up doing some low-level parsing with the `yaml` library in [Config.js](https://github.com/purescript/spago/blob/68b644644faf38f2d2ccbee7b02758de60a8f1c7/src/Spago/Config.js), or hopefully we can do something [in the Codec at the PS level](https://github.com/purescript/spago/blob/68b644644faf38f2d2ccbee7b02758de60a8f1c7/core/src/Config.purs#L66)

**Comment by thomashoneyman** [comment]
The relevant registry PR is merged, but #1272 isn't, so I'm reopening this.
