### ISSUE TITLE
Suggest version

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1167]
I imagine this would be a possible feature for later on. It would be cool when spago detects the toplevel functions of modules, when a function is removed or the type signature change then it should bump the major version as per https://semver.org/

when functions where added then it should bump the minor version

when all functions stayed the same the implementation was changed and it can suggest the patch version

Requires parsing and diffing of current tag in relation to previous tag. Suggestion for tag should show the changes in function signatures and ask whether to accept the suggestion or not. I can imagine it's a heavy feature likely it should go under a flag `--version-suggestion` or something.

**Comment by JordanMartinez** [comment]
:-1: from me. This is a large feature request that I don't think is very sustainable across compiler version changes. I think it would be better to develop this outside of Spago and only to integrate it into Spago once the tool has been shown to be accurate and used heavily by the wider community.

**Comment by flip111** [comment]
@f-f not sure what you mean with "only the compiler should be looking at those". Do you mean that other tools can not rely on the `externs.cbor` format or there are any other technical issues. Or do you mean out of some principle the compiler is forbidden to export information and make it readable for other tools?

I stumbled on this thread where thomas was referring to a use case of the registry https://github.com/purescript/purescript/issues/4247#issuecomment-1054761732 I'm not sure where the registry would use this exactly though.

I imagine the following parts are needed:

1. reading of `externs.cbor`. A quick seach reveals [an implementation for node](https://github.com/hildjj/node-cbor), but no FFI for purescript.
2. a place (i guess in `.spago` folder) where to store the externs file for a specific version. Since the externs can change in different git commits of the same package version i would just always override for a specific package version. It's up to the programmer then to first checkout a git commit of that version.
3. a diff of the externs
4. a UI presenting the findings. A recommendation on the console for a new version with below that a list of changed function headers with before and after.

**Comment by f-f** [comment]
> Do you mean that other tools can not rely on the `externs.cbor` format

Yes. These files are generated by the compiler for its own consumption, and are not part of the public API. They could (and do, in fact) change at any point in time, so other tools should not rely on them.

**Comment by flip111** [comment]
Found a haskell project that can serve as inspiration https://kowainik.github.io/projects/policeman
