### ISSUE TITLE
Possible feature to prevent overwriting source files

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1171]
When i tried bundle it overwrite an existing `index.js`, luckily i had that checked into version control. However spago could put a  `// generated by spago` at the top of the generated file. Then when bundling it could check if that files exist, and if it does check whether it can find `// generated by spago` then overwrite without asking.

**Comment by JordanMartinez** [comment]
It's not clear to me why this is a problem. What was your workflow that caused this to happen? 
Bundling code produces an artifact from source code that can be recreated by bundling again. IMO, overwriting the same file with a new bundle from slightly changed source code is normal. If one wrote some index.js file not based on source code and then overwrite the file with the output of a bundle call, that sounds more like user error to me.

**Comment by flip111** [comment]
There are plenty of tools that either ask if you want to overwrite and/or have special flags to force overwrite.

**Comment by JordanMartinez** [comment]
To me, this creates more of a problem than a solution. If this was supported and I want to run `spago bundle -p some-app`, I now always need to pass `--force` to it to get the workflow I explain above. So, such a feature would impede my workflow.

**Comment by flip111** [comment]
That's not what i am suggesting. It would overwrite automatically without flag when it detects `// generated by spago`
