### ISSUE TITLE
allow to exclude some .purs files from compiling

### ISSUE THREAD

**Issue by srghma** [purescript/spago#1203]
while I was doing https://github.com/natefaubion/purescript-tidy/pull/122

I found that I need a way to exlude .purs files in `lib/test/snapshots` folder (those .purs files are not really purescript code)

But cannot accomplish this

![2024-03-17-02pm-53-41-screenshot](https://github.com/natefaubion/purescript-tidy/assets/7573215/3d6f41ff-1d1c-4edd-b805-174216c26399)

**Comment by srghma** [comment]
```yaml
    execArgs:
      - "--exclude-files"
      - "snapshots/*" # TODO: doesnt work
      - "--exclude-files"
      - "test/snapshots/*" # TODO: doesnt work
      - "--exclude-files"
      - "lib/test/snapshots/*" # TODO: doesnt work
```

doesnt work too

**Comment by f-f** [comment]
Spago treats the `test` folder as _the place_ where to find tests - all the PureScript files in there will be treated as input sources for the test suite of the package.
This means that if you need some fixtures for the tests, as this is the case here, then you shouldn't be including them there. See [how in Spago itself](https://github.com/purescript/spago/tree/master/test-fixtures) we include them in the `text-fixtures` folder, that is outside of the `test` tree.
