### ISSUE TITLE
Publish a new version? 

### ISSUE THREAD

**Issue by roryc89** [purescript/spago#1226]
Would it be possible to publish the recent changes to npm? 

We have some work that is blocked until the char count for packages is increased to 150. 

I would make the PR myself but I'm not sure around the process. 

Thanks!

**Comment by f-f** [comment]
Ah yes, I meant to release after merging your PR, but got sidetracked - I just released [0.93.30](https://www.npmjs.com/package/spago/v/0.93.30) 🚀
