### ISSUE TITLE
Stuck at `purs graph`

### ISSUE THREAD

**Issue by CGenie** [purescript/spago#1243]
Hello,

I'm using spago 0.93.35 with purs 0.15.15. My project was building recently, but currently for some unknown reason, in `--verbose` mode it's stuck at:
```
[   94065ms] Called `purs graph`, decoding..
```
I tried to repeat that `purs graph` command, it does spit out a very large JSON object (containing 1185 keys).

Thing is, it's stuck for very long and CPU does crunch something.

Looking at source code, I think it might be decoding that large JSON for so long -- is it possible? And if so, is there a fix for this?

**Comment by f-f** [comment]
I wonder if you're hitting #1242 - a few questions to try to pinpoint the issue:
1. do you still experience the problem with version 0.93.32?
2. can you post debug output? (run with `-v` flag)

**Comment by CGenie** [comment]
BTW, the 0.93.32 build feels still slower than was was there previously. The purescript builds for me always were fast and now I'm visibly waiting for the `purs graph` step.

**Comment by f-f** [comment]
Ah I see - we switched json library in 0.93.31, can you try how's the performance with 0.93.30?

**Comment by f-f** [comment]
Btw I assume that you want the `graph` command to run, as you have `pedantic-packages` on, or some of the other options that require a graph. I guess we could do a better job at noting which of the options rely on the graph.

**Comment by CGenie** [comment]
> Ah I see - we switched json library in 0.93.31, can you try how's the performance with 0.93.30?

I don't see a large time difference between 0.93.30 and 0.93.32,  it's around 29 seconds for both and the transitive dependencies step is the longest.

Indeed I have `pedanticPackages` turned on as recommended in https://github.com/purescript/spago/issues/1211#issuecomment-2066083651 but I guess for dev builds it doesn't matter.

**Comment by f-f** [comment]
Do you happen to have a repo with many packages? I added additional logging, and I'm testing on [purescript-core](https://github.com/purescm/purescript-core) - it turns out the bottleneck is not the JSON decoding, but running the computations on the graph takes 1-2s per package:
```
[    3189ms] Called `purs graph`, decoding..
[    3195ms] Decoded the output of `purs graph` successfully. Analyzing dependencies...
[    3196ms] Checking imports for arrays
[    4471ms] Checking imports for assert
[    5696ms] Checking imports for console
[    6917ms] Checking imports for control
[    8144ms] Checking imports for datetime
[    9388ms] Checking imports for effect
[   10570ms] Checking imports for enums
[   11781ms] Checking imports for exceptions
[   12986ms] Checking imports for foldable-traversable
[   14189ms] Checking imports for foreign-object
[   15414ms] Checking imports for functions
[   16606ms] Checking imports for integers
[   17815ms] Checking imports for json
[   19027ms] Checking imports for lazy
[   20238ms] Checking imports for minibench
[   21496ms] Checking imports for numbers
[   22744ms] Checking imports for partial
[   24031ms] Checking imports for prelude
[   25256ms] Checking imports for quickcheck
[   26491ms] Checking imports for random
[   27738ms] Checking imports for record
[   28956ms] Checking imports for refs
[   30180ms] Checking imports for st
[   31429ms] Checking imports for strings
[   32664ms] Checking imports for unfoldable
[   33929ms] Checking imports for unsafe-coerce
```

**Comment by f-f** [comment]
@CGenie I just released 0.93.36 with additional logging - it looks like most of the time is being spent in `getModuleGraphWithPackage`

**Comment by CGenie** [comment]
I'm working on an open-source project:
https://gitlab.iscpif.fr/gargantext/purescript-gargantext

Please check out the `dev` branch.

You might be lucky just running:
```sh
yarn
yarn spago build
```
but if not, then try `nix -L develop` to use the `flake.nix` setup.

**Comment by peterbecich** [comment]
Here is another reproduction case for this:

https://github.com/peterbecich/purescript-bridge/tree/merge-iohk-3

```

$ nix develop

# in nix develop shell

$ spago graph modules --verbose
...
[    1565ms] Called `purs graph`, decoding..
```

`spago build` succeeds
```
$ spago build                  
Reading Spago workspace configuration...

✅ Selecting 3 packages to build:
    argonaut-round-trip-test
    example
    json-helpers-round-trip-test

Downloading dependencies...
Building...
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.

```

```
spago 0.93.35
purs 0.15.15
```
, tools provided by https://github.com/thomashoneyman/purescript-overlay

Thanks

**Comment by f-f** [comment]
I narrowed it down to this line taking 50ms for each dependency:
https://github.com/purescript/spago/blob/f130b33a2e98e9267549dc358add039ba9220d5f/src/Spago/Purs/Graph.purs#L104

I won't manage to have a look at this for a while, but this is a good pointer - I suspect the glob code can be improved; we swapped it out for a different implementation in https://github.com/purescript/spago/pull/1220, so 0.93.29 will have a different code path and might be faster - something to try out
