### ISSUE TITLE
feature request: test filter

### ISSUE THREAD

**Issue by peterbecich** [purescript/spago#1247]
Feature request for a way to filter tests by test name.

Something like
```
spago test -z one plus one
```
which would run all tests which include this substring.

---------------

Scala SBT supports this:
https://stackoverflow.com/a/22490924/1007926
```
testOnly *MySuite -- -z foo
```
> to run only the tests whose name includes the substring "foo".

Thanks

**Comment by f-f** [comment]
This is not a feature that Spago can support directly - the test framework+runner that you're using needs to provide the right hooks to let you filter tests.
What Spago can do is to provide a hook for letting you pass arguments to the running script, which it can do with `--backend-args`. This is the same thing that Scala allows you to do, the arguments after the `--` are passed to the test runner.

**Comment by f-f** [comment]
purescript-spec now supports this! See https://purescript-spec.github.io/purescript-spec/running/#running-under-node
