### ISSUE TITLE
Monorepo setup issue with duplicate `Test.Main` module

### ISSUE THREAD

**Issue by onslaughtq** [purescript/spago#1282]
When attempting to create a monorepo, if we have two packages, each with their own Test.Main module (`test/Test/Main.purs`), spago build reports an error
`Module Test.Main has been defined multiple times`

**Comment by f-f** [comment]
This is expected - you can't have two modules with the same name in a single build, so you should rename one of them.

You can configure each package to have a different entry point for tests, e.g. see how it's done in Spago itself:
https://github.com/purescript/spago/blob/188e61d9eeb278bf526389875baaa2f412398fd0/docs-search/index/spago.yaml#L34-L39

I'll close this ticket as I believe the above will be sufficient to solve the issue, but let's reopen it if we think there's something we can improve. (docs possibly?)
