### ISSUE TITLE
G-Data security vendor flags IP as malware

### ISSUE THREAD

**Issue by donarn** [purescript/spago#1289]
I was trying out Purescript over the weekend, only to have our IT Security team inform me this morning that Spago.exe was contacting a 'potentially dangerous IP' based on this report: https://www.virustotal.com/gui/ip-address/185.199.111.133/detection .
IP address in question belongs to GitHub.
any ideas on how to get this false positive fixed?

**Comment by f-f** [comment]
Have you contacted VirusTotal about it? Spago needs to be able to clone a few GitHub repos in order to work.

**Comment by f-f** [comment]
Great, thanks! I'll close this as it looks like there's not much we can do on our end.
