### ISSUE TITLE
Add `--tag` flag to `spago upgrade-set`

### ISSUE THREAD

**Issue by f-f** [purescript/spago#370]
Right now doing `spago init` tries to upgrade to the latest release of the set, so in order to have a replicable setup one needs to know the right version of `package-sets` and set that by hand in the `packages.dhall`

This is uncomfortable to do from a CLI-only perspective, so we should have some way to set the right package-sets version from CLI, and I propose something like
```
$ spago upgrade-set --tag psc-0.13.2-20190725
```

This would just set the version we pass in the `packages.dhall` (that is, without doing a lookup to see if this is an actual tag in there)

The usecase for this is e.g. to make life easier for [blog posts](https://thomashoneyman.com/articles/practical-profunctor-lenses-optics/), where you really want the code there to be working for long time and there's really no space to paste the entire `packages.dhall` (cc @thomashoneyman, does this make sense?)

**Comment by thomashoneyman** [comment]
Yes! That would be useful. It would be nice if `spago init --tag psc-0.13.2-20190725` were also a command, as I could then just suggest:

```sh
spago init --tag psc-0.13.2-20190725
spago install profunctor-lenses remotedata
```

**Comment by f-f** [comment]
@thomashoneyman 

> It would be nice if `spago init --tag psc-0.13.2-20190725` were also a command

Right, great idea

> Any reason to not do this?

It would be straightforward to call the github API and ask if that's actually a release tag, but the issue is that GitHub has a limit of 50 requests per IP per hour on unauthenticated requests, so it might unexpectedly fail for some users in crowded networks, so that's why I'm a bit wary of doing this

**Comment by thomashoneyman** [comment]
I see. In that case, still fully in support of this!

**Comment by menelaos** [comment]
Just a heads up that older `packages.dhall` files are currently not available via `https://github.com/purescript/package-sets/releases/download/{tag}/packages.dhall`. 

See e.g.:
```
# Works as expected
curl -L https://github.com/purescript/package-sets/releases/download/psc-0.13.2-20190715/packages.dhall

# Not Found
curl -L https://github.com/purescript/package-sets/releases/download/psc-0.13.0-20190713/packages.dhall
```

**Comment by f-f** [comment]
@jhrcek great point. We switched to putting the `packages.dhall` in releases with #322, and we currently support the old style for some things (e.g. upgrading the package set will detect the old style), but it's listed for removal in 1.0 (in #291), so I'd say it's fine if for the new features we only support the new style

**Comment by Woody88** [comment]
Hi @f-f, 

What are the requirements for this issue? 
So far my understanding is this: 
- Create a new flag called "tag" which accepts a package-set version, i.e: psc-0.13.2-20190725
- Set the upstream value in package.dhall using the tag value that was passed in

Should we use Github API to get the url for the tag? 
I read the discussion above but it isn't clear to me. 

Do you know what are the modules that will require modification?

**Comment by f-f** [comment]
Hi @Woody88, thanks for asking about this! I'll try to clarify both the spec and scope for this issue, together with giving a few entry points to the code.

I'd say the "definition of done" for this issue would be so that:
- we'd add a `--tag` flag to the `init` and `upgrade-set` commands
- when given this flag, Spago would try to find out (somehow) if there exist a package set with that tag, and if that's the case it should patch the `packages.dhall` (if found in the current location) with that tag. The code to do the patching is already implemented, but needs to be extracted from a local definition. It's here:
https://github.com/purescript/spago/blob/0323b527712b9808cf3ab7b428c79a6f43a2c646/src/Spago/PackageSet.hs#L60-L78
- now, the trickiest part about this issue is deciding how to find out if the provided tag is an existing release. Off the top of my head, there are three possible ways:
  1. We call the GitHub API and ask all the releases of `package-sets` (with lower limit at the release at the time of #322, because in there we changed the location of where we fetch the `packages.dhall` from), and then pick from there. The code for this can be added in the [GitHub module](https://github.com/purescript/spago/blob/master/src/Spago/GitHub.hs). This is the "most dynamic" way, but the riskiest one, because of the 50-request limit I mentioned above (i.e. this is likely to fail sometimes, which is not desiderable)
  2. Or we get the same list of releases at build time (so the same code as above calling the GitHub API, but in our [Template Haskell module](https://github.com/purescript/spago/blob/master/src/Spago/TH.hs), or just a bash script that pulls a json file that we literally version along the [other templates](https://github.com/purescript/spago/blob/master/src/Spago/Templates.hs)). Then at runtime we just consult this list and see if the tag is there. This is the "least dynamic" way, but it literally cannot fail, except for tags published after releasing that specific Spago version.
  3. Or we go the middle-way, and put this list of releases in the [package-sets-metadata repo](https://github.com/spacchetti/package-sets-metadata): this should be done by patching the [Curator app](https://github.com/purescript/spago/blob/master/app/Curator.hs) to hit the GitHub API as described above and put this list of releases somewhere in the repo (I guess my preference would be in a new file, like `packageSetsReleasesV1.json`). Then Spago can dynamically fetch that (as it does already with the `metadataV1.json` file) and consult this semi-static list of releases when deciding if the tag exists.

My preferred option would be 2+3, but the easiest to implement would be option 2 I think, so we can just go for that one for now. How does this sound?

**Comment by Woody88** [comment]
@f-f 
Thanks for the detailed explanation. I still need you to clarify a few things for me... sorry 😐.

First, let me tell you what I have done so far:
- Added the "--tag" flag as an option for "init" & "upgrader-set" https://github.com/Woody88/spago/blob/8b17a011143087b39c180ecab02b7385614028c1/app/Spago.hs#L425-L433
- Added the logic that fetches all the tags of package-sets
https://github.com/Woody88/spago/blob/8b17a011143087b39c180ecab02b7385614028c1/src/Spago/GitHub.hs#L58-L60
- Added TagVersion as parameter to the `upgradePackageSet` function https://github.com/Woody88/spago/blob/8b17a011143087b39c180ecab02b7385614028c1/src/Spago/PackageSet.hs#L48-L49

Now, I really would like to have option 2+3 as well, however, the approach is still not clear to me. 

Option 2: 
- do you want to pull the list of the tag once and save it in file say like so `/templates/packaget-sets-tags.json`? If so, it means that every time a new release is out we have to manually update it or call this function that will pull the list and overwrite the file, no?
- I can't seem to see where the upstream value in "package.dhall" is overwritten if it needs to be upgraded. It seems like we are only pulling "template/package.dhall".  So, once we have the tag version that the user passed and confirmed the tag version and the commit sha, what function do we pass those 2 values to which will override the value in "package.dhall"?

Option 3: 
- we are looking for something which will put the list that we got from option 2 and update the list from the package-sets-metadata? A function to similar to the one below: https://github.com/purescript/spago/blob/0323b527712b9808cf3ab7b428c79a6f43a2c646/app/Curator.hs#L387-L403
- if the above is correct will we be only using option 2 to update the package-sets-metadata repo, and confirm the tag by fetching `packageSetsReleasesV1.json`?

**Comment by f-f** [comment]
@Woody88 no worries at all! Your code looks good so far.

To answer your questions:

> do you want to pull the list of the tag once and save it in file say like so `/templates/packaget-sets-tags.json`? If so, it means that every time a new release is out we have to manually update it or call this function that will pull the list and overwrite the file, no?

Yes, and yes. However, we can offload the work of updating this file to the `Curator`, which already has automation to upgrade the `packages.dhall` file every time there's a new release, here:
https://github.com/purescript/spago/blob/0323b527712b9808cf3ab7b428c79a6f43a2c646/app/Curator.hs#L284-L293
If we are going to store a file with releases in the `package-sets-metadata` repo, then we can just patch this code to download and commit that file too.

> I can't seem to see where the upstream value in "package.dhall" is overwritten if it needs to be upgraded. It seems like we are only pulling "template/package.dhall". So, once we have the tag version that the user passed and confirmed the tag version and the commit sha, what function do we pass those 2 values to which will override the value in "package.dhall"?

This is happening in the `updateTag` function that I linked in my previous comment:
https://github.com/purescript/spago/blob/0323b527712b9808cf3ab7b428c79a6f43a2c646/src/Spago/PackageSet.hs#L60-L78

This function:
- takes the tag that we want to write in the `packages.dhall`
- reads the `packages.dhall` into a Dhall AST (line 64)
- patches into this AST the new tag (line 74)
- writes the AST to file (line 76) - note: this doesn't contain the SHA yet
- ..and computes the Dhall SHA in line 78

We can take this definition to the top level and reuse it almost as it is - we'll have to change the logging and probably some conditions so that it's relevant to both cases.

> we are looking for something which will put the list that we got from option 2 and update the list from the package-sets-metadata? A function to similar to the one below

Yes, we should change the `metadataUpdater` function that you linked to also fetch the list of tags and commit that to a file in the `package-sets-metadata`

> if the above is correct will we be only using option 2 to update the package-sets-metadata repo, and confirm the tag by fetching `packageSetsReleasesV1.json`?

I think the algorithm should be:
- we include the `packageSetsReleasesV1.json` file statically in Spago (in the `Spago.Templates` module)
- when we get a tag from the user we first check that file
- if we don't find the tag there, then we download the new version from the repo
