### ISSUE TITLE
Run package-set commands without `spago.dhall` present

### ISSUE THREAD

**Issue by elliotdavies** [purescript/spago#393]
Some commands such as `verify-set` and `list-packages` don't work if a `spago.dhall` file is missing from the current directory. This can feel weird in a monorepo setup where (for example) there's a root `packages.dhall` and multiple `spago.dhall`s in sub-directories, because it means the commands must be run from a sub-directory away from the actual package-set definition. This is also the opposite behaviour from commands like `upgrade-set` and `freeze` which can _only_ be run in the same directory as `packages.dhall`.

I guess we should go through the commands, figure out whether they're a "requires `packages.dhall`" or a "requires `spago.dhall`", and fix them appropriately - I'm not sure how much reorganisation this might require. The Spago help text already informally sorts commands into "project" and "package-set" lists so we could also sync up with that.

This likely relates to #349.

**Comment by f-f** [comment]
@elliotdavies good point, and yes this kind of relates to #349, but in a funny way: if we have commands search for the `packages.dhall` then they would fail in folders where there isn't one
So we'd need the resolution from #349, or some kind of fallback like "search for the `packages.dhall` first, if not found just read the `spago.dhall` and get the `PackageSet` from there"

There is no particular reason why `verify` requires a `spago.dhall`, but the reason why `list-packages` does is that you can pass `--filter=transitive` and `--filter=direct`, in which case Spago would need the list of dependencies in the config.
On the other hand I was thinking about splitting that command into `spago ls package-set` (which wouldn't require a `spago.dhall`) and `spago ls deps` and `spago ls transitive` (which would).
The next release is going to be breaking anyways so this could be a good moment to implement this
