### ISSUE TITLE
Show warning if package is added to packages.dhall's additions, but not listed as dependency in spago.dhall

### ISSUE THREAD

**Issue by ad-si** [purescript/spago#462]
I think I remember we've talked about this before, but I can't remember what the consensus was. Also this just cost me half an hour (again), and It think it's still a big issue!

**Comment by elliotdavies** [comment]
I don't think this would hold up in a monorepo scenario where you have a single, shared `packages.dhall` but many projects each with their own `spago.dhall`.

However there was some discussion in https://github.com/spacchetti/spago/issues/165 about figuring out the `spago.dhall` dependencies automatically, which would remove the duplication.

**Comment by f-f** [comment]
@ad-si thanks for reporting this, and I agree, it's a very common issue that we could prevent

@elliotdavies that's a great point, I wonder if we are able to reliably detect such situation and disable this behaviour?

**Comment by f-f** [comment]
Taking a look after a while, it looks like we wouldn't really be able to solve this in the case of monorepos. I'll close for now, but let's reopen if we get any more insights

**Comment by ad-si** [comment]
Why not check if the repo is monrepo and then skip the warning?

**Comment by f-f** [comment]
@ad-si how would we do that in a reliable way?

**Comment by ad-si** [comment]
Isn't it as simple as this? 🤔

1. Go upwards until the level of the `packages.dhall` is reached
2. Check if directory tree contains several `spago.dhall` (with a maximum depth of 2 or so)

**Comment by f-f** [comment]
Yeah that sounds sensible. I'm still skeptical about how reliable it is to do this (i.e. how many false positives we'd get), but cannot come up with example of this right now, so let's go with this.

Note that we already have some machinery to find "the root `packages.dhall`":
https://github.com/purescript/spago/blob/8c44f1c149f6a41df45931ec05f361742b31cd1c/src/Spago/PackageSet.hs#L235

I'll reopen this

**Comment by f-f** [comment]
Now that we are considering a new config format in #842 with a first-class-support for monorepos in a single config this would really not be achievable anymore, so I'll close for now. Let's reopen if there are any new developments on this front
