### ISSUE TITLE
Ignore emacs tempfiles in `--watch`

### ISSUE THREAD

**Issue by f-f** [purescript/spago#477]
As noted in https://github.com/spacchetti/spago/issues/465#issuecomment-546569568, emacs creates some temporary files that trigger unnecessary rebuilds when using the  `--watch` flag. We should just ignore these files (unless we find a usecase for not ignoring them, in which case we can make this configurable)

**Comment by gomain** [comment]
**Work around**

in _spago.dhall_ file do

``` dhall
sources = [ "src/**/[!.]*.purs", "test/**/[!.]*.purs" ]
```

to include only files not starting with a `.`

**Comment by gomain** [comment]
Would be nice if spago just ignored all the .gitignore files.
