### ISSUE TITLE
`spago run --watch` recompiles but doesn't rerun

### ISSUE THREAD

**Issue by f-f** [purescript/spago#506]
It looks like this happens because Spago fires up a Nodejs process that might not terminate. When reloading the watcher the old process is left running and a new one is started.

We should instead keep track of the old `ProcessHandle` (see [here](http://hackage.haskell.org/package/process-1.6.7.0/docs/System-Process.html#v:createProcess) for how to make one) and kill that in the watcher

**Comment by whitecolor** [comment]
Yes, it is quite strange, watch but not re-run).

**Comment by f-f** [comment]
We don't support watching in Spago anymore, see https://github.com/purescript/spago/issues/1029
