### ISSUE TITLE
Check that `psci-support` is installed when starting a repl

### ISSUE THREAD

**Issue by f-f** [purescript/spago#550]
We should check that we're including the `psci-support` as a package when starting a `spago repl`, as the error message can be quite misleading, e.g. see [this thread](https://discourse.purescript.org/t/spago-repl-fails-to-star/1113).

**Comment by gcsolaroli** [comment]
@f-f, could you please provide some rough hints on where to start looking into the spago code base for this issue?

**Comment by f-f** [comment]
@gcsolaroli yes, thanks for asking :slightly_smiling_face: 

Basically the implementation for the repl command is here:
https://github.com/spacchetti/spago/blob/cc755561d992406533e0ca1fd2fe4087c047a7bb/src/Spago/Build.hs#L172-L179

..and the line that collects the dependencies before starting the repl is this one:
https://github.com/spacchetti/spago/blob/cc755561d992406533e0ca1fd2fe4087c047a7bb/src/Spago/Build.hs#L184

..so before going forward in the code we should check that a `Package` called `psci-support` is included in `deps`

Does it make sense? I can detail further if there's anything unclear

**Comment by gcsolaroli** [comment]
I'll give it a try, thanks.

**Comment by JordanMartinez** [comment]
I think this issue also needs to ensure that `psci-support` has been installed before `spago repl` starts (and this check only occurs if the directory in which `spago repl` is run has a `spago.dhall` file in it)

**Comment by f-f** [comment]
@JordanMartinez this is already happening as of the latest `master`, see #611
