### ISSUE TITLE
Watch `spago.yaml` when in watch mode, so that we pick up new packages

### ISSUE THREAD

**Issue by f-f** [purescript/spago#572]
In #570 we figured that if a user does a `spago install` while a `spago build -w` is running, then the new package is not picked up. We could fix this by watching the `spago.dhall` (or whatever config file is being used), and dynamically loading the source paths in the watcher

**Comment by BebeSparkelSparkel** [comment]
could you also watch `package.dhall`?

**Comment by f-f** [comment]
We don't support watching in Spago anymore, see #1029
