### ISSUE TITLE
Spago should respect TERM=dumb or TERM=win

### ISSUE THREAD

**Issue by bbarker** [purescript/spago#579]
See e.g. https://github.com/9fans/plan9port/issues/180#issuecomment-423258108

I'd like to disable escape sequences from output when not using spago from a live terminal, e.g., for logging.

**Comment by f-f** [comment]
@bbarker great point :+1: 

Does using `--no-color` work for now?

**Comment by bbarker** [comment]
Yes, thanks for pointing that out! I was using an older version of `spago` in my container that didn't have that option.

**Comment by f-f** [comment]
Fix up in #581
