### ISSUE TITLE
Output global cache dir in `spago path`

### ISSUE THREAD

**Issue by elliotdavies** [purescript/spago#591]
At the moment it's a bit hard to tell where the global cache lives. `spago install -v` will output its path, as mentioned in the README, but only if the installation process actually runs. If the project is already fully installed, the path won't be printed.

I'd suggest printing the cache dir as part of `spago path`, which already lists the `output` directory being used. (Also perhaps that should be `spago paths`?)

**Comment by f-f** [comment]
@elliotdavies yes this is a good idea!

I don't have a strong opinion on `spago path` vs `spago paths`, but I'll just note that:
- less chars to type is usually better
- Stack uses `path` too
