### ISSUE TITLE
Install autocompletions

### ISSUE THREAD

**Issue by f-f** [purescript/spago#592]
I'd like to have the npm install script also configure the autocompletion for Spago. We can produce an [autocompletion script](https://github.com/pcapriotti/optparse-applicative/wiki/Bash-Completion) already, but I'm not sure how to install it.

Some useful links to dig more into this: [1](http://source.git-annex.branchable.com/?p=source.git;a=blob;f=Makefile;h=965f53e1fc4a8f6d69041eabaccd759268f6490f;hb=HEAD), [2](https://github.com/python-poetry/poetry#enable-tab-completion-for-bash-fish-or-zsh)

**Comment by hdgarrood** [comment]
I manage my bash configuration in a git repository with different concerns split out into different scripts, so trying to do this in an automated way is more or less guaranteed to not do what I want. In general I think it's bad etiquette to modify dotfiles in $HOME automatically (unless those dotfiles specifically relate to the program which is modifying them, ie I don't mind git modifying `~/.gitconfig`). See also https://github.com/NixOS/nix/issues/1209 which is me whinging about Nix doing this. It might be uncommon for people to organize their dotfiles like I do, but even for people who just have a single giant `.bashrc` file, they probably will want to keep that file organized, say, by putting all the completion scripts together, which again isn't really possible if the file is being modified automatically.

**Comment by f-f** [comment]
@hdgarrood sure, we could ask for confirmation or add a flag for this, but I'd consider this an implementation detail compared to setting this up in the first place - e.g. I did not manage to install autocompletions for my shell even when doing it by hand, so I don't think it's straightforward to automate this

**Comment by s0kil** [comment]
Here is a good resource: https://github.com/scop/bash-completion/blob/master/README.md#faq

Got the bash completions working without modifying `.bashrc` by:
```
spago --bash-completion-script $(which spago) >> ~/.bash_completion
```
so far this seems to be the only method without having permissions to write into `/etc/bash_completion.d/spago`

Note: `~/.bash_completion` is a file, so we append to it.
