### ISSUE TITLE
How to setup project to be able to call purescript function from javascript ?

### ISSUE THREAD

**Issue by flip111** [purescript/spago#596]
I'm using this setup https://github.com/purescript/spago#get-started-from-scratch-with-parcel-frontend-projects

And run `npm run dev`.

The purescript manual says i should be able to execute `shout(require('Prelude').showNumber)(42);`. This doesn't work though. I tried instead `console.log(require('../../output/Prelude'));` but this gave an empty object because there are no functions in the prelude javascript file

index.js in Prelude folder:
```javascript
// Generated by purs version 0.13.6
"use strict";
module.exports = {};
```

Anyway what i really wanted to do is convert a Set into a List (because a Set structure is a pita to work with in JS). So i did `let opt = require('../../output/Data.Set').toUnfoldable(mySet);` this works as it's calling the right function. But it then crashes in this code.

From Data.List
```javascript
var toUnfoldable = function (dictUnfoldable) {
    return Data_Unfoldable.unfoldr(dictUnfoldable)(function (xs) { // <-- crash point
        return Data_Functor.map(Data_Maybe.functorMaybe)(function (rec) {
            return new Data_Tuple.Tuple(rec.head, rec.tail);
        })(uncons(xs));
    });
};
```

```
TypeError: Data_Unfoldable.unfoldr(...) is not a functionclient.e31bb0bc.js:16462:49
    toUnfoldable http://localhost:1234/client.e31bb0bc.js:16462
    toUnfoldable http://localhost:1234/client.e31bb0bc.js:23010
    new http://localhost:1234/client.e31bb0bc.js:23319
    handleAction http://localhost:1234/client.e31bb0bc.js:52021
    $tco_loop http://localhost:1234/client.e31bb0bc.js:33695
    toView http://localhost:1234/client.e31bb0bc.js:33719
    go http://localhost:1234/client.e31bb0bc.js:34053
    go http://localhost:1234/client.e31bb0bc.js:28850
    go http://localhost:1234/client.e31bb0bc.js:28858
    _run http://localhost:1234/client.e31bb0bc.js:24432
    step http://localhost:1234/client.e31bb0bc.js:24510
    drain http://localhost:1234/client.e31bb0bc.js:24268
    enqueue http://localhost:1234/client.e31bb0bc.js:24291
    step http://localhost:1234/client.e31bb0bc.js:24499
    eventListener http://localhost:1234/client.e31bb0bc.js:29240
```

Data.Set.toUnfoldable looks like this
```javascript
var toUnfoldable = function (dictUnfoldable) {
    var $63 = Data_List.toUnfoldable(dictUnfoldable);
    return function ($64) {
        return $63(toList($64));
    };
};
```

How must the project be setup so that the code in the output folder can use each other's functions? And how can i use just `require('Data.Set')` rather than working with relative paths?

**Comment by f-f** [comment]
@flip111 thanks for the report. I'm not entirely sure of what's happening here, some comments/ideas:
- I don't know why the `output/Prelude/index.js` file is empty
- in my experience when calling PS from JS, the least painful approach is to implement the whole logic in PureScript, and then call from JavaScript only the high-level functions that return "business-meaningful" results - I never tried doing the low-level interop that you're attempting here
- this doesn't look like a bug in Spago, but a more generic "purescript project setup" question, so you might have more support if you ask in the `#purescript` channel in the [FP slack](https://fpchat-invite.herokuapp.com/)

**Comment by hdgarrood** [comment]
@flip111 I can help but can we move the discussion to [Discourse](https://discourse.purescript.org/) please?

**Comment by flip111** [comment]
@hdgarrood ok the copy can be found here https://discourse.purescript.org/t/how-to-setup-a-project-with-spago-to-be-able-to-call-a-purescript-function-from-javascript/1232

@f-f spago covers how to setup your project, i think it's in scope of spago to discuss this. Spago bundles all javascript into a single file. But it can also give instructions in the readme how to call other parts of purescript from the bundled file because FFI is also parts of purescript. See https://github.com/purescript/spago#get-started-from-scratch-with-parcel-frontend-projects I'm not saying it's a bug, but if it ends up that i'm not causing this problem then it seems there is room for improvement in either the readme file or something in the code.

**Comment by flip111** [comment]
Here are some possibilities for not having to work with relative path https://gist.github.com/branneman/8048520 I don't really like any of them. Perhaps the NODE_PATH one is the best. If i can get that to work so things like `require('Data.Set')` can be done i could update the readme with this additional information.

**Comment by f-f** [comment]
It looks like solutions for these issues were suggested in the Discourse thread, so I'm not sure what needs to be done here on the Spago side. I'll close this one for now, but feel free to reopen if there's some actionable feedback we could implement (e.g. documentation fixes, etc)
