### ISSUE TITLE
Be able to inject build meta data into the compiled result

### ISSUE THREAD

**Issue by stacycurl** [purescript/spago#599]
Scenario: I want to show the version of the current code, or the time it was built, the git branch, spago version, etc.

A workaround I've applied manually is to add this to my code: 
```
BuildInfo  { timestamp ∷ Int }
buildInfo = BuildInfo { timestamp: 123345 }
```

and then commit unholy acts using sed on the resulting js

```
#!/bin/bash
JS_FILE=output/Build/index.js
TIMESTAMP=$(date +"%s")
sed -i "" "s/timestamp:[^,]*/timestamp: $TIMESTAMP/g" $JS_FILE
```

and place that before invoking spago.

Example from Scala: https://github.com/sbt/sbt-buildinfo.

**Comment by f-f** [comment]
The new Spago supports this, generating a module called `Spago.Generated.BuildInfo` that is built together with your source. It does not include timestamps yet, but it does include the version numbers for both Spago and the package being built.
