### ISSUE TITLE
Possible to replace pulp for publishing packages ?

### ISSUE THREAD

**Issue by flip111** [purescript/spago#603]
When reading https://pursuit.purescript.org/help/authors and the commands there.

I noticed that spago can already do the docs. So `spago docs` instead of `pulp docs -- --format html`.

Is it possible, or are there plans to support the other command through spago as well?

* `pulp version`
* `pulp login`
* `pulp publish`

**Comment by klntsky** [comment]
See #396 for context.

**Comment by f-f** [comment]
And #204 

Also quoting my comment from #396:

> the publishing situation is a bit weird right now since we are transitioning to a different package registry. One of my goals with the new registry is to make this version conflict less awkward and things easy for Spago - but things are still in flux so I cannot say more right now

**Comment by f-f** [comment]
I'll also add that if anyone wants to implement the flow that `pulp publish` has right now as `spago publish` that would be fine by me - I just won't do any work on it myself as I'm focusing on getting the registry running

**Comment by flip111** [comment]
Ok i understand, thanks for the information.
