### ISSUE TITLE
Install dependencies before attempting to start a repl

### ISSUE THREAD

**Issue by hdgarrood** [purescript/spago#611]
Currently, `spago repl` does not check that the dependencies listed in `spago.dhall` are installed before attempting to start a repl. For example:

```
$ mkdir spago-repl-test
$ cd spago-repl-test
$ spago init
[info] Initializing a sample project or migrating an existing one..
[info] Upgrading the package set version to "psc-0.13.6-20200404"
[info] Package-set upgraded to latest tag "psc-0.13.6-20200404"
Fetching the new one and generating hashes.. (this might take some time)
[info] Generating new hashes for the package set file so it will be cached.. (this might take some time)
[info] Set up a local Spago project.
[info] Try running `spago build`
$ spago repl
purs repl: PSCi requires the psci-support package.
For help getting started, visit https://github.com/purescript/documentation/blob/master/guides/PSCi.md
spago: callCommand: purs repl ".spago/console/v4.4.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"  (exit 1): failed
```
but if I run `spago build` first, then `spago repl` works. I would have expected `spago repl` to ensure that dependencies are installed before attempting to start the repl, much like `spago build` ensures that dependencies are installed before attempting to invoke the compiler. Is the current behaviour intentional?

**Comment by f-f** [comment]
This was fixed in #610 (see [here](https://github.com/purescript/spago/blob/0e70a23247a37181365191b06f3c73a8db5a8a8a/src/Spago/Build.hs#L165) for the place where this happens), I'll cut a release shortly

**Comment by hdgarrood** [comment]
Great news. Thanks 🙂

**Comment by f-f** [comment]
You're welcome :slightly_smiling_face:
