### ISSUE TITLE
bundle-module not exporting re-exported module

### ISSUE THREAD

**Issue by nakamin** [purescript/spago#622]
I have this PureScript code
```purescript
module Main (runLogic2020, module Logic2020.Data) where

...
import Logic2020.Data (Argument, Command, Logic2020Error, ShowLine)
...
```
I run `spago build-module`, the resulting CommonJS module exposes only the runLogic2020 function, and not the `Logic2020.Data` module. I wish to publish my PureScript code on npm and use it from JS projects, which require acess to the types defined in the module I'm trying to re-export. Also I can't just migrate the types I need into the Main module since I'll have a dependency cycle. Is there any way to accomplish what I want?

**Comment by f-f** [comment]
@nakamin I'm not sure what the answer to this question is, and it's not really Spago-related, as all the logic for bundling is defined in the compiler, and Spago just invokes `purs` in this case.

So I'd suggest moving this question to [Discourse](https://discourse.purescript.org/), where I'm sure you'll get a more useful answer :slightly_smiling_face:

**Comment by nakamin** [comment]
Ok thanks.

**Comment by f-f** [comment]
You're welcome!
