### ISSUE TITLE
'spago build' fails to find purs on Windows 10

### ISSUE THREAD

**Issue by kelden** [purescript/spago#635]
spago 0.15.2
purs 0.13.6
nvm 1.17
node 14.1.0
npm 6.14.4

Just following the [purescript book](https://book.purescript.org/chapter2.html), everything works great until I get to `spago run`, which gives me:

```
C:\Users\redacted\Documents\src\purescript\my-project>spago run
[31m[error] [0mExecutable was not found in path: "purs"[0m
[34m[info] [0mInstallation complete.[0m
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
[error] Failed to build.
```

Running `spago -V build` gets:
```
C:\Users\redacted\Documents\src\purescript\my-project>spago -V build
[90m2020-05-02 11:41:25.124986: [32m[debug] [0mRunning `getGlobalCacheDir`[90m
@(src\Spago\RunEnv.hs:43:7)[0m
[90m2020-05-02 11:41:25.147116: [32m[debug] [0mTransformed config is the same as the read one, not overwriting it[90m
@(src\Spago\Config.hs:364:14)[0m
[90m2020-05-02 11:41:25.178362: [32m[debug] [0mEnsuring that the package set is frozen[90m
@(src\Spago\PackageSet.hs:275:3)[0m
[90m2020-05-02 11:41:25.209606: [31m[error] [0mExecutable was not found in path: "purs"[90m
@(src\Spago\Prelude.hs:128:13)[0m
[90m2020-05-02 11:41:25.209606: [32m[debug] [0mExitFailure 1[90m
@(src\Spago\RunEnv.hs:128:9)[0m
[90m2020-05-02 11:41:25.225227: [32m[debug] [0mRunning `spago build`[90m
@(src\Spago\Build.hs:58:3)[0m
[90m2020-05-02 11:41:25.225227: [32m[debug] [0mGetting transitive deps[90m
@(src\Spago\Packages.hs:129:3)[0m
[90m2020-05-02 11:41:25.225227: [32m[debug] [0mRunning `fetchPackages`[90m
@(src\Spago\FetchPackage.hs:41:3)[0m
[90m2020-05-02 11:41:25.240848: [32m[debug] [0mChecking if `purs` is up to date[90m
@(src\Spago\PackageSet.hs:183:3)[0m
[90m2020-05-02 11:41:25.309847: [34m[info] [0mInstallation complete.[90m
@(src\Spago\FetchPackage.hs:69:3)[0m
[90m2020-05-02 11:41:25.309847: [32m[debug] [0mCompiling with "C:\\Program Files\\nodejs\\purs.cmd"[90m
@(src\Spago\Purs.hs:29:3)[0m
[90m2020-05-02 11:41:25.309847: [32m[debug] [0mRunning command: `C:\Program Files\nodejs\purs.cmd compile  ".spago/console/v4.4.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"`[90m
@(src\Spago\Purs.hs:121:3)[0m
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
2020-05-02 11:41:25.341090: [error] Failed to build.
@(src\Spago\Prelude.hs:128:13)
```

I'm guessing [this line](https://github.com/purescript/spago/blob/58bb1d45da5372b02fdeff7965170d483909faef/src/Spago/Prelude.hs#L233) needs to escape spaces, or surround paths with quotes like this?
```
 Just path -> pure $ Text.pack $ "\"" <> path <> "\""
```

I will try building from stack and submitting a pull request if it works. Sound good?

**Comment by f-f** [comment]
@kelden thanks for the report! And yes, if you find a fix PRs are welcome :slightly_smiling_face:

**Comment by kelden** [comment]
Ok, so I replaced the line I mentioned and now it gives the correct quoted version, but I get the same error:
```
C:\Users\redacted\Documents\src\purescript\my-project>spago -V build
[90m2020-05-02 15:09:48.029051: [32m[debug] [0mRunning `getGlobalCacheDir`[90m
@(src\Spago\RunEnv.hs:43:7)[0m
[90m2020-05-02 15:09:48.044644: [32m[debug] [0mTransformed config is the same as the read one, not overwriting it[90m
@(src\Spago\Config.hs:364:14)[0m
[90m2020-05-02 15:09:48.082398: [32m[debug] [0mEnsuring that the package set is frozen[90m
@(src\Spago\PackageSet.hs:275:3)[0m
[90m2020-05-02 15:09:48.113640: [31m[error] [0mExecutable was not found in path: "purs"[90m
@(src\Spago\Prelude.hs:127:13)[0m
[90m2020-05-02 15:09:48.113640: [32m[debug] [0mExitFailure 1[90m
@(src\Spago\RunEnv.hs:128:9)[0m
[90m2020-05-02 15:09:48.113640: [32m[debug] [0mRunning `spago build`[90m
@(src\Spago\Build.hs:58:3)[0m
[90m2020-05-02 15:09:48.129293: [32m[debug] [0mGetting transitive deps[90m
@(src\Spago\Packages.hs:129:3)[0m
[90m2020-05-02 15:09:48.129293: [32m[debug] [0mRunning `fetchPackages`[90m
@(src\Spago\FetchPackage.hs:41:3)[0m
[90m2020-05-02 15:09:48.129293: [32m[debug] [0mChecking if `purs` is up to date[90m
@(src\Spago\PackageSet.hs:183:3)[0m
[90m2020-05-02 15:09:48.198321: [34m[info] [0mInstallation complete.[90m
@(src\Spago\FetchPackage.hs:69:3)[0m
[90m2020-05-02 15:09:48.198321: [32m[debug] [0mCompiling with "\"C:\\Program Files\\nodejs\\purs.cmd\""[90m
@(src\Spago\Purs.hs:29:3)[0m
[90m2020-05-02 15:09:48.213962: [32m[debug] [0mRunning command: `"C:\Program Files\nodejs\purs.cmd" compile  ".spago/console/v4.4.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"`[90m
@(src\Spago\Purs.hs:121:3)[0m
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
2020-05-02 15:09:48.229562: [error] Failed to build.
@(src\Spago\Prelude.hs:127:13)
```

Which is odd, because

1. Actually running `"C:\Program Files\nodejs\purs.cmd" compile  ".spago/console/v4.4.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"` in my console compiles the program.
2. It says that the `Executable was not found in path: "purs"`, and yet `Checking if `purs` is up to date` doesn't fail.

Why does pasting `command` in my shell work but `shell command empty` fail? I thought that it may simply be an issue with my Windows environment and not spago. Node version manager adds an environment variable to my path, %NVM_SYMLINK%, which is set to C:\Program Files\nodejs. I tried changing it to C:\Progra~1\nodejs to sidestep the whitespace issue, which gets me:
```
C:\Users\redacted\Documents\src\purescript\my-project>spago -V build
[90m2020-05-02 14:16:18.070925: [32m[debug] [0mRunning `getGlobalCacheDir`[90m
@(src\Spago\RunEnv.hs:43:7)[0m
[90m2020-05-02 14:16:18.086545: [32m[debug] [0mTransformed config is the same as the read one, not overwriting it[90m
@(src\Spago\Config.hs:364:14)[0m
[90m2020-05-02 14:16:18.133409: [32m[debug] [0mEnsuring that the package set is frozen[90m
@(src\Spago\PackageSet.hs:275:3)[0m
[90m2020-05-02 14:16:18.155540: [31m[error] [0mExecutable was not found in path: "purs"[90m
@(src\Spago\Prelude.hs:127:13)[0m
[90m2020-05-02 14:16:18.155540: [32m[debug] [0mExitFailure 1[90m
@(src\Spago\RunEnv.hs:128:9)[0m
[90m2020-05-02 14:16:18.155540: [32m[debug] [0mRunning `spago build`[90m
@(src\Spago\Build.hs:58:3)[0m
[90m2020-05-02 14:16:18.155540: [32m[debug] [0mGetting transitive deps[90m
@(src\Spago\Packages.hs:129:3)[0m
[90m2020-05-02 14:16:18.171160: [32m[debug] [0mRunning `fetchPackages`[90m
@(src\Spago\FetchPackage.hs:41:3)[0m
[90m2020-05-02 14:16:18.171160: [32m[debug] [0mChecking if `purs` is up to date[90m
@(src\Spago\PackageSet.hs:183:3)[0m
[90m2020-05-02 14:16:18.240151: [34m[info] [0mInstallation complete.[90m
@(src\Spago\FetchPackage.hs:69:3)[0m
[90m2020-05-02 14:16:18.240151: [32m[debug] [0mCompiling with "\"C:\\Progra~1\\nodejs\\purs.cmd\""[90m
@(src\Spago\Purs.hs:29:3)[0m
[90m2020-05-02 14:16:18.240151: [32m[debug] [0mRunning command: `"C:\Progra~1\nodejs\purs.cmd" compile  ".spago/console/v4.4.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"`[90m
@(src\Spago\Purs.hs:121:3)[0m
The system cannot find the path specified.
2020-05-02 14:16:18.271399: [error] Failed to build.
@(src\Spago\Prelude.hs:127:13)
```

Weird.

Again, copying and pasting the string spago prints as it's running command works fine. [Looking deeper, the version check](https://github.com/purescript/spago/blob/5beef6723a0756d3661e87746d6d08847cf792ed/src/Spago/Purs.hs#L104) seems to use `purs --version` rather than `"C:\Progra~1\nodejs\purs.cmd" --version`. Google lead me to [an issue with turtle](https://github.com/Gabriel439/Haskell-Turtle-Library/issues/256) that may be related. I will try and make some testcases with turtle to see if calling executables with a colon in their path reproduces the issue. Otherwise, I'm stumped.

**Comment by f-f** [comment]
I see, thanks for the looking into this!
Maybe we could just stop using executables with their full path on Windows since the version check seems to work?

**Comment by mjarosie** [comment]
I'm having **almost** exactly the same issue. The only difference is that `spago build` succeeds in spite of `Executable was not found in path: "purs"` error:

```
$ spago build
[error] Executable was not found in path: "purs"
[info] Installation complete.
[info] Build succeeded.
```

I'm building a demo project described in [Getting Started with PureScript](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md).

Output of `spago -V build`:

```
$ spago -V build
2020-05-10 22:55:12.082510: [debug] Running `getGlobalCacheDir`
@(src\Spago\RunEnv.hs:43:7)
2020-05-10 22:55:12.094478: [debug] Transformed config is the same as the read one, not overwriting it
@(src\Spago\Config.hs:364:14)
2020-05-10 22:55:12.140355: [debug] Ensuring that the package set is frozen
@(src\Spago\PackageSet.hs:275:3)
2020-05-10 22:55:12.171272: [error] Executable was not found in path: "purs"
@(src\Spago\Prelude.hs:128:13)
2020-05-10 22:55:12.171272: [debug] ExitFailure 1
@(src\Spago\RunEnv.hs:128:9)
2020-05-10 22:55:12.173266: [debug] Running `spago build`
@(src\Spago\Build.hs:58:3)
2020-05-10 22:55:12.173266: [debug] Getting transitive deps
@(src\Spago\Packages.hs:129:3)
2020-05-10 22:55:12.175262: [debug] Running `fetchPackages`
@(src\Spago\FetchPackage.hs:41:3)
2020-05-10 22:55:12.175262: [debug] Checking if `purs` is up to date
@(src\Spago\PackageSet.hs:183:3)
2020-05-10 22:55:12.267016: [info] Installation complete.
@(src\Spago\FetchPackage.hs:69:3)
2020-05-10 22:55:12.268013: [debug] Compiling with "C:\\Users\\macie\\AppData\\Roaming\\npm\\purs.cmd"
@(src\Spago\Purs.hs:29:3)
2020-05-10 22:55:12.268013: [debug] Running command: `C:\Users\macie\AppData\Roaming\npm\purs.cmd compile  ".spago/assert/v4.1.0/src/**/*.purs" ".spago/bifunctors/v4.0.0/src/**/*.purs" ".spago/console/v4.4.0/src/**/*.purs" ".spago/control/v4.2.0/src/**/*.purs" ".spago/distributive/v4.0.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/either/v4.1.1/src/**/*.purs" ".spago/foldable-traversable/v4.1.1/src/**/*.purs" ".spago/identity/v4.1.0/src/**/*.purs" ".spago/invariant/v4.1.0/src/**/*.purs" ".spago/lazy/v4.0.0/src/**/*.purs" ".spago/lists/v5.4.1/src/**/*.purs" ".spago/maybe/v4.0.1/src/**/*.purs" ".spago/newtype/v3.0.0/src/**/*.purs" ".spago/nonempty/v5.0.0/src/**/*.purs" ".spago/orders/v4.0.0/src/**/*.purs" ".spago/partial/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" ".spago/refs/v4.1.0/src/**/*.purs" ".spago/tailrec/v4.1.1/src/**/*.purs" ".spago/tuples/v5.1.0/src/**/*.purs" ".spago/type-equality/v3.0.0/src/**/*.purs" ".spago/unfoldable/v4.1.0/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"`
@(src\Spago\Purs.hs:121:3)
2020-05-10 22:55:12.610098: [info] Build succeeded.
@(src\Spago\Purs.hs:123:20)
```

**Comment by kelden** [comment]
I'm pretty sure that's normal. Spago first tries to find purs by looking for the command `purs` [in the function `getPurs`](https://github.com/purescript/spago/blob/0e70a23247a37181365191b06f3c73a8db5a8a8a/src/Spago/RunEnv.hs#L123). If it doesn't find it it tries again, this time searching for `purs.cmd` which it succeeds in finding for you. It looks like the error message just needs to be adjusted or suppressed. Do `run` and `repl` work as well?

Just out of curiosity, what version of npm, node (and maybe nvm) are you running? This seems to confirm my suspicion that it's my configuration that is causing the issue (probably nvm). Every test I've done with turtle in ghci succeeds in finding `purs.cmd` and running the compile command, so I still don't know what the issue is. 

@f-f I patched my local copy of spago to use `cmd = "purs" <> " compile " <> args <> " " <> paths` for compiling and it works for me, but I'm hesitant to suggest it as a solution in case it breaks Spago for other Windows users. However, @mjarosie passes the version check as well so maybe that is the way to go?

**Comment by mjarosie** [comment]
```
$ npm --version
6.14.5

$ node --version
v10.16.3

$ spago version
0.15.2

$ purs --version
0.13.6
```

I'm not using `nvm`. `run` and `repl` work without any problems.

**Comment by f-f** [comment]
Fix is up in #639, could anyone on this thread try out that branch? (it should be enough to clone this repo and do a `stack install` to get the new binary)

**Comment by mjarosie** [comment]
Unfortunately getting the same "error":

```
$ spago build
[error] Executable was not found in path: "purs"
[info] Installation complete.
[info] Build succeeded.
```

**Comment by f-f** [comment]
@mjarosie what's the result if you run `spago -V build`?

**Comment by f-f** [comment]
@mjarosie could you try the latest commit?

**Comment by mjarosie** [comment]
@f-f that fixes it! : )

```
$ spago build
[info] Installation complete.
[info] Build succeeded.
```

**Comment by f-f** [comment]
@mjarosie thank you for trying this out! I'll merge and release the fix then :)

**Comment by stkb** [comment]
This issue is caused by what I'd consider a bug in haskell/process#51 and because in this case there's a space in the path to the purs binary.

Say we build our purs command:
```
"some path with spaces\purs.exe" "args" "in" "quotes"
```
This gets passed through `Turtle.shell` to the `System.Process` module which [turns it into a commandline to cmd.exe](https://github.com/haskell/process/blob/81c3c1d898dff3733b5ce83308b0cd7eccd2a2ac/System/Process/Windows.hsc#L232):
```
cmd.exe /c "some path with spaces\purs.exe" "args" "in" "quotes"
```
The way cmd.exe is called here is incorrect. [Because of an arcane set of rules](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd#remarks), cmd removes the first and last quotes from the passed-in command, and so the command we want to run gets turned into:
```
some path with spaces\purs.exe" "args" "in" "quotes
```
Now without the leading quote, the command is broken (reason for the "Can't find C:\Program" error)

The generally-correct way to pass a command to cmd.exe is to use the extra `/s` switch, and to wrap the entire command to run in another set quotes. Then it will run fine:
```
cmd.exe /s /c ""some path with spaces\purs.exe" "args" "in" "quotes""
```

[Node.js for example does this correctly](https://github.com/nodejs/node/blob/c1ee70ec168eedc3f9d193473d141b9c03e2df88/lib/child_process.js#L490)

### Fix

So if we want to stick with finding/using the absolute path to `purs`, building the compile command like this in `Purs.compile` fixes it.
``` haskell
cmd = surroundQuote $ surroundQuote purs <> " compile " <> args <> " " <> paths
```
(I don't know how that will behave on *nix but of course we can special-case Windows)

However, I'm out of the loop here and don't know why we do that in the first place? Since we already require `purs` to be on the path, it makes sense to just call `purs` as-is (the direction #639 is going)

Moreover, if we do that, we don't need the extra code to look for a `purs.cmd` on Windows. Since we call out to a shell, just calling `purs` will work anyway.

**Comment by f-f** [comment]
@stkb thanks for looking into this! For context, I recently got a Windows 10 install, and the first thing that happened when I tried to run spago was that it errored because it wanted `purs.cmd` - which is the reason why I added this check, which fixed my issue.

I don't think we actually need to use absolute paths at all, so I'll go ahead and merge #639, which fixes this.

**Comment by Rohit-cell-art** [comment]
> Ok, so I replaced the line I mentioned and now it gives the correct quoted version, but I get the same error:
> 
> ```
> C:\Users\redacted\Documents\src\purescript\my-project>spago -V build
> �[90m2020-05-02 15:09:48.029051: �[32m[debug] �[0mRunning `getGlobalCacheDir`�[90m
> @(src\Spago\RunEnv.hs:43:7)�[0m
> �[90m2020-05-02 15:09:48.044644: �[32m[debug] �[0mTransformed config is the same as the read one, not overwriting it�[90m
> @(src\Spago\Config.hs:364:14)�[0m
> �[90m2020-05-02 15:09:48.082398: �[32m[debug] �[0mEnsuring that the package set is frozen�[90m
> @(src\Spago\PackageSet.hs:275:3)�[0m
> �[90m2020-05-02 15:09:48.113640: �[31m[error] �[0mExecutable was not found in path: "purs"�[90m
> @(src\Spago\Prelude.hs:127:13)�[0m
> �[90m2020-05-02 15:09:48.113640: �[32m[debug] �[0mExitFailure 1�[90m
> @(src\Spago\RunEnv.hs:128:9)�[0m
> �[90m2020-05-02 15:09:48.113640: �[32m[debug] �[0mRunning `spago build`�[90m
> @(src\Spago\Build.hs:58:3)�[0m
> �[90m2020-05-02 15:09:48.129293: �[32m[debug] �[0mGetting transitive deps�[90m
> @(src\Spago\Packages.hs:129:3)�[0m
> �[90m2020-05-02 15:09:48.129293: �[32m[debug] �[0mRunning `fetchPackages`�[90m
> @(src\Spago\FetchPackage.hs:41:3)�[0m
> �[90m2020-05-02 15:09:48.129293: �[32m[debug] �[0mChecking if `purs` is up to date�[90m
> @(src\Spago\PackageSet.hs:183:3)�[0m
> �[90m2020-05-02 15:09:48.198321: �[34m[info] �[0mInstallation complete.�[90m
> @(src\Spago\FetchPackage.hs:69:3)�[0m
> �[90m2020-05-02 15:09:48.198321: �[32m[debug] �[0mCompiling with "\"C:\\Program Files\\nodejs\\purs.cmd\""�[90m
> @(src\Spago\Purs.hs:29:3)�[0m
> �[90m2020-05-02 15:09:48.213962: �[32m[debug] �[0mRunning command: `"C:\Program Files\nodejs\purs.cmd" compile  ".spago/console/v4.4.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"`�[90m
> @(src\Spago\Purs.hs:121:3)�[0m
> 'C:\Program' is not recognized as an internal or external command,
> operable program or batch file.
> 2020-05-02 15:09:48.229562: [error] Failed to build.
> @(src\Spago\Prelude.hs:127:13)
> ```
> 
> Which is odd, because
> 
> 1. Actually running `"C:\Program Files\nodejs\purs.cmd" compile  ".spago/console/v4.4.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"` in my console compiles the program.
> 2. It says that the `Executable was not found in path: "purs"`, and yet `` Checking if ``purs`` is up to date `` doesn't fail.
> 
> Why does pasting `command` in my shell work but `shell command empty` fail? I thought that it may simply be an issue with my Windows environment and not spago. Node version manager adds an environment variable to my path, %NVM_SYMLINK%, which is set to C:\Program Files\nodejs. I tried changing it to C:\Progra~1\nodejs to sidestep the whitespace issue, which gets me:
> 
> ```
> C:\Users\redacted\Documents\src\purescript\my-project>spago -V build
> �[90m2020-05-02 14:16:18.070925: �[32m[debug] �[0mRunning `getGlobalCacheDir`�[90m
> @(src\Spago\RunEnv.hs:43:7)�[0m
> �[90m2020-05-02 14:16:18.086545: �[32m[debug] �[0mTransformed config is the same as the read one, not overwriting it�[90m
> @(src\Spago\Config.hs:364:14)�[0m
> �[90m2020-05-02 14:16:18.133409: �[32m[debug] �[0mEnsuring that the package set is frozen�[90m
> @(src\Spago\PackageSet.hs:275:3)�[0m
> �[90m2020-05-02 14:16:18.155540: �[31m[error] �[0mExecutable was not found in path: "purs"�[90m
> @(src\Spago\Prelude.hs:127:13)�[0m
> �[90m2020-05-02 14:16:18.155540: �[32m[debug] �[0mExitFailure 1�[90m
> @(src\Spago\RunEnv.hs:128:9)�[0m
> �[90m2020-05-02 14:16:18.155540: �[32m[debug] �[0mRunning `spago build`�[90m
> @(src\Spago\Build.hs:58:3)�[0m
> �[90m2020-05-02 14:16:18.155540: �[32m[debug] �[0mGetting transitive deps�[90m
> @(src\Spago\Packages.hs:129:3)�[0m
> �[90m2020-05-02 14:16:18.171160: �[32m[debug] �[0mRunning `fetchPackages`�[90m
> @(src\Spago\FetchPackage.hs:41:3)�[0m
> �[90m2020-05-02 14:16:18.171160: �[32m[debug] �[0mChecking if `purs` is up to date�[90m
> @(src\Spago\PackageSet.hs:183:3)�[0m
> �[90m2020-05-02 14:16:18.240151: �[34m[info] �[0mInstallation complete.�[90m
> @(src\Spago\FetchPackage.hs:69:3)�[0m
> �[90m2020-05-02 14:16:18.240151: �[32m[debug] �[0mCompiling with "\"C:\\Progra~1\\nodejs\\purs.cmd\""�[90m
> @(src\Spago\Purs.hs:29:3)�[0m
> �[90m2020-05-02 14:16:18.240151: �[32m[debug] �[0mRunning command: `"C:\Progra~1\nodejs\purs.cmd" compile  ".spago/console/v4.4.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"`�[90m
> @(src\Spago\Purs.hs:121:3)�[0m
> The system cannot find the path specified.
> 2020-05-02 14:16:18.271399: [error] Failed to build.
> @(src\Spago\Prelude.hs:127:13)
> ```
> 
> Weird.
> 
> Again, copying and pasting the string spago prints as it's running command works fine. [Looking deeper, the version check](https://github.com/purescript/spago/blob/5beef6723a0756d3661e87746d6d08847cf792ed/src/Spago/Purs.hs#L104) seems to use `purs --version` rather than `"C:\Progra~1\nodejs\purs.cmd" --version`. Google lead me to [an issue with turtle](https://github.com/Gabriel439/Haskell-Turtle-Library/issues/256) that may be related. I will try and make some testcases with turtle to see if calling executables with a colon in their path reproduces the issue. Otherwise, I'm stumped.



How did you solve this problem?
Even I am facing same problem.
Please Help.
