### ISSUE TITLE
Depend on zephyr for even smaller bundles

### ISSUE THREAD

**Issue by f-f** [purescript/spago#640]
There's [some talk lately](https://discourse.purescript.org/t/what-is-the-state-of-the-art-minification-compression/1369) about small bundles, and [zephyr](https://github.com/coot/zephyr) comes up quite often. We could depend on it (as a library) and add a flag to enable it when calling `spago bundle-*`

**Comment by hdgarrood** [comment]
You'll end up bringing in the whole compiler that way: https://github.com/coot/zephyr/blob/802d968a1a79620560e88a1607a4f8b7de863879/zephyr.cabal#L111 Not sure if that's a dealbreaker.

**Comment by f-f** [comment]
@hdgarrood it kind of is, as then we'd be depending on a specific version of `purs` :slightly_frowning_face: 

Any thoughts on including zephyr-like functionality in the compiler instead?

**Comment by hdgarrood** [comment]
I definitely think it's worthy of consideration. I could potentially see `purs bundle` being replaced with a more zephyr-like version at some point in the future. The issue to follow is https://github.com/purescript/purescript/issues/2970

**Comment by f-f** [comment]
Wonderful, thanks for the pointer. You can note a +1 from me on that, and I'll close this issue :slightly_smiling_face:
