### ISSUE TITLE
spago build didn't update corefn in output directory

### ISSUE THREAD

**Issue by thautwarm** [purescript/spago#643]
I change my code in Main module and run`spago build`, nothing happened in my project directory, and hence alternative backends failed in generating code correctly.

Don't know why JS backend works even when corefn files didn't updated.

Any hints for alternative backends?

**Comment by thautwarm** [comment]
I have to delete `output` directory and rebuild to work it.

**Comment by f-f** [comment]
@thautwarm I'm not sure of what's happening and what's your setup - could you put together a minimal reproduction for this?

**Comment by thautwarm** [comment]
@f-f Sorry, I just cannot reproduce this and everything works quite well..
I'm quite sure with exactly the same codebase, no modification, on this afternoon, this issue had happened.

**Comment by opyapeus** [comment]
I have the same problem.
I found that the problem does not occur when I disable PureScript IDE in VSCode.
But I don’t know why it happens.

Reproduction

`spago init`
`spago build --purs-args "-g corefn" `
modify "🍝" to "something" in `src/Main.purs`
check `output/Main/corefn.json`

My envs
- macos 10.15.3
- spago 0.15.2
- purescript 0.13.8
- vscode 1.46.1
- purescript ide 0.20.15

**Comment by thautwarm** [comment]
It seems that I cannot confirm this, and I remember I didn't use such a (relatively) complex command.

I tested with following envs
- windows 10 (don't think this significant so ignore details)
- spago (both 0.15.2/0.15.3 tested with same result)
- purescript 0.13.8

spago 0.15.3:

```shell
bash> spago build --purs-args "-g corefn"
[info] Installation complete.
Invalid option `--codegen'

Usage: purs.bin COMMAND
  The PureScript compiler and tools
[error] Failed to build.
```
spago 0.15.2:
```
bash> spago build --purs-args "-g corefn"
[error] Executable was not found in path: "purs"
Invalid option `--codegen'

Usage: purs.bin COMMAND
  The PureScript compiler and tools
[error] Failed to build.
```

All those commands cannot execute correctly, so no new corefn generated is reasonable.

I think the actual error occurred in macos is, the error message didn't show up correctly.

**Comment by thautwarm** [comment]
PLUS:
After removing "backend" option in `spago.dhall`, `spago build --purs-args "-g corefn"` executed correctly, but python backend can generate the latest `Main` which is strictly according to the disk file output/Main/corefn .

```shell
spago build
pspy
pspy --run
# show the latest result
```

**Comment by thautwarm** [comment]
Result: cannot reproduce..
It seems that something cannot reproduce happened @opyapeus , just like what happened to me..
Everything fixed for me after I go out for a short walk.

**Comment by opyapeus** [comment]
@thautwarm Thank you!
Hmm... I will comment if there is any progress.
