### ISSUE TITLE
'spago build' not working on Windows

### ISSUE THREAD

**Issue by ursi** [purescript/spago#644]
I'm trying to get started with purescript and I'm following the guide
https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md

I ran `npm i -g purescript` and confirmed `purs` does work in my terminal

I ran `npm i -g spago` and ran `spago init` with no issues.

Then I try to run `spago build` and I get this
```
[error] Executable was not found in path: "purs"
[info] Installing 4 dependencies.
[info] Searching for packages cache metadata..
[info] Unable to find packages cache metadata, downloading from GitHub..
[info] Installing and globally caching "psci-support"
[info] Installing and globally caching "console"
[info] Installing and globally caching "effect"
[info] Installing and globally caching "prelude"
[info] Installation complete.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
[error] Failed to build.
```

And on subsequent runs
```
[error] Executable was not found in path: "purs"
[info] Installation complete.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
[error] Failed to build.
```

It seems there's an issue with parsing the path as it's trying to execute `C:\Program`.

**Comment by f-f** [comment]
@ursi thanks for reporting! This was actually fixed in #639, but I forgot to cut a release then - sorry for that. I'll cut one later today :slightly_smiling_face:
