### ISSUE TITLE
Inconsistent relative path rules for `packages` and `sources` in `spago.dhall`

### ISSUE THREAD

**Issue by milesfrain** [purescript/spago#648]
* `packages` uses a path relative to `spago.dhall`
* `sources` uses a path relative to where `spago` is run.

I think it makes most sense to use paths relative to the file, which requires changes to how `sources` is handled.

We're encountering this issue with the cookbook ([PR](https://github.com/JordanMartinez/purescript-cookbook/pull/35)).

The directory structure is like this:
```
.    
├── makefile    
├── packages.dhall    
└── recipes    
    ├── HelloWorld    
    │   ├── README.md    
    │   ├── spago.dhall    
    │   └── src    
    │       └── Main.purs    
    └── RoutingPushHalogen    
        ├── README.md         
        ├── spago.dhall       
        └── src    
            ├── Example.purs    
            ├── Main.purs    
            └── Routing.purs 
```

Ideally we'd be able to reuse these lines for the `spago.dhall` in each recipe:
```dhall
, packages = ../../packages.dhall    
, sources = [ "src/**/*.purs" ]
```
But instead we need to customize `sources` for each:
```dhall
, sources = [ "recipes/HelloWorld/src/**/*.purs" ] 
```
```dhall
, sources = [ "recipes/RoutingPushHalogen/src/**/*.purs" ] 
```

Build commands are:
```
spago build --config recipes/HelloWorld/spago.dhall
spago build --config recipes/RoutingPushHalogen/spago.dhall
```

**Comment by f-f** [comment]
The new Spago does not have `sources` anymore
