### ISSUE TITLE
Misleading error message with non-existent alternative dhall

### ISSUE THREAD

**Issue by hedefalk** [purescript/spago#650]
I saw some other issues around the spago.dhall but I couldn't see this particular thing:

```fish
✗ npx spago -x nonexisting.dhall test --watch
[error] Failed to read the config. Error was:
[error] There's no "spago.dhall" in your current location.

If you already have a spago project you might be in the wrong subdirectory,
otherwise you might want to run `spago init` to initialize a new project.
```

Just a bit misleading there…

**Comment by f-f** [comment]
Thanks for reporting. Do you think we should just tweak the error message replacing `spago.dhall` with the provided file?

**Comment by hedefalk** [comment]
> Do you think we should just tweak the error message replacing `spago.dhall` with the provided file?

Yup, that makes sense to me.

**Comment by autophagy** [comment]
@f-f Hi Fabrizio! Was just looking through Spago's issues list for good first issues and came across this - but I believe it was fixed with https://github.com/purescript/spago/pull/747? Just thought you'd like a heads up, in case you wanted to close it! :sparkles:

**Comment by f-f** [comment]
@autophagy yes you're right, thank you! I'll close this.
