### ISSUE TITLE
bundle-module and bundle-app have conflicting short names for --to and --then

### ISSUE THREAD

**Issue by mhmdanas** [purescript/spago#651]
Somehow, they work fine even when they're together:
```console
mhmdanas@Mohammeds-MacBook-Pro  % spago bundle-module -t index.js
[info] Installation complete.
[info] Build succeeded.
[info] Bundling first...
[info] Bundle succeeded and output file to index.js
[info] Make module succeeded and output file to index.js
mhmdanas@Mohammeds-MacBook-Pro  % spago bundle-module -t index.js -t 'echo foo'
[info] Installation complete.
[info] Build succeeded.
[info] Bundling first...
[info] Bundle succeeded and output file to index.js
[info] Make module succeeded and output file to index.js
foo
mhmdanas@Mohammeds-MacBook-Pro  % spago bundle-module -t 'echo foo'
[info] Installation complete.
[info] Build succeeded.
[info] Bundling first...
[info] Bundle succeeded and output file to echo foo
[info] Make module succeeded and output file to echo foo
```
The same happens with `bundle-app`.

In case this is actually the intended behavior, I believe it needs to be clarified somewhere, like in the `spago bundle-module -h` and `spago bundle-app -h` outputs.

**Comment by f-f** [comment]
Thanks for reporting!

I think we could have a couple of ways to address this:
- change either `then` or `target`'s shorthand to be different (I suspect `then` is going to be less breaking
- change one of them to not have the shorthand at all

Does anyone have any thoughts on this?

**Comment by mhmdanas** [comment]
I vote for the second option. `--then` seems to be shared across at least several commands, including `bundle-module`, `bundle-app`, and `build`, so if it has a shorthand, we'll have to be careful not to make any conflicts across all of these commands. So I think removing the shorthand for `--then` is the best option.

**Comment by mhmdanas** [comment]
I'd like to try to fix this issue, but which solution should we go with?

**Comment by f-f** [comment]
@mhmdanas let's go with removing the shorthand for `--then` (and `before`, and `else`, for consistency)

Some implementation pointer: all the CLI stuff is taken care of in the [`Spago.CLI`](https://github.com/purescript/spago/blob/master/src/Spago/CLI.hs) module, here:
https://github.com/purescript/spago/blob/7ac6b53e48ccfd52003be9a72bb83b4c34af1b2d/src/Spago/CLI.hs#L121-L123

The problem with the code above is that it's using the [`Turtle.Options`](http://hackage.haskell.org/package/turtle-1.5.19/docs/Turtle-Options.html) module, which to make things easy it always requires a shorthand - so to remove it we'd need to just use `optparse-applicative` for these flags. It's nothing new as we already use it for some commands below, and it's anyways what Turtle uses under the hood. Let me know if you'd like more details on this :slightly_smiling_face:
