### ISSUE TITLE
Spago fails behind aggressive proxy / firewall

### ISSUE THREAD

**Issue by JesterXL** [purescript/spago#652]
Running `spago init` fails on my work machine.
```bash
InternalException (HandshakeFailed (Error_Protocol ("certificate rejected: [InvalidSignature SignatureInvalid]",True,CertificateUnknown)))
```

I have the same problem with Elm ( https://github.com/elm/core/issues/1036 ) and with Haskell's `stack`. I believe my corporate network is either re-writing their own certs, or just flat out blocking some http/https calls directly to github. For Python and Node, they require us to use Artifactory instead.

... however, I _do_ have public Github access, so I'm unclear why some things work (I don't think I can use Python's `pip install` directly from Github, but I did write [a hack](https://github.com/JesterXL/elm-library-installer) using Node to download Elm library ZIP's directly from Github and this worked... ).

Is this an Artifactory thing or an HTTPS Haskell thing? Any ideas on how to work around this?

**Comment by hdgarrood** [comment]
My guess would be that your internal network is MITMing you by intercepting any attempted HTTPS connections and presenting you with their own self-signed certificates, and has also configured your browser to trust these certificates, but that configuration isn't being picked up by other programs. I think this would be a little easier to diagnose if you could show us the exact URL spago was trying to connect to and the certificate you were presented with.

**Comment by f-f** [comment]
Yeah Spago does access the network when doing `init`, I think exactly once, when trying to upgrade the package set to the latest release:
https://github.com/purescript/spago/blob/da6d91c19b23f06f3ede793f78599a6589c9e7cd/src/Spago/Packages.hs#L47-L48

I think we should probably just address this with a global `--offline` flag, as reported in #575?

**Comment by hdgarrood** [comment]
I'm not sure if an `--offline` flag would help in this case, because at some point (if not during `spago init`, then during `spago build`), presumably Spago is going to have to grab some stuff from GitHub?

**Comment by f-f** [comment]
@hdgarrood for how I see the `--offline` flag, it would halt execution when it would absolutely need to fetch packages.
The main use case for it is Nix usage, and the assumption there is that people would feed Spago already downloaded packages (e.g. with Spago2Nix), which could also be the solution here (or an equivalent script that fetches things off github)

**Comment by f-f** [comment]
It looks like we think that the `--offline` flag is the way to go for this, so I'll close this issue in favor of #575. Please reopen if I misunderstood and/or you feel we're not addressing the original usecase and/or we should do something different here
