### ISSUE TITLE
Unable to build Spago derivation from nixpkgs

### ISSUE THREAD

**Issue by ssbothwell** [purescript/spago#656]
I'm using `nix` in multi-user mode on MacOS Catalina with the `20.03` channel. Installing spago via `nix-env -i spago` yields this GHC error:

```
src/Spago/Templates.hs:32:3: error:
    • Exception when trying to run compile-time code:
        templates/docs-search-app.js: openBinaryFile: permission denied (Permission denied)
      Code: embedURLWithFallback
              ("https://github.com/spacchetti/purescript-docs-search/releases/download/"
                 <> T.unpack docsSearchVersion <> "/docs-search-app.js")
              "templates/docs-search-app.js"
    • In the untyped splice:
        $(embedURLWithFallback
            ("https://github.com/spacchetti/purescript-docs-search/releases/download/"
               <> T.unpack docsSearchVersion
               <> "/docs-search-app.js")
            "templates/docs-search-app.js")
   |
32 |   $(embedURLWithFallback
```

**Comment by f-f** [comment]
cc @cdepillabout: any idea why this might be happening?

**Comment by cdepillabout** [comment]
@ssbothwell I'm not exactly sure why this would be happening, but there is some nixpkgs-specific logic for pulling down data from `purescript-docs-search` in the `spago` derivation in nixpkgs.

My first suggestion would be to just try building `spago` in the nixpkgs-unstable channel (or just on the nixpkgs `master` branch).

If this also doesn't work, could you report an issue in nixpkgs (and cc me)?  Also, if you could play around with the derivation to figure out exactly why it is failing, it would be very helpful.

**Comment by f-f** [comment]
It looks like this issue really belongs in `nixpkgs` rather than here, so I'll close this - let's reopen it if we figure out that there's something to be done on our end :slightly_smiling_face:
