### ISSUE TITLE
Use new Dhall syntax for overrides

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#659]
> I just realized we have a nicer syntax for that snippet in the newer Dhall/Spago versions, now you should be able to write that as:

```dhall
upstream
  with argonaut.version = "v7.0.0"
  with other-lib.version = "v1.2.3"
```

**Comment by f-f** [comment]
Yep, and the README should be ported to the new syntax too

**Comment by JordanMartinez** [comment]
With the update, would `package.dhall` then look like this?
```dhall
let upstream = --
let overrides = upstream
  with argonaut.version = "v7.0.0"
  with other-lib.version = "v1.2.3"
let additions = --
in overrides \\ additions
```
Also, what would one do if they were also overriding the `repo` of a package at the same time as the `version`?

**Comment by f-f** [comment]
I would get rid of `overrides` and `additions` too: I find them confusing and with this syntax they don't really make sense anymore, since we get rid of the merge operator (`//`) entirely.

I'd say the `packages.dhall` could look like this:
```dhall
let upstream =
      https://github.com/purescript/package-sets/releases/download/psc-0.13.8-20200615/packages.dhall sha256:5d0cfad9408c84db0a3fdcea2d708f9ed8f64297e164dc57a7cf6328706df93a

in  upstream
    with argonaut.version = "v7.0.0"
    with other-lib.version = "v1.2.3"
    with other-lib.repo = "some new repo" -- here we override the repo too
    with new-lib = -- and this is an addition to the set
      { version = "v.0.1.0"
      , repo = "..."
      , dependencies = [ ... ]
      }
```

**Comment by JordanMartinez** [comment]
```dhall
in upstream =
  with other-lib.version = "v1.2.3"
  with other-lib.repo = "some new repo" -- here we override the repo too
```
Could the above be reworked to
```dhall
in upstream =
  with other-lib
    with version = "v1.2.3"
    with repo = "some new repo"
```

**Comment by f-f** [comment]
@JordanMartinez if you try that in a `dhall` repl (or [on the website](https://dhall-lang.org)) you'll see that it doesn't compile. The closest we can get with that kind of syntax is:

```dhall
in upstream =
  with other-lib = (upstream.other-lib
    with version = "v1.2.3"
    with repo = "some new repo")
```

..which I'm not a fan of, especially because it requires parentheses
