### ISSUE TITLE
`packages.dhall` doesn't respect local package's sources

### ISSUE THREAD

**Issue by ptwales** [purescript/spago#662]
From the Mono repo example, say if I define a local dependency like so 

```dhall
let overrides =
     { liba = ./liba/spago.dhall as Location
     }
```
in `packages.dhall`. But `liba/spago.dhall` defines it's sources with something like

```dhall
, sources = 
    [ "liba/src/main/purescript/**/*.purs" ]
```
_Say there is server code in `liba/src/main/java/`._ 

I can compile code in `liba` with 

```bash
spago -x liba/spago.dhall build
```
 but I when I compile `app1` which depends on `liba` then I also compile source code in `liba/src/test/purescript/`.  This is because spago is using `liba/src/**/*.purs` as the sources.  You can confirm this behaviour with 

```bash
spago -x app1/spago.dhall sources
```
which will always output `./liba/src/**/*.purs` regardless of what `liba/spago.dhall` says it's sources are.

**Comment by ptwales** [comment]
Issue is in [`Packages.hs#L87`](https://github.com/purescript/spago/blob/master/src/Spago/Packages.hs#L87)

**Comment by ptwales** [comment]
I think JordanMartinez meant #663

**Comment by JordanMartinez** [comment]
Ah, yeah, sorry about that.

**Comment by f-f** [comment]
Sorry it's a bit of a hectic time and I did not manage to look at this yet, I'll get to it shortly

**Comment by f-f** [comment]
The new Spago does not have `sources` anymore, closing
