### ISSUE TITLE
Upgrade to GHC 8.8 and Dhall 1.35

### ISSUE THREAD

**Issue by f-f** [purescript/spago#685]
See https://github.com/dhall-lang/dhall-haskell/issues/2031

**Comment by f-f** [comment]
I gave this a shot, and apart from the fact that this will require us to rework the CI (possibly porting it to GitHub Actions) it looks like `dhall-1.33` carries a change that it's pretty breaking for us: language keywords cannot be used anymore as record keys, see https://github.com/dhall-lang/dhall-haskell/pull/1801.

In our case this means that a new version of Spago using the latest Dhall (`1.35` at the time of writing) will not be able to _parse_ package sets that contain the package `assert` (because that's a keyword).
I already patched `package-sets` so that all the new sets correctly quote the `assert` package: https://github.com/purescript/package-sets/pull/692

Of all the possible solutions to "we want to use the new Dhall but also parse old package sets", there is only one that is completely transparent to the users: write a script that goes through all the releases of `package-sets`, downloads [the package-set file that Spago imports](https://github.com/purescript/package-sets/releases/download/psc-0.13.8-20200911/packages.dhall), patches it in the same way as my PR above, and reuploads it in the release.

This is transparent to the users because the hash (which we use to ensure that the imported set does not change) is unaffected, as the Dhall binary representation for "record key" and "quoted record key" is the same.

**Comment by hdgarrood** [comment]
Patching old releases like that sounds okay to me. Why would it require us to rework the CI, just out of interest?

**Comment by f-f** [comment]
@hdgarrood the Travis build for Linux uses a docker image to have a decently fast cache. To upgrade the GHC version I'd have to upgrade it in there and rebuild the images, etc. I don't really feel like it's worth spending any more time on fixing Travis at this point, when GitHub Actions is faster, better integrated, etc.

**Comment by f-f** [comment]
Heads-up @nwolverson: we'll need to apply the script I described above also to the releases of `purerl/package-sets` (tests are failing on my local Spago branch with the new Dhall because it cannot parse the purerl package set that we have in a test)

**Comment by f-f** [comment]
Also I believe this can be closed, as it was fixed in #695

**Comment by nwolverson** [comment]
With minimal tweaking ran the script against recent purerl package sets - thanks @JordanMartinez for the work in there, @f-f for the coordination

**Comment by JordanMartinez** [comment]
Glad to here it went smoothly!
