### ISSUE TITLE
Installation failed on Ubuntu 20.04 in WSL on Windows 10

### ISSUE THREAD

**Issue by michalwa** [purescript/spago#689]
Steps to reproduce:
```
$ spago init
[info] Initializing a sample project or migrating an existing one..
[info] Upgrading the package set version to "psc-0.13.8-20200922"
[info] Package-set upgraded to latest tag "psc-0.13.8-20200922"
Fetching the new one and generating hashes.. (this might take some time)
[info] Generating new hashes for the package set file so it will be cached.. (this might take some time)
[info] Set up a local Spago project.
[info] Try running `spago build`
$ spago build
[info] Installing 4 dependencies.
[info] Searching for packages cache metadata..
[info] Recent packages cache metadata found, using it..
[info] Copying from global cache: "psci-support"
[info] Copying from global cache: "console"
[error] Installation failed
[error] Error:
[error] .spago/__download-console-v4.4.0-37568c9a74076dea/download: rename: permission denied (Permission denied)
```
I have `purs` and `spago` installed globally.
No clue what this is about, I'm just starting out with PureScript.

### Edit
The problem occurs when the project directory is opened remotely in Visual Studio Code. Not sure if this issue should still be open in this repo, or whether this should be reported to the VSCode team.

**Comment by f-f** [comment]
@michalwa thanks for reporting. Does it work if you run `spago --global-cache=skip build`?

**Comment by michalwa** [comment]
@f-f Nope, still getting the same error.

**Comment by f-f** [comment]
I see. Could you post the output of `spago -V build`?

**Comment by michalwa** [comment]
Now I seem not to able to ignore the cached packages?
```
$ spago build --very-verbose --global-cache=skip

...
2020-09-24 16:44:24.721344: [info] Copying from global cache: "console"
@(src/Spago/FetchPackage.hs:116:9)
2020-09-24 16:44:24.722442: [info] Copying from global cache: "psci-support"
@(src/Spago/FetchPackage.hs:116:9)
2020-09-24 16:44:24.724452: [info] Copying from global cache: "effect"
@(src/Spago/FetchPackage.hs:116:9)
2020-09-24 16:44:24.728754: [info] Copying from global cache: "prelude"
@(src/Spago/FetchPackage.hs:116:9)
...
```

**Comment by michalwa** [comment]
I can't really explain it, but when I ran the build with `--very-verbose`, it fetched all the stuff and succeeded. Something else must have changed since the error?

**Comment by michalwa** [comment]
Alright, I was able to reproduce the error again now by attempting to install a package:
```

**Comment by f-f** [comment]
All that flag does is to enable some additional logging, so Spago is really doing the same work as before. Maybe it's something else you tweaked in the meantime?

**Comment by michalwa** [comment]
I'm not sure how to properly check my WSL version. Following [this guide](https://askubuntu.com/a/1177730), step A gave me the following output:
```
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         1
```

**Comment by michalwa** [comment]
OK, I figured it out. Turns out spago can't rename some files while the directory is open remotely in VS Code.

**Comment by f-f** [comment]
I see. Probably we cannot do much about this on the Spago side then?

**Comment by michalwa** [comment]
I guess so. Thanks for the interest.

**Comment by f-f** [comment]
You're welcome :slightly_smiling_face:
