### ISSUE TITLE
backendAction does not send outputPath

### ISSUE THREAD

**Issue by knight9999** [purescript/spago#690]
In `runBackend` function in `Spago/Build.hs`, the `postBuild` is defined as
```
  let postBuild = maybe (nodeAction $ Path.getOutputPath buildOpts) backendAction maybeBackend
```

Here
the default `nodeAction` receives`Path.getOutputPath buildOpts` and uses it to search `purs` files location.
This is good.

But for the alternate `backendAction`,  following parameters are used.
```
let args :: [Text] = ["--run", unModuleName moduleName <> ".main"] <> fmap unPursArg extraArgs
```
in which no outputPath information is included.

As a result, alternate backend,  `psgo` for example, can not  receive outputPath.

Actually, the outputPath in `psgo` is hard-coded as

```
modPrefix = modLabel <> "/output"
```
( https://github.com/andyarvanitis/purescript-native/blob/f7e8d1c29c20659035d5079de306bb24a836b87f/src/CodeGen/IL/Printer.hs#L510 )

I think it is better to send outputPath to alternate backend command.

For the case of `psgo`, the current backend commands fired by Spago are

```
$ psgo --run Main.main
```
for run (`spago run` or `spago run -o ./output2`)

```
$ psgo --run Test.Main.main
```
for test (`spago test` or `spago test -o ./output2`)

I think following backend commands are better, for example.

```
$ psgo --run=Main.main
```
for run (`spago run`)
```

$ psgo --run=Test.Main.main
```
for test (`spago test`)

```
$ psgo --run=Main.main --output=./output2
```
for run (`spago run -o ./output2`)

```
$ psgo --run=Test.Main.main --output=/output2
```
for test (`spago test -o ./output2`)

Then we can improve `psgo` to support outputPath instead of using hard coded one.

**Comment by knight9999** [comment]
This is strongly related the alternate backend feature and may bring breaking change.
Therefore I close this issue.

**Comment by nwolverson** [comment]
Not sure why you closed this, seems like a perfectly valid point - I think the discussion issue around alt backends discussed output path?

Obvious path to the change would be first to implement it (optionally) in those backends then start passing it from spago
