### ISSUE TITLE
Automatically namespace packages

### ISSUE THREAD

**Issue by ursi** [purescript/spago#694]
This is an idea to improve the following issues without any changes to the compiler
- the global module namespace
- reliance on transitive dependencies, causing the removal of dependencies to be a breaking change*

What if, when spago installs packages, all dependencies that are not directly included in the `spago.dhall` get prefixed with a module-ified version of their package name. This would make it so the only modules that need to be uniquely named are the ones you're directly depending on. This would also allow for an easy way to get out of that problem, but allowing something in the configuration to explicitly specify that you want to include a module in a namespaced way.

Regarding dependency removal being a breaking change. I guess this is kind of of gray area. I suspect no one would want to depend on transitive dependencies if it meant uglier imports, but it seems that some people don't even look at their imports and have the tooling do everything, so perhaps this really doesn't change anything. But maybe it could be enforced by convention.

As far as I can tell, this would just require some alteration in the presumably easy to parse imports and exports section of dependencies and seems feasible.

**Comment by maxdeviant** [comment]
This feels overly complex, and more like a hack than a well-designed language feature. The whole idea of having different behavior for direct vs transitive dependencies just feels gross.

Also, it sounds like Spago would be performing source manipulations of packages in order to prefix the auto-generated module name on transitive dependencies? This would preclude any sort of caching mechanism for depending on pre-built packages (https://github.com/purescript/purescript/issues/2477).

Additionally, this would require changes to code when switching from a transitive dependency to a direct dependency, as you would have to remove the auto-generated module name.

**Comment by maxdeviant** [comment]
The proposed solution also wouldn't fix the issue of module name collisions in packages that you directly depend on. So while it would be a step towards alleviating problems arising from conflicting module names, it's not a holistic solution.

**Comment by ursi** [comment]
> The whole idea of having different behavior for direct vs transitive dependencies just feels gross
Interesting. In my head they have a clear distinction, so it doesn't feel weird to me to treat them differently. Guess that's just personal preference.

> This would preclude any sort of caching mechanism for depending on pre-built packages
I must admit I'm not very familiar with the caching side of things

**Comment by maxdeviant** [comment]
Personally, I wouldn't want to be able to import transitive dependencies at all. This is something you can do in JavaScript, and it's a big footgun. If you accidentally start importing/using a transitive dependency and then it gets dropped by another package, your code would break.

You should have to list every package that you depend on. Others [feel similarly](https://github.com/purescript/purescript/issues/3493#issuecomment-449386206) about this:

> One thing I’d really like to do is to make it so that you can’t import transitive dependencies directly without declaring that you’re using them; then we don’t need to consider dropping a dependency as a breaking change.

**Comment by ursi** [comment]
> Personally, I wouldn't want to be able to import transitive dependencies at all

I totally agree with this, but as far as I understand, there's no way to get around that with the current compiler since it just lumps everything together and makes it available to you. I feel like this proposal at least makes it a little more explicit.

**Comment by maxdeviant** [comment]
> there's no way to get around that with the current compiler

That's why it's been suggested to change this as part of making the compiler package aware.

I would suggest reading through https://github.com/purescript/purescript/issues/3493 and https://github.com/purescript/purescript/issues/2437, as they are both closely related and (I think) would solve all of the concerns you've raised about module name collisions.

**Comment by ursi** [comment]
I am aware of those issues. It just didn't seem to me like any consensus had be reached, so I figured I'd throw out another idea in the meantime.

**Comment by f-f** [comment]
A couple of thoughts:
- we can easily forbid imports of transitive dependencies (that have not been declared in the current project), this is tracked in #598. It's not a big deal to implement, it's just that no one has picked it up so far
- editing source files is definitely not something we'd like to do - Spago is supposed to help you build things and get out of the way; we do our best to avoid "patching things" before calling the compiler, especially if we are already looking for ways to fix this in the compiler itself. Probably something like #599 will be the furthest we go on this

**Comment by f-f** [comment]
It looks like all issues have been addressed here, so I'll close
