### ISSUE TITLE
Is there a way to run an arbitrary test script with `spago test`?

### ISSUE THREAD

**Issue by kindaro** [purescript/spago#696]
I have a Spago project with tests in `test/Main.purs`. As I understand, this is the default location Spago looks for tests in when run as `spago test`.

I want to add a test script _X_ written in Haskell that should be executed with a command of form `cabal run X`, using the [Cabal script] feature. Moreover, after _X_ is run, another PureScript check _Y_ should be built and run in the usual way. I would like these checks to run on `spago test`.

Is it possible to accomplish this directly with Spago, or must I wire the logic into `test/Main.purs`? Or can I use a simple shell script? Is there a _«right»_ way of doing this?

[Cabal script]: https://github.com/tomjaguarpaw/tilapia/issues/26

**Comment by f-f** [comment]
There's no recommended way to do this, personally I'd just use `make` or a shell script to orchestrate this. But there are many other ways, such as building the logic in the `test/Main.purs`, or adding this in your `package.json` so that you can call `npm test`

**Comment by kindaro** [comment]
Thank you.

**Comment by f-f** [comment]
You're welcome :slightly_smiling_face:
