### ISSUE TITLE
Invalid option `--tag'

### ISSUE THREAD

**Issue by siddhant-curious** [purescript/spago#697]
The documentation says "Fortunately, you can specify which package set to use via the --tag argument. " 

However running 

`spago init --tag "psc-0.12.5-20190525"`

results in 

`Invalid option `--tag'`

Version: `0.16.0`

**Comment by f-f** [comment]
Sorry for this, I thought this was already published but it was not - I just cut a new version, which should work as you expect: https://github.com/purescript/spago/releases/tag/0.17.0
