### ISSUE TITLE
`spago docs` doesn't update docs

### ISSUE THREAD

**Issue by ursi** [purescript/spago#699]
if I run `spago docs` and then make a small change - say I update the documentation or export a new function, then run `spago docs` again, nothing changes. Whenever I'm editing my docs I always have to use
```
rm output/Module/docs.json && spago docs
```
It appears that if there's already a `docs.json`, the docs don't get regenerated sometimes. (I would say all the time but I *think* I've had it work before after having not done it in a while).

**Comment by hdgarrood** [comment]
I think this is a compiler bug, see https://github.com/purescript/purescript/issues/3911

**Comment by ursi** [comment]
oh, I didn't realize that was a compiler feature.
