### ISSUE TITLE
add --depth 1 on git clone

### ISSUE THREAD

**Issue by srghma** [purescript/spago#701]
for faster cloning of big repos

**Comment by f-f** [comment]
This would work only if we'd need to use the latest commit right?

**Comment by srghma** [comment]
> This would work only if we'd need to use the latest commit right?

dont really understand

nix `builtins.fetchGit` creates cache dir with a `.git` dir content and then creates tarball with `git archive` and then extracts that tarball

```
forkuri=https://github.com/purescript/purescript-lazy
forkname=$(basename $forkuri)
forkrev=master
forkdir="$HOME/projects/$forkname"
forkcachedir="$HOME/projects/$forkname-cache"
# forkrev="v3.0.0"
# forkrev="bfef53b20d4e3450c8bba83a69ddfe5a14c74c9f"
git init --bare $forkcachedir
git -C $forkcachedir fetch --depth=1 --quiet --force -- $forkuri $forkrev

ls -al $forkcachedir
total 48
drwxr-xr-x  7 srghma users 4096 Nov 24 18:38 .
drwxr-xr-x 89 srghma users 4096 Nov 24 18:38 ..
drwxr-xr-x  2 srghma users 4096 Nov 24 18:38 branches
-rw-r--r--  1 srghma users   66 Nov 24 18:38 config
-rw-r--r--  1 srghma users   73 Nov 24 18:38 description
-rw-r--r--  1 srghma users  105 Nov 24 18:38 FETCH_HEAD
-rw-r--r--  1 srghma users   23 Nov 24 18:38 HEAD
drwxr-xr-x  2 srghma users 4096 Nov 24 18:38 hooks
drwxr-xr-x  2 srghma users 4096 Nov 24 18:38 info
drwxr-xr-x 17 srghma users 4096 Nov 24 18:38 objects
drwxr-xr-x  4 srghma users 4096 Nov 24 18:38 refs
-rw-r--r--  1 srghma users   41 Nov 24 18:38 shallow

git -C $forkdir argive $forkrev > /tmp/asdf.tar
tar extract /tmp/asdf.tar $forkdir
```

**Comment by f-f** [comment]
Sorry, I don't really understand what you mean, could you detail?

**Comment by f-f** [comment]
I'll close this because we cannot really clone with `--depth 1`: when we fetch git repos we might have to checkout a branch, a tag or a commit. Using `--depth 1` works when checking out a branch or a tag, but not when checking out commits, for which we have to have the whole git history available.

**Comment by klntsky** [comment]
Would it be possible to use it for the cases when we know that the revision is a branch or a tag?

**Comment by f-f** [comment]
@klntsky how would we know without cloning the repo?

**Comment by L-as** [comment]
FWIW `--depth 1` is a hack and should *never* be used. However, there is the much better alternative now `--filter=tree:0` or `--filter=blob:null`. The former doesn't fetch unused directories (trees) and files (blobs), the latter still downloads all directories.
They don't prevent switching branch, commit, etc.

Theory-wise, it works by simply not fetching the parts of the Merkle tree that aren't used.

**Comment by f-f** [comment]
@L-as thanks for the suggestion! How would one use `--filter` to clone a specific branch or tag?

**Comment by L-as** [comment]
with CLI it's an option you pass to `git clone`, after that all fetches are partial.
