### ISSUE TITLE
Spago tries to create a global cache when `-c skip` is used

### ISSUE THREAD

**Issue by ursi** [purescript/spago#704]
Spago will still try to create a global cache when `-c skip`/`--global-cache skip` is used. This tripped me up when trying to use spago to build something with nix, as `HOME` is set to `/homeless-shelter` (which doesn't exist) and spago tries to create it (which it doesn't have permission to do).

**Comment by ursi** [comment]
Okay according to the README it looks like you're supposed to use this flag with an `=`. Using `--global-cache=skip` I get the same behaviour. Using `-c=skip` I get the help text.

**Comment by f-f** [comment]
Hi @ursi!

I have a few points about this:
- you can use long flags with both `=` or spaces, i.e. both `--global-cache skip` and `--global-cache=skip` are valid
- what Nix is doing here doesn't seem nice, as I feel it makes sense that the `HOME` directory for the user exists and it's writable. In any case, you can always change the location of the cache by setting the `XDG_CACHE_HOME` envvar. This is how we get its location:
https://github.com/purescript/spago/blob/6258ac601480e776c215c989cc5faae46d5ca9f7/src/Spago/GlobalCache.hs#L145-L154
- I did notice before that the global cache would still be somehow doing things even when one wanted to disable it, so I included a fix for this in my refactoring in #705. We should now not have anything to do with it when using `-c skip`

**Comment by ursi** [comment]
Yes, I had figured out that trick, sorta, I set `HOME`, which worked just fine. Thanks for the fixes!

**Comment by f-f** [comment]
You're welcome :slightly_smiling_face:
