### ISSUE TITLE
Update opening comment in spago.dhall to refer back to Spago's Readme

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#708]
The `spago.dhall` file has this comment added automatically:
```
{-
Welcome to a Spago project!
You can edit this file as you like.
-}
```

Should this comment be removed by default? It doesn't add anything besides notifying someone unfamiliar with spago and package sets in general that it's a Spago-related item. However, I feel like Spago has become more of the norm now that even that reason isn't much of a reason now.

**Comment by hdgarrood** [comment]
I'm not particularly keen on this: just because many of the existing users know what this file is for, we should still design for users who are picking up the tool for the first time.

**Comment by JordanMartinez** [comment]
True, but could it be updated to say something more meaningful than its current comments? At the very least, it could link to the `spago` readme so a user can read more of its documentation.

**Comment by hdgarrood** [comment]
That sounds sensible to me, yes.

**Comment by f-f** [comment]
Yes, I agree with both of you - I'd like to keep the comment there in order to ensure a good initial experience, but I'd also welcome a rework that makes it more substantial/useful (it might be useful to also point out that there's a flag if a user wishes to skip it for future projects)

**Comment by JordanMartinez** [comment]
> it might be useful to also point out that there's a flag if a user wishes to skip it for future projects)

Yeah, but I forgot to include that flag when I was updating some libraries :sweat_smile:
