### ISSUE TITLE
CLI parsing error when `--no-psa` is supplied after subcommand

### ISSUE THREAD

**Issue by hdgarrood** [purescript/spago#713]
It appears that whether the `--no-psa` flag is supplied before or after the subcommand affects the parsing of the rest of the command. For example, this command works in a project I'm working on:
```
$ spago --no-psa bundle-app --main Server
```
however this does not:
```
$ spago bundle-app --no-psa --main Server
Invalid option `--main'
```
I expected one of two things from the second command: either an error that the `--no-psa` flag should come before the subcommand, or for it to work and behave the same way as the first command.

This does not appear to be specific to the `bundle-app` subcommand - I've noticed the same issue with `bundle-module` and `build` too.

**Comment by f-f** [comment]
IIRC there was a config option in `optparse-applicative` to enable mixing global and subcommand-specific flags after the subcommand, but I am not able to find it now :thinking:

**Comment by f-f** [comment]
Maybe [`subparserInline`](https://www.stackage.org/haddock/lts-16.26/optparse-applicative-0.15.1.0/Options-Applicative.html#v:subparserInline)?

**Comment by f-f** [comment]
The new Spago only takes flags after commands
