### ISSUE TITLE
Error in command-specific args should show command-specific help

### ISSUE THREAD

**Issue by hdgarrood** [purescript/spago#714]
For example, if I write `spago build --purs-agrs` then spago prints ``Invalid option `--purs-agrs'`` and then prints the global help (that is, the message you get for `spago --help`).

However, if the subcommand name was recognised, it would probably be more helpful to show the subcommand-specific help (the message you'd get for `spago build --help`).

**Comment by f-f** [comment]
Ultimately we're tied to what `optparse-applicative` supports - I am not sure how to achieve this, and as far as I can see `purs` behaves in the same way?

**Comment by hdgarrood** [comment]
Oh good point, `purs` does indeed behave the same way and I hadn't realised. Perhaps we might be able to get a patch into `optparse-applicative` if it could be made easier to behave in this way (or even if it could be made possible to behave in this way, if it isn't currently, I'm not sure), because that behaviour obviously preferable to me.

**Comment by hdgarrood** [comment]
Actually, looking at this again a few days later, I realised a couple of things. Firstly, if you misspell an option or flag, you don't actually get the full `spago --help` message as I said originally, you just get a small portion of it. Secondly, I don't think I actually agree so much with my original report - since this is an error message, it's just as arguable that the signal-to-noise ratio should be the highest priority - and in this case showing the full subcommand help would add a lot of noise. So actually I take this back, the current behaviour is preferable, in at least one way. I imagine that if we wanted to improve UX here then the ideal way to go about that would just be to add a "did you mean" if a supplied option/flag looks like it might be misspelled. But I don't think we really need an issue here for that. Shall we close?

**Comment by f-f** [comment]
Thanks for the detailed explanation! Yeah I'd say we can close for now.
