### ISSUE TITLE
Required glibc in 0.18

### ISSUE THREAD

**Issue by kim366** [purescript/spago#717]
Yesterday I set up CI for running my Purescript tests on GitHub actions. Today, with the new spago version released, I am running into the following issue in the CI runner:

```
spago: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by spago)
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```

Is glibc a new dependency for spago? If so, what does it add and is it necessary? It seems that in my CI I will have to install C infrastructure now to run Purescript tests. Or is the issue caused by something unrelated?

Thanks!

**Comment by f-f** [comment]
Hi @kim366! We just switched the CI from running on Ubuntu 14.04 to run on Ubuntu 20.04 - so it's very likely that we're now building with a newer version of the `libc`, likely newer than your local one. I'll see if we can downgrade the Linux runner, and if so I'll package up a 0.18.1 with the lower requirements and see if that works.

**Comment by f-f** [comment]
[It looks like we can downgrade to Ubuntu 16.04](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources), hopefully that's enough

**Comment by f-f** [comment]
Fix up in #718

**Comment by kim366** [comment]
Thank you for the quick action! My config specifies ubuntu-latest, so I am not sure what version it is. But if it's just the OS version, it should also be trivial to fix on my end. I'll also try to mirror the workflows in this repo.

**Comment by f-f** [comment]
@kim366 that's interesting - we also currently build on GitHub Actions, with `ubuntu-latest` (which is `18.04` right now). So there shouldn't be any issue since it's literally the same OS? :thinking:

**Comment by kim366** [comment]
I didn't know purescript-contrib/setup-purescript@main was a thing. With this it all works well. Sorry for bothering. Still weird why it worked with old Spago when installing Spago manually from npm.

**Comment by f-f** [comment]
You're welcome! I'll still go ahead and change the build to work with Ubuntu 16.04, since that allows for more compatibility anyways.
