### ISSUE TITLE
MoveFileEx: Error while spago build

### ISSUE THREAD

**Issue by wclr** [purescript/spago#726]
I've encountred this error while running spago build:

```
PS D:\Code\xxxx> spago build   
[info] Installing 2 dependencies.
[info] Searching for packages cache metadata..
[info] Recent packages cache metadata found, using it..
[info] Installing "proxy"
[info] Installing "globals"
[error] Installation failed
[error] Error:
[error] MoveFileEx ".spago\\__download-globals-v5.0.0-9b17743f822960f3\\download" "D:\\Code\\xxxx\\.spago\\globals\\v5.0.0": permission denied (Access is denied.)
```

I've looked and found out that `D:\\Code\\xxxx\\.spago\\globals\\v5.0.0` doesn't exists, I created it to check how it will go.

But then got the error:

```
purs compile: No files found using pattern: .spago/globals/v5.0.0/src/**/*.purs
purs compile: No files found using pattern: .spago/proxy/v3.0.2/src/**/*.purs
Error 1 of 2:
```

**Comment by f-f** [comment]
The last error is due to the fact that spago will assume the files are there if the directory exists, but since you created an empty one the files are not there. They are supposed to get there with the file move that errors out - I'm afraid you'll have to debug it on your side, as there are many reasons why this could happen: maybe permission errors, maybe trying to copy across links or across disks (which doesn't seem to work on Windows)

**Comment by wclr** [comment]
> I'm afraid you'll have to debug it on your side, as there are many reasons why this could happen: maybe permission errors, maybe trying to copy across links or across disks (which doesn't seem to work on Windows)

I think need to find this out, or people will encounter this periodically.

Why spago expect `D:\\Code\\xxxx\\.spago\\globals\\v5.0.0` to exixt here?

**Comment by f-f** [comment]
Spago will create a cache folder named `.spago` in the directory you're running it in, in order to fetch packages. It doesn't only expect that directory to be there, it's supposed to create it too so you shouldn't worry about that.
The part one needs to worry about is the fact that you get a permission error "Access denied" when trying to write to that location - why is it so?

**Comment by wclr** [comment]
`Access denied` here because the directory `D:\\Code\\xxxx\\.spago\\globals\\v5.0.0` doesn't exist.

**Comment by f-f** [comment]
@wclr yes, and the reason it doesn't exist is that your user is not authorized to create it. So my question is: why is your user not authorized to create that folder?

It might help to give you more context on how spago does things:
- it looks like your project folder is `D:\Code\psalm`
- so when running `spago install`, spago wil create the folder `D:\Code\psalm\.spago` to put its files in
- when installing a dependency, say `globals`, spago will first create a folder `D:\Code\psalm\.spago\globals` as a container for all the versions, and then a folder `D:\Code\psalm\.spago\globals\v5.0.0` when fetching that specific version. However, *it looks like it doesn't have write permission to do so*

Makes sense?

**Comment by wclr** [comment]
There is probably something wrong with the `move` command which spago uses internally I can do it if I just do 

`mv .spago\\__download-globals-v5.0.0-9b17743f822960f3\\download D:\\Code\\xxxx\\.spago\\globals\\v5.0.0`

**Comment by wclr** [comment]
There should be no permission issues. Actually, sometimes it works and breaks sometimes after some actions.

**Comment by f-f** [comment]
@wclr great! Then the issue should be upstream, in the [implementation of `mv`](https://www.stackage.org/haddock/lts-16.27/turtle-1.5.20/Turtle-Prelude.html#v:mv). However, I'm working on a patch to see if we can avoid using `mv` at all (for an unrelated bug)

**Comment by wclr** [comment]
Says:
> Works if the two paths are on the same filesystem.
Maybe it thinks that  `.spago\\__download-globals-v5.0.0-9b17743f822960f3\\download` and `D:\\Code\\xxxx\\.spago\\globals\\v5.0.0` are on different? So if to replace second one with `.spago\\globals\\v5.0.0`?

**Comment by wclr** [comment]
This error is due to `vscode` watching, need to add it in settings:

```json
"files.watcherExclude": {    
    "**/.spago/**": true
  },
```

Probably need to add in docs, or not sure if the extension can affect this option.

**Comment by f-f** [comment]
@wclr it sounds like this should be reported [upstream](https://github.com/nwolverson/vscode-ide-purescript) then?

**Comment by wclr** [comment]
Created the issue.

**Comment by f-f** [comment]
@wclr I subscribed to the issue upstream, so I'll keep posted on updates there - let's close this one until we figure out more details
