### ISSUE TITLE
spago garbles output in Gitlab CI

### ISSUE THREAD

**Issue by pmiddend** [purescript/spago#729]
I'm using spago inside a continous integration with Gitlab environment, and even with `--no-color`, it somehow garbles the output, as such:

```
[info] Installing and globally caching "enums"
116[info] Installing and globally caching "exists"
117[info] Installing and global[liyn fc[oai]cn hfIionn]sg t Ia[["nliifslnnotiffranooelg]]il   gi"II[nnhnni["gass[ni
118 lttifnaoaanofngllf]odello ] nii]I g"nn nIl
119ggIsno  ntsbaasatan[ntlaldidalll n lilygfglni lolignco]on gab bga caIa nahlnladnilsln dnytydg g a  lg clcgol"alalbofcicoabohnhblarigiallmn nlyl-gagl yu n yc r"d" aclf fccaeograhcnllecihcdoehnioabaigndbapn gell"g" del
120 f""-y"oft
121 crorcakraat"evc
122eiehngriansnb-aglob ebl"-jefle"ric
123estet""s
124"
125[info] Installing and globally caching "functions"
126[info] Installing and globally caching "functors"
```

What is going on here? I have never witnessed something like this, and it only happens with spago.

**Comment by f-f** [comment]
I also noticed this with the most recent versions - what Spago version are you running?

And does it help if you use `-j 1`?

**Comment by pmiddend** [comment]
Ah, it's fixed with `-j 1` (thanks!), and I know why you suggested this. I guess it's not a big deal since multithreaded logging can simply produce such garbage. But I'll keep this issue open for a while. See if somebody else has something to say about it.

**Comment by f-f** [comment]
[Here's the implementation for the logging](https://github.com/commercialhaskell/rio/blob/91c379f29b158dc91e7bea059fe7874d9a16973c/rio/src/RIO/Prelude/Logger.hs#L370-L383). It looks alright, but it doesn't seem to put any special care into handling many threads logging at the same time, but on the other hand I never encountered the same issue locally, so I'm not really sure what's going on.

**Comment by pmiddend** [comment]
I know the problem with Haskell's IO. As you said, if you don't take care of, say, locking some mutex, you will get garbled output. I guess that's one of the reasons why people say you shouldn't write your own logging and use a library. :D

**Comment by f-f** [comment]
Upstream logging framework won't take care of this and suggested that it might help to set the encoding of the console to `UTF-8`

So if that doesn't work then we have no other choice to implement our own logging :smile: 
I think the easiest way to handle this would be to start a single logs-writer thread at startup and have all the logging functions go through that thread.

**Comment by hdgarrood** [comment]
We have fixed similar issues in the past by setting stdout and/or stderr to use line buffering; I think in some cases they use no buffering by default.

**Comment by f-f** [comment]
@hdgarrood should this be user-configurable or should we use `IO.hSetBuffering IO.stdout IO.LineBuffering` as the compiler does? (we currently don't)

**Comment by hdgarrood** [comment]
I think you might want this to be user configurable in the case of `spago run`, because if you’ve written a PureScript program which displays progress bars or prints a `.` each time a test passes or something, then you will want to turn buffering off in that case. Although in those cases maybe you can just do `spago build` and then call `node` yourself. I’m not sure.

I think line-buffering stdout and not buffering stderr is generally a good default, because stderr is where things like progress bars (which won’t work with line buffering) should be going, so perhaps spago could set stderr to be line buffered while running the compiler and then set it back to no buffering (or whatever it was to start with) afterwards?

**Comment by hdgarrood** [comment]
Oh wait, sorry, I forgot that this is output that spago produces, not compiler output. For output that spago produces, I don’t think it makes a lot of sense to make the buffering mode user configurable - I don’t remember coming across a case where that would have been useful in the compiler. So I think I would look into setting whichever stream this output goes to to use line buffering while spago is doing its thing, and then setting it back before/after running any external program. I’m not certain that will fix this issue though.

**Comment by f-f** [comment]
Good points. I opened #800 adding line buffering only when we do parallel work, which should be the source of the issue here.
