### ISSUE TITLE
cannot execute spago 

### ISSUE THREAD

**Issue by gasacchi** [purescript/spago#733]
Hi, i try to install spago with yarn and success but after installing spago cannot be execute, currenly on Void linux with musl libc,
try to tracking excecutable file and run ```ldd```
```
cd /home/gasacchi/.config/yarn/global/node_modules/spago
ldd ./spago
```
output:
```
/lib64/ld-linux-x86-64.so.2 (0x7f1df1fcf000)
libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f1df1fcf000)
libstdc++.so.6 => /lib/libstdc++.so.6 (0x7f1df1d38000)
libz.so.1 => /lib/libz.so.1 (0x7f1df1b21000)
libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f1df1fcf000)
librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f1df1fcf000)
libutil.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f1df1fcf000)
libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f1df1fcf000)
libgmp.so.10 => /lib/libgmp.so.10 (0x7f1df1aa4000)
libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f1df1fcf000)
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f1df1a8b000)
Error relocating ./spago: __open_2: symbol not found
Error relocating ./spago: __sprintf_chk: symbol not found
Error relocating ./spago: __memcpy_chk: symbol not found
Error relocating ./spago: __strdup: symbol not found
```
i'm not sure, but is this musl libc issue?

**Comment by f-f** [comment]
@gasacchi yes, we don't have a static build, and we dynamically link to `libc` in CI, which means that `musl` is not going to work.

You have a couple of options here:
- build it locally: clone the repo and run `stack install`
- [pickup this PR to add Spago to voidlinux packages](https://github.com/void-linux/void-packages/pull/24723), maybe you're able to get it to work

**Comment by f-f** [comment]
It looks like there's nothing actionable left to do here, so I'll close this
