### ISSUE TITLE
Incorrect dhall file output to command line

### ISSUE THREAD

**Issue by mikesol** [purescript/spago#746]
Hi!

Thanks for your hard work on this very helpful and useful open-source project.

It looks like the filename `spago.dhall` is [hardcoded](https://github.com/purescript/spago/blob/611a7051782ca3ca750fa5eb282bff6ea7f57239/src/Spago/Messages.hs) in the error messages, which led to a bit of confusion as we were trying to debug why our github action was failing. It turned out that we had forgotten to check `test.dhall` into version control.  The action message was:

```bash
Run npx spago -x test.dhall install
[error] Failed to read the config. Error was:
[error] There's no "spago.dhall" in your current location.
```

It would be helpful if the error could display the correct missing file. Thanks!

**Comment by f-f** [comment]
Thanks for reporting! Fix up in #747
