### ISSUE TITLE
Document how to override the location of the global cache

### ISSUE THREAD

**Issue by mikesol** [purescript/spago#751]
When trying to compile with `spago` on a linux env that does not have a `/home` directory, there is an error message `Directory "/home" is not accessible`. Is there a setting that would make it possible to use `spago` in an environment with out `/home`?

**Comment by f-f** [comment]
We don't use `/home` specifically, but we follow the [XDG spec](https://wiki.archlinux.org/index.php/XDG_Base_Directory) to place the cache directory.
You can override the cache location by setting the `XDG_CACHE_DIR` environment variable.

**Comment by mikesol** [comment]
Sounds good, will do & thanks!

**Comment by f-f** [comment]
It looks like we don't have this written down anywhere in the docs, so I'll reopen this to track this documentation need.

**Comment by hdgarrood** [comment]
I just ran into this as well when I had an invalid `XDG_CACHE_HOME` value. If instead of
```
[error] Directory "/var/www" is not accessible. Permissions {readable = True, ... }`
```
we had something like, say,
```
[error] While trying to create global cache directory /var/www/.spago-global-cache:
[error] Directory "/var/www" is not accessible. Permissions {readable = True, ... }`
[error] hint: Set XDG_CACHE_HOME to an absolute directory path in order to control where the global cache is placed.
```
then I expect people would be able to diagnose and fix the issue a little more easily, without needing to refer to the docs.

**Comment by f-f** [comment]
@hdgarrood this is a great idea! I'll edit the title to track this.

**Comment by f-f** [comment]
@hdgarrood this is great idea!

However I think it's still important to document the fact that we use `XDG_CACHE_HOME` to place the cache, so that it's useful also to users that don't get this error but still want to fiddle with this.

**Comment by f-f** [comment]
Reopening to keep track of the missing documentation as explained above

**Comment by f-f** [comment]
The new Spago has unclear rules for how it picks up the cache folder. We are now using [this package](https://www.npmjs.com/package/env-paths) under the hood to get a global cache folder. On Linux, it should be using the `XDG_CACHE_HOME` variable. I however just encountered a situation where I needed to set the `XDG_RUNTIME_DIR` for it to work. I think we should dig more on this and document it properly. [Link to the XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
