### ISSUE TITLE
build --path option question

### ISSUE THREAD

**Issue by wclr** [purescript/spago#761]
I see that `build --path` option adds supplied path to the standard source paths (configured in `spago.dhall`), is it supposed to work this way?

If yes it is probably good to add a more concrete description for cli option.

```
-p,--path PATH   Source path to include -> Source path to include (in addition to included paths in spago.dhall)
```

Not sure how to formulate it better.

**Comment by f-f** [comment]
@wclr sounds good, would you like to PR this change?

**Comment by wclr** [comment]
I added PR, closing.
