### ISSUE TITLE
spago 0.19.2 printing wrong version

### ISSUE THREAD

**Issue by toastal** [purescript/spago#764]
```
$ pwd                                                                                          
/nix/store/lfywycy87bh31xczx6wripp0sll86y61-spago-0.19.2/bin
$ ./spago --version 
0.19.1
```

I'm not much of a Haskeller, but the cabal file still says `0.19.1`

**Comment by cdepillabout** [comment]
It looks like the `package.yaml` in the release tarball was correctly updated to version `0.19.2`, but then the `spago.cabal` file was not regenerated.

From `master` as of right now (which should be the `0.19.2` release):

https://github.com/purescript/spago/blob/614fe15248898d7442bc27d3b52abeca0755f4f6/spago.cabal#L10

**Comment by f-f** [comment]
Do you think we should cut a new minor release now where we update both or would you be fine waiting until the next major release?

**Comment by toastal** [comment]
I think there may be a some issues for some tooling that checks the version or even in debugging. I know it's common to, say, print out tool versions in CI so it's easier to debug a potential issue and a user could be led astray to chasing why Spago didn't upgrade.

**Comment by cdepillabout** [comment]
I'd personally be fine waiting for the next major release.

I also noticed this when trying to package spago-0.19.2 in nixpkgs.

**Comment by f-f** [comment]
[Cut a new version](https://github.com/purescript/spago/releases/tag/0.20.0)
