### ISSUE TITLE
Bundle app but do not run anything ?

### ISSUE THREAD

**Issue by jukefr** [purescript/spago#765]
I want to make a library that gets built to JavaScript and users can load on their page via a script tag to then have said library be available in the scope of the document and do whatever they want with it.
When I bundle with spago it will add a line at the end of the bundle that executes the main function.
Is there any way to disable this ? (currently I just remove last line in post build)

(sorry for two issues in one) Also, is there a way to make it so that the bundle also does not make the module available on the `PS` object but directly via its own module name ? (so instead of the user having to do `PS.Module.function` they would do `Module.function`)

Sorry if this is already documented, I could not find anything.

**Comment by f-f** [comment]
Have you tried with [`spago bundle-module`](https://github.com/purescript/spago/#2-spago-bundle-module)?

**Comment by jukefr** [comment]
This will produce the same result pretty much but the last line will be a module.exports that is not supported by the browser.
