### ISSUE TITLE
How to fix transitive dependency errors

### ISSUE THREAD

**Issue by milesfrain** [purescript/spago#769]
PSA for folks troubleshooting error messages:

With the [release of 0.20.0](https://github.com/purescript/spago/releases/tag/0.20.0), which incorporates #730, you may encounter errors like this in pre-existing projects:
```
[error] Some of your project files import modules from packages that are not in the direct dependencies of your project.
To fix this error add the following packages to the list of dependencies in your config:
- integers
- maybe
- partial
- prelude
```
The error message suggests adding these to `spago.dhall`. A simple way to accomplish this is to run the `install` command with those missing packages:
```
spago install integers maybe partial prelude
```

It might be nice to autogenerate that `spago install ...` line in the error message for convenience.

**Comment by f-f** [comment]
Fixed in #770
