### ISSUE TITLE
spago reports module `Data.Foreign` was not found but package `foreign` is installed

### ISSUE THREAD

**Issue by 0dB** [purescript/spago#774]
I am trying to migrate a project from purescript 0.11.7 to 0.13.8 and to spago. I have successfully done this before with other projects. But for one project I am getting errors that the following modules are not found, even though I have installed `foreign `and `foreign-generic`:

`npx spago build` reports (yes, I use npm / npx because of a local install of purs and spago, to be able to run more than one version of purescript):

```
Module Data.Foreign was not found.
    Module Data.Foreign.Class was not found.
    Module Data.Foreign.Generic was not found.
    Module Data.Foreign.Generic.EnumEncoding was not found.
    Module Data.Foreign.Index was not found.
```

But the packages are installed:

```
$ npx spago ls packages | grep foreign
ffi-foreign                      v0.0.2        Remote "https://github.com/markfarrell/purescript-ffi-foreign.git"
foreign                          v5.0.0        Remote "https://github.com/purescript/purescript-foreign.git"
foreign-generic                  v10.0.0       Remote "https://github.com/paf31/purescript-foreign-generic.git"
foreign-object                   v2.0.3        Remote "https://github.com/purescript/purescript-foreign-object.git"
parsing-foreign                  v0.0.2        Remote "https://github.com/markfarrell/purescript-parsing-foreign.git"
```

This is my `spago.dhall` file:

```
{-
Welcome to a Spago project!
You can edit this file as you like.
-}
{ name = "xxxx"
, dependencies =
  [ "assert"
  , "console"
  , "effect"
  , "foreign"
  , "foreign-generic"
  , "node-fs"
  , "prelude"
  , "psci-support"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
}
```

For migrating, I first cloned my project, ran `spago init`, then ran `spago install` for the packages I need, then, because I got the problems above but many more than those, I created a new directory and copied only the files and directories really needed by spago (basically leaving out all old bower and node files and directories), ran `npm install purescript@~0.13` and then tried to run `spago build` again, and this time getting less errors but still the ones concerning `foreign` and `foreign-generic` above.

I don't see why spago lists the packages but does not find them when trying to build with purs. Any ideas? Am I doing something wrong?

Here some more info if it helps:

```
$ npx purs --version
0.13.8
$ npx spago --version
0.20.0
```

This is my package.set as written to `packages.dhall`:

```
https://github.com/purescript/package-sets/releases/download/psc-0.13.8-20210226/packages.dhall
```

This is my project directory (my user name is x-ed out):

```
drwxr-xr-x+ 1 xxxx Domain Users     0 Apr 13 15:29 node_modules
-rwxr-xr-x+ 1 xxxxx Domain Users 45066 Apr 13 15:29 package-lock.json
-rwxr-xr-x+ 1 xxxxx Domain Users  3012 Apr 12 20:43 packages.dhall
-rwxr-xr-x+ 1 xxxxx Domain Users   330 Apr 12 20:43 spago.dhall
drwxr-xr-x+ 1 xxxxx Domain Users     0 Apr 13 13:11 src
drwxr-xr-x+ 1 xxxxx Domain Users     0 Apr 13 13:11 test
```

**Comment by colinwahl** [comment]
I don't think you're doing anything wrong with `spago` itself - the dependencies should be installed correctly.

In preparation for 0.12, those modules you are referring to (`Data.Foreign`, etc) were changed - they are now under the `Foreign` namespace, see https://github.com/purescript/purescript-foreign/releases/tag/v5.0.0. Since you upgraded `purs` and are now using the `0.13.8` package set, your dependencies got upgraded and there were breaking changes.

I haven't exhaustively checked, but I think changing all of your imports to be `Foreign`, `Foreign.Generic`, etc will fix these particular errors - but you might run into more errors down the line if any other breaking changes were made

**Comment by 0dB** [comment]
Ah, I overlooked that. I already caught that for `Effect`, for example (and the breaking changes there).

Indeed, there they are:

```
$ find . -name Foreign
./.spago/foreign/v5.0.0/src/Foreign
./.spago/foreign-generic/v10.0.0/generated-docs/Foreign
./.spago/foreign-generic/v10.0.0/src/Foreign
./.spago/foreign-object/v2.0.3/bench/Bench/Foreign
./.spago/foreign-object/v2.0.3/src/Foreign
./.spago/foreign-object/v2.0.3/test/Test/Foreign
```

I'm good to go now, and am now running into the (expected) breaking changes and will deal with those.

Thanks for the quick help!
