### ISSUE TITLE
Make it easier to fix "direct dependencies" error message

### ISSUE THREAD

**Issue by rintcius** [purescript/spago#776]
I was thinking that it could be handy if the list of packages that is shown for the following error would instead contain lines that can directly be copy-pasted into `spago.dhall` (rather than having to edit after paste) or, even better if `spago` would ask if it's ok to apply the necessary changes to `spago.dhall`

```
[error] Some of your project files import modules from packages that are not in the direct dependencies of your project.
To fix this error add the following packages to the list of dependencies in your config:
- package1
- package2
- etc
```

The following warning may also be incorporated in the suggestion, though this is less work to do manually:
```
[warn] None of your project files import modules from some projects that are in the direct dependencies of your project.
These dependencies are unused. To fix this warning, remove the following packages from the list of dependencies in your config:
- packageA
- packageB
- etc
```

A step further and not sure how easy this would be to implement, but it would be awesome if `spago` could also apply the addition of **new** dependencies in the same way (as long as it's in the package set). I.e. if it would recognise the package that needs to be added given a certain import that was just added.

**Comment by f-f** [comment]
I believe this was fixed in #770?

**Comment by rintcius** [comment]
Ah right sorry, looks like it does indeed - I used the latest release but didn't check the unreleased fixes.

Does the last paragraph look feasible?

> A step further and not sure how easy this would be to implement, but it would be awesome if spago could also apply the addition of new dependencies in the same way (as long as it's in the package set). I.e. if it would recognise the package that needs to be added given a certain import that was just added.

**Comment by f-f** [comment]
@rintcius implementing that would need having the entire package set available at all times (or at least an index of that). We investigated this and other things in #165, and ultimately declared this out of scope for now

**Comment by rintcius** [comment]
Thank you @f-f - closing

**Comment by f-f** [comment]
You're welcome :slightly_smiling_face:
