### ISSUE TITLE
Assume compatibility with minor / patch compiler releases

### ISSUE THREAD

**Issue by milesfrain** [purescript/spago#777]
Since the latest compiler version is not yet listed in [latest-compatible-sets.json](https://github.com/purescript/package-sets/blob/master/latest-compatible-sets.json), new users starting today will encounter the following error:
```
npm i -g purescript spago

purs --version
0.14.1
spago --version
0.20.0

spago init
[info] Initializing a sample project or migrating an existing one..
[error] It seems that you're using a compiler version that is not supported by package-sets at the moment.
Please install one of the following versions of the compiler and try again: 
- 0.14.0
- 0.13.8
- 0.13.6
...
```

Could spago assume that minor compiler version bumps maintain compatibility with the latest package set? For example, I suspect that `purs 0.14.1` is still compatible with `psc-0.14.0-20210409`.

**Comment by JordanMartinez** [comment]
> I suspect that purs 0.14.1 is still compatible with psc-0.14.0-20210409.

It still is compatible. 

One can workaround this issue by updating their `packages.dhall` file to the latest package set _manually_ (as `spago` currently complains when one runs `spago upgrade-set`) and then add the below `with metadata.version = "v0.14.1"` part to the file. For example...
```dhall
let upstream =
      https://github.com/purescript/package-sets/releases/download/psc-0.14.0-20210409/packages.dhall sha256:e81c2f2ce790c0e0d79869d22f7a37d16caeb5bd81cfda71d46c58f6199fd33f

in  upstream
    with metadata.version = "v0.14.1"
```

**Comment by f-f** [comment]
This is fixed for this release, but we have to do something otherwise we'll encounter this again with the next minor. The logic that handled this compatibility has been there for a while, but got overriden by the newer logic. We could make it so that if the compiler "not in the list" is "semver compatible" with a compiler in the list, then we could use its set.

**Comment by f-f** [comment]
Fix up in #782, @milesfrain @JordanMartinez could you take a look at it?

**Comment by JordanMartinez** [comment]
@f-f LGTM!

**Comment by milesfrain** [comment]
It will be a bit tough to test until we get another compiler bump beyond the latest package set, but I don't see anything looks problematic in that PR. So I'm thinking we can consider this resolved.

**Comment by f-f** [comment]
Great, thank you for taking a look at it. I thought about adding some tests for the change, but the code involved here is fairly `IO-heavy`, and disentangling the whole thing might not be worth it at this stage. We'll have another minor release soon so we'll likely just test it then.
