### ISSUE TITLE
Invoking `spago test` does nothing (purs 0.13.8, spago 0.20.1)

### ISSUE THREAD

**Issue by emiel** [purescript/spago#789]
Is spago 0.20.x supposed to work with PureScript 0.13.x or is it 0.14.x only? When invoking `spago test` with PureScript 0.13.8 and spago 0.20.1 nothing happens. I expect the build and test to run. I'm guessing this may somehow be related to `psa` but I'm unsure. Let me know if you need more info.

To reproduce:

Nothing happens when `spago test` invoked.
```
$ mkdir foo && cd foo
$ npm init -y
$ npm install --save purescript@0.13.8 spago@0.20.1
$ npx spago init
$ npx spago test
<<no output; no build>>
```

Expected output:
```
$ npm install --save spago@0.19.2
$ npx spago test
           Src   Lib   All
Warnings   0     0     0
Errors     0     0     0
[info] Build succeeded.
🍝
You should add some tests.
[info] Tests succeeded.
```

**Comment by f-f** [comment]
Fix up in #790, I'll cut a release as soon as CI is done

**Comment by f-f** [comment]
Released [0.20.2](https://github.com/purescript/spago/tree/0.20.2) with the fix

**Comment by emiel** [comment]
Wow @f-f! Thanks for the quick fix. I'm up and running again.

**Comment by f-f** [comment]
You're welcome 🙂
