### ISSUE TITLE
Unused dependencies are reported when building with --deps-only

### ISSUE THREAD

**Issue by nwolverson** [purescript/spago#794]
I think spago should just never report unused dependencies when building with `--deps-only`, currently it is reporting all dependencies which my project code would use, if I were to build it, as well as those that were unused.

**Comment by f-f** [comment]
Yep, I noticed this as well. To fix this it should be enough to add `&& not depsOnly` (since we have access to the build options) to this check:
https://github.com/purescript/spago/blob/96ea7fee244d8c64705024c3110ec55943bc8852/src/Spago/Build.hs#L120-L121
