### ISSUE TITLE
Request: support Github mirror

### ISSUE THREAD

**Issue by myfreess** [purescript/spago#795]
in source file https://github.com/purescript/spago/blob/master/src/Spago/GitHub.hs , line 58, github's domain name was hard coded

in china ，almost all user hard to access github resources, can we subjoin a option allow people using other github mirrors, like https://github.com.cnpmjs.org/ ？

**Comment by f-f** [comment]
Have you tried setting the `http_proxy` variable as described in https://github.com/purescript/spago/pull/745#issuecomment-780762657?

**Comment by myfreess** [comment]
Thanks! Sorry for my rudeness @f-f

**Comment by f-f** [comment]
@myfreess no worries at all :slightly_smiling_face:
