### ISSUE TITLE
`--src-only` to complement `--deps-only`

### ISSUE THREAD

**Issue by drathier** [purescript/spago#797]
On my machine it takes about 3s to run `spago build` when a single file changed. Running `purs compile "src/**/*.purs"` takes about 0.05s to run. If the deps didn't change, I think spago could run much faster than 3s, and since I'm compiling easily north of 100 times a day, it adds up quickly.

Maybe `--src-only` isn't the way to do this, idk, but it would help me a lot.

**Comment by f-f** [comment]
How would this flag work? If you are looking to "just not pass the dependencies globs to the compiler and pass only the source", then that doesn't work as `purs` would just issue a lot of complaints about missing modules and refuse to build.

In general, the compiler manages the build cache by itself, and we don't/can't do anything about it, so any performance issue should be reported to the compiler and fixed there, as in many cases Spago is just a tiny convenience layer for the compiler's build system.
Does this make sense?

**Comment by drathier** [comment]
Sorry, my bad. My test file didn't have any imports, so I didn't see that issue.

**Comment by f-f** [comment]
No worries at all :slightly_smiling_face:
