### ISSUE TITLE
Can not pass multiple args with `--purs-args` (on Windows)

### ISSUE THREAD

**Issue by wclr** [purescript/spago#804]
Trying to pass multiple purs-args fails for me on windows:

```
spago build --purs-args "-p --json-erros"
```
Invalid option `--json-erros'

Usage: purs.bin COMMAND
  The PureScript compiler and tools
[error] Failed to build.

```
spago build --purs-args '-p --json-erros'
```

```
spago build  -u="-p --json-errors"
```
No luck too.

Though one can use multiple args. 

```
spago build -u -p -u --json-erros
```

So if not applicable may be closed.

**Comment by f-f** [comment]
This should work.

This is how we run `purs` right now:
https://github.com/purescript/spago/blob/c465a41fb9939f883e083ac9ad5293aafe9cda4d/src/Spago/Purs.hs#L156-L161

I wonder if this is due to us using `shell` rather than [`proc`](https://www.stackage.org/haddock/lts-18.2/turtle-1.5.22/Turtle-Bytes.html#v:proc)?

**Comment by fsoikin** [comment]
This also applies to both `--exec-args` and `--node-args` on Windows.

```
> spago run --node-args "foo bar"
Invalid argument `bar'
...

> spago run --exec-args "foo bar"
Invalid argument `bar'
...
```

**Comment by f-f** [comment]
I don't think we can fix this in a meaningful way - it would require us to parse the arguments and split them on spaces. But e.g. things like `--exec-args '-foo "bar baz"'` would produce nonsense. So I think it should be up to the user to handle the proper splitting of the arguments to pass to the underlying commands, knowing that Windows does this.

I'll close this as we can't do much about it, but let's reopen if we come up with a viable idea for how to tackle this.
