### ISSUE TITLE
`spago run --watch` does not rebuild project on source changes

### ISSUE THREAD

**Issue by ae-mo** [purescript/spago#807]
I'm running an application with `spago run --watch`. It is a web server that runs indefinitely while listening on a specific port. 

The expected behavior when running it with `spago run --watch` would be that whenever a source file changes, **spago** would rebuild the project and launch the application again, but none of these two steps seems to happen. 

**Spago** does display the following message on source change though:

```
[info] File changed, triggered a build: "path/to/file.purs"
```

But no build seems to be triggered. At least, the changes are not reflected in the application.

As a workaround, I'm running `spago run` and `spago build --watch` at the same time, which gives the desired behavior.

EDIT: Grammar

**Comment by f-f** [comment]
Thanks for reporting this! I think this is a duplicate of #506?

If you have a long running process then what's happening here is that even though spago recompiles the source then the old process is _not_ killed, so it's still hanging around. We should instead terminate the long-running process when recompiling.

**Comment by f-f** [comment]
I'll close this as the issue is tracked in #506
