### ISSUE TITLE
Spago should have a release checksum to avoid dependency confusion attack

### ISSUE THREAD

**Issue by klarkc** [purescript/spago#816]
One of most common way to hijack a software project is by placing compromised dependencies in place of real ones. Adding a checksum of each release asset in the build process would allow to check if downloaded file corresponds to the expected file.

[Purescript compiler](https://github.com/purescript/purescript) does this using a SHA checksum. So I can do this in my project:

```Makefile
# Makefile
vendor/purescript:
	curl -o /tmp/purescript_linux64.tar.gz -fSL https://github.com/purescript/purescript/releases/download/v${PURS_VERSION}/linux64.tar.gz
	shasum /tmp/purescript_linux64.tar.gz | grep ${PURS_HASH}
	tar -xzf /tmp/purescript_linux64.tar.gz -C vendor
	chmod +x vendor/purescript/purs
	rm /tmp/purescript_linux64.tar.gz
```

`shasum` validates the downloaded binary, so there is no chance to replace it by a compromised binary hijacking the name resolution.

**Comment by f-f** [comment]
We are in the process of switching to [a new Registry](https://github.com/purescript/registry) for PureScript packages, and the new design [includes such SHA checksum when downloading dependencies](https://github.com/purescript/registry#package-metadata).
So this is being taken care of, but I'll leave this open for tracking the change.

**Comment by klarkc** [comment]
@f-f actually I was telling about the spago itself (it's release page should contain the binary hash), but the same applies to the dependencies, of course.

**Comment by f-f** [comment]
Oh I see, this makes sense - I won't have much time to look at this myself, but I'd welcome a PR that implements this!

**Comment by f-f** [comment]
For context, [here](https://github.com/purescript/purescript/blob/18e3b14c556c5bd58e391531e4f4e511f834c3ff/bundle/build.sh#L48-L57) is the code that the purescript compiler uses to compute the sha, we could just add this to the release workflow.
