### ISSUE TITLE
Downloading of package sets results in redirect

### ISSUE THREAD

**Issue by mikesol** [purescript/spago#825]
On the wagsi project, we're seeing an issue where downloading package sets from the command line results in an error. https://github.com/mikesol/wagsi/issues/8#issuecomment-945312610 Originally we thought this was coming from wagsi, but it may be a more general issue that could effect a minority of spago users. It looks like GitHub has some redirect logic for raw files that, for example, prevents straight-up downloads using cURL on this particular machine. This seems to be the same behavior of the HTTP library spago uses internally as well. I'm wondering if anyone has seen this behavior before (you can reference the issue for more info) and if there are any recommendations on what to do in this case? Thanks!

**Comment by mikesol** [comment]
Yup! Looks like it works 💯

**Comment by f-f** [comment]
I am unable to reproduce using the instructions above, so I suspect it's something related to the local configuration of the machine and not a bug in Spago. I'll close for now - let's reopen once we manage to find a reliable repro.
