### ISSUE TITLE
Search for available packages

### ISSUE THREAD

**Issue by adamjc** [purescript/spago#827]
Is it possible to find the name of a package you need without going to https://pursuit.purescript.org/? 

E.g. I want to find out what package Node.Encoding is, how do you do that through the CLI?

**Comment by f-f** [comment]
We already have `spago search` to find things in the modules you have installed.
However the way more common use case (and what I understand you'd like to have here) is to search in the whole package set.
This functionality is currently unimplemented but we'd like to add it - the ticket tracking this is https://github.com/purescript/spago/issues/518

**Comment by adamjc** [comment]
That's exactly what I was after, I'll close this issue as it's a dupe of #518, thanks

**Comment by f-f** [comment]
You're welcome 🙂
