### ISSUE TITLE
Spago build seems unusually slow

### ISSUE THREAD

**Issue by Hazelfire** [purescript/spago#833]
Sorry if this is the wrong place to put this.

I've found that on installing spago, building even relatively small projects has become incredibly slow. Even after building the entire project, just rebuilding without changing any files takes about 49 seconds.

Steps to reproduce:
1. Install spago and purescript
2. Create a new project with `spago init`
3. Add halogen as a dependency
4. Change src/Main.purs to the [counter example](https://purescript-halogen.github.io/purescript-halogen/guide/index.html) shown in the tutorial
5. Run `spago build`
6. Run `spago build` a second time without changing any files

![image](https://user-images.githubusercontent.com/13807753/147338087-f96468ea-3e93-487c-b1a9-d18dc0bc2411.png)

I'm running a [Google Pixelbook, i5, 8GB ram](https://support.google.com/pixelbook/answer/7504948?hl=en). It compiles and runs Haskell much faster than this.

I've tried to install spago and purescript both through yarn but also through nixpkgs, with similar results.

Feel free to close this if you think this is not relevant to anything.

**Comment by f-f** [comment]
Thank you for reporting, this is very interesting!
I think the main thing to figure out at this point would be if the slowdown is happening in Spago or in the compiler.
If you run `spago -V build` you'll get a more detailed log - is there some place where you notice the slowdown?

**Comment by f-f** [comment]
Looking at the discussion in Discord it sounds like you get a similar slowdown even when using just `purs`, so it looks like it's not Spago-related?

**Comment by Hazelfire** [comment]
Yeah it seems to be not spago related, It seems to slow down on this statement, in the compilation stage:
![image](https://user-images.githubusercontent.com/13807753/147347674-045655cd-4806-48e5-b9db-d9cdfa3f1ee5.png)
Feel free to close and I can reopen it at purescript.
