### ISSUE TITLE
Attempt retry using exponential backoff when downloading fails

### ISSUE THREAD

**Issue by mikesol** [purescript/spago#834]
For the past 24-hours or so, GitHub downloads have been crapping out at a rate of 1/100. I suggested on the Discord server that automatic retry (ie 3 retries) with exponential backoff could help get the ball over the net when this happens and @f-f recommended opening an issue. Hopefully I'll be able to implement this soon!

**Comment by f-f** [comment]
Thanks for reporting! I thought we didn't have this, but we do:
https://github.com/purescript/spago/blob/aa7c0de6d903262f69452663c09fad9c441af8d3/src/Spago/GlobalCache.hs#L168-L169

..however it's only for downloading tarballs. In the case of `git` errors there's no retry, and it should be patched somewhere here:
https://github.com/purescript/spago/blob/aa7c0de6d903262f69452663c09fad9c441af8d3/src/Spago/FetchPackage.hs#L144-L158

**Comment by f-f** [comment]
Fixed in #873
