### ISSUE TITLE
spago bundle-app requires xhr2 which seems to be incompatible with parcel 2

### ISSUE THREAD

**Issue by ocramz** [purescript/spago#835]
Output of `parcel build index.html` with `"parcel": "^2.0.1"` :
```
[info] Bundle succeeded and output file to prod/index.js
🚨 Build failed.

@parcel/core: Failed to resolve 'xhr2' from './prod/index.js' 

  /Users/marco/.../prod/index.js:13:34
    12 |       platformSpecific.newXHR = function () {
  > 13 |         var XHR = module.require("xhr2");
  >    |                                  ^^^^^^
    14 |         return new XHR();
    15 |       };

```

My app used to build fine against `parcel 1.12.3` until a misguided version update of the JS tools.

I hope this is the right place to discuss this !

**Comment by f-f** [comment]
Hi! Indeed I'm not sure this falls under Spago's competence - we can't really do much about this except discouraging the use of Parcel (personally I've been using `esbuild` lately).
I wonder if the community has found solutions to this particular issue, maybe worth asking about this on [Discourse](https://discourse.purescript.org/)?

**Comment by ocramz** [comment]
Thank you @f-f , I'll try out `esbuild` at next tooling upgrade. 

Re. this issue : should I keep it open for posterity or not? Is the `platformSpecific.`.. stuff generated by `spago` or `psc` ?

**Comment by thomashoneyman** [comment]
If you want to stay with Parcel, then you can exclude `xhr2` from the Parcel configuration, as seen here:

https://github.com/thomashoneyman/purescript-halogen-realworld/pull/101

...but I also encourage using `esbuild` where possible.

**Comment by f-f** [comment]
It looks like there are no further action points about this, so I'll close this ticket
