### ISSUE TITLE
Removing the `bundle` commands

### ISSUE THREAD

**Issue by f-f** [purescript/spago#836]
[The community is evaluating a proposal to remove `purs bundle`](https://discourse.purescript.org/t/rfc-the-future-of-the-purescript-bundler).

This would affect our `bundle-module` and `bundle-app` commands, as we'd have to decide what to do in such case.
There are some proposals in that Discourse thread, but I'm opening this issue to track the decision here.

**Comment by thomashoneyman** [comment]
Snowpack [takes an interesting approach](https://www.snowpack.dev/guides/optimize-and-bundle) in which they include `esbuild` support by default, but you can swap in other bundlers as you see fit.

**Comment by sigma-andex** [comment]
I created a draft pr #839 to get the discussion started. I changed `spago run` to supoprt es modules and replaced `bundle` to use `esbuild`.

**Comment by f-f** [comment]
In #862 we started using `esbuild` for bundling code when using purs 0.15, deciding to keep the `bundle` commands in spago, since they provide an easy-to-get-started bundling experience.
So I think this resolves the current ticket, and I'll close. Let's reopen it if we figure out that we want to go in another direction instead
