### ISSUE TITLE
How does spago use bower?

### ISSUE THREAD

**Issue by jgarte** [purescript/spago#838]
Hi,

Would someone be able to give me a high level overview of how spago depends on and uses bower?

I'm currently reading [Bower.hs](https://github.com/purescript/spago/blob/master/src/Spago/Bower.hs).

I would just like to have a big picture understanding (forest for the trees) so that I can be more informed reading the source code.

Any help is greatly appreciated.

**Comment by f-f** [comment]
@jgarte what's your use case?

Spago uses Bower in various ways when running the `spago version` command, in preparation for publishing a library. This is the most legacy part of the codebase and we're not interested in fixing it, as the new Registry is about to ship with a new publishing method that doesn't depend on Bower.

**Comment by jgarte** [comment]
> @jgarte what's your use case?

I'm a [GNU GUIX](guix.gnu.org) maintainer and I'm trying to check bower off of the list of things I would need to account for in packaging spago. I wasn't sure if spago directly depended on bower or not. Packaging bower for upstream Guix would be [no easy task](https://dustycloud.org/blog/javascript-packaging-dystopia/) because of Guix's commitment to accounting for all the dependencies in the dependency trail.

> Spago uses Bower in various ways when running the `spago version` command, in preparation for publishing a library. This is the most legacy part of the codebase and we're not interested in fixing it, as the new Registry is about to ship with a new publishing method that doesn't depend on Bower.

Do you have an idea of when the new Registry will ship with a new publishing method that doesn't depend on Bower? 

That's great to know. Thanks for the reply and info. Much appreciated

**Comment by thomashoneyman** [comment]
> Do you have an idea of when the new Registry will ship with a new publishing method that doesn't depend on Bower?

Spago won't be able to drop Bower for at least a year from the date that the Registry ships, as we're providing compatibility with Bower during the transition phase.

Is it possible to package Spago without packaging Bower also? After all, the vast majority of Spago usage is done without the library documentation publishing workflow done via Bower.

**Comment by jgarte** [comment]
> > Do you have an idea of when the new Registry will ship with a new publishing method that doesn't depend on Bower?
> 
> Spago won't be able to drop Bower for at least a year from the date that the Registry ships, as we're providing compatibility with Bower during the transition phase.
> 
> Is it possible to package Spago without packaging Bower also? After all, the vast majority of Spago usage is done without the library documentation publishing workflow done via Bower.

Yup, that's the next thing I was thinking of. I'll just package spago and get bower another way. Maybe using nix or just npm.

Can I use spago currently without bower if I avoid certain features or is it dependent for vital features of spago?

**Comment by thomashoneyman** [comment]
> Can I use spago currently without bower if I avoid certain features or is it dependent for vital features of spago?

If you aren't publishing a library, then you can use Spago without Bower.

**Comment by jgarte** [comment]
> > Can I use spago currently without bower if I avoid certain features or is it dependent for vital features of spago?
> 
> If you aren't publishing a library, then you can use Spago without Bower.

Oh, that's good to know! Thanks a lot.

**Comment by f-f** [comment]
Thank you @jgarte! And feel free to add Guix to the [installation methods](https://github.com/purescript/spago#installation) if this package is going to be available for all Guix users :slightly_smiling_face:

**Comment by jgarte** [comment]
> Thank you @jgarte! And feel free to add Guix to the [installation methods](https://github.com/purescript/spago#installation) if this package is going to be available for all Guix users slightly_smiling_face

I'll make sure to add it once spago gets accepted into upstream GNU Guix.

Now, I'm off to start packaging it :) Thanks for all the help! So much appreciated

**Comment by jgarte** [comment]
¯\_(ツ)_/¯

**Comment by f-f** [comment]
FYI the new spago does not depend on bower anymore, and it's a javascript thing that gets published on NPM. So if Guix has a way to get npm packages in, then this should be straightforward.
