### ISSUE TITLE
Does not compile with `dhall >=1.39`

### ISSUE THREAD

**Issue by hololeap** [purescript/spago#848]
There have been some [API changes which first appear in `dhall-1.39.0`](https://github.com/dhall-lang/dhall-haskell/commit/698101bd549374b0c1b66b36e22dfa450ff993e9#diff-3c6a893ac71793a18f2ddbe1d7bac83c638a8adba7d2f87d869e79d3a24bb990), and it appears that the following function will need to be re-written in order to maintain compatibility:

https://github.com/purescript/spago/blob/33da63176fe07967761f43c83af9715f104013f0/src/Spago/Dhall.hs#L28-L41

**Comment by f-f** [comment]
Thanks for reporting! This should not be a big deal to fix, I'll try to get out a patched release asap

**Comment by f-f** [comment]
[0.20.5](https://github.com/purescript/spago/releases/tag/0.20.5) is out with the fix!

**Comment by hololeap** [comment]
Thank you!
