### ISSUE TITLE
libtinfo Error

### ISSUE THREAD

**Issue by mkohlhaas** [purescript/spago#853]
Cannot invoke spago with its latest release (20.5):

```
./spago: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

The tinfo libraries are installed. Version 20.4 works fine.

**Comment by mkohlhaas** [comment]
Sorry, requested tinfo libraries are not installed. I have **version 6** installed. Spago binary asks for **version 5**!

But spago version 20.4 works fine with tinfo version 6.

**Comment by mkohlhaas** [comment]
Talking about Linux, of course. (Void Linux.)

**Comment by f-f** [comment]
Thanks for reporting! This is terrible, we are not supposed to be depending on libtinfo since #684, but it probably sneaked in #851 when I bumped most of the dependencies. I'll have a look!

**Comment by mkohlhaas** [comment]
Thank you! That was quick!

**Comment by f-f** [comment]
You're welcome :slightly_smiling_face:
