### ISSUE TITLE
Command line arguments with spago run

### ISSUE THREAD

**Issue by j-nava** [purescript/spago#865]
Now that Spago uses `node -e` for `spago run`, there's a disparity (when it comes to command line arguments) between running a Node app using `spago run` and directly with `node` after bundling.

When running with Node, the second argument is expected to be the [path to the JavaScript file being executed](https://nodejs.org/docs/latest/api/process.html#processargv). But when running with `spago run`, because of `node -e`, the second argument is omitted. 

On one hand, that's how Node behaves, so technically this might not be considered an issue with Spago. 

But I believe Spago should simulate the experience of running a Node app directly, so I propose that the file that is `require`d when Spago runs `node -e` should be added to the command line arguments.

**Comment by sigma-andex** [comment]
This is being fixed in [this pr](https://github.com/purescript/spago/pull/866)
