### ISSUE TITLE
Different colors for `Expected` and `Got` in `spago test`

### ISSUE THREAD

**Issue by two-six** [purescript/spago#872]
Is there a way and if not could there be implemented an option to highlight `expected` and `got` parts of the error message in `spago test` command? Right now, I get errors like these while testing my code:

`
 Error: expected ({ content: ((Just "l") : Nil), type: ListType, value: Nothing } : { content: ((Just "l") : Nil), type: TextType, value: Nothing } : { content: Nil, type: NewlineType, value: Nothing } : { content: ((Just "s") : Nil), type: ListType, value: Nothing } : { content: ((Just "s") : Nil), type: TextType, value: Nothing } : { content: Nil, type: NewlineType, value: Nothing } : { content: ((Just "h1") : Nil), type: HeaderType, value: (Just 1) } : { content: Nil, type: NewlineType, value: Nothing } : { content: Nil, type: HorizontalRuleType, value: Nothing } : { content: Nil, type: NewlineType, value: Nothing } : { content: ((Just "link") : Nil), type: LinkType, value: Nothing } : Nil), got ({ content: ((Just "l") : Nil), type: ListType, value: Nothing } : { content: ((Just "l") : Nil), type: TextType, value: Nothing } : { content: Nil, type: NewlineType, value: Nothing } : { content: ((Just "s") : Nil), type: ListType, value: Nothing } : { content: ((Just "s") : Nil), type: TextType, value: Nothing } : { content: ((Just "h1") : Nil), type: HeaderType, value: (Just 1) } : { content: Nil, type: NewlineType, value: Nothing } : { content: ((Just "h1") : Nil), type: HeaderType, value: (Just 1) } : { content: Nil, type: NewlineType, value: Nothing } : { content: Nil, type: HorizontalRuleType, value: Nothing } : { content: Nil, type: NewlineType, value: Nothing } : { content: ((Just "link") : Nil), type: LinkType, value: Nothing } : Nil)
 `
 
It's all in the same color and it would be nice to be able to quickly distinguish these two parts. Maybe add an option to display them on separate lines?

**Comment by f-f** [comment]
Spago only runs the generated code when calling `spago test` - the diffing, coloring, pretty printing, etc are all handled by the testing library you're using (presumably [purescript-spec](https://github.com/purescript-spec/purescript-spec)?) and such bugs should be reported there

**Comment by two-six** [comment]
Thanks for explaining :)
