### ISSUE TITLE
Sourcemaps don't work

### ISSUE THREAD

**Issue by andys8** [purescript/spago#877]
Hi, this is more  a question than an issue:

The docs say to build with `--purs-args "-g sourcemaps"` (which didn't work for me):
https://github.com/purescript/spago#get-source-maps-for-my-project

But there is also [a flag `--source-maps`](https://github.com/purescript/spago/pull/562) provided by spago. 

Is there a difference? Are the docs outdated? When to use what?

Maybe it's possible to clarify this in the docs :)

**Comment by f-f** [comment]
Good question - does the `--source-maps` flag work for you?

**Comment by andys8** [comment]
I'm not sure to what degree I can expect the result, if it depends on other settings or if the user needs to configure browser settings... But for now I think it doesn't seem to be working in chrome dev tools. That's how I started looking into PureScript specific instructions.

The difference is that the `purs` flag fails to build. The spago flag builda fine, but I'm not sure if it makes a difference.

**Comment by f-f** [comment]
Right, I think the docs are outdated here and the `purs` flag just doesn't work anymore.

As of the latest version (`0.20.8`) when you bundle with the `--source-maps` flag in Spago, that gets passed to `esbuild`:
https://github.com/purescript/spago/blob/744bdbbefc538750d4c36888ee53dc5d336314c4/src/Spago/Build.hs#L426
..so the relevant `esbuild` documentation applies, see [here](https://esbuild.github.io/api/#sourcemap).

As for having them work, once you get the `.js.map` file then Chrome should be able to pick it up once the JS maps flag is enabled.

Maybe there are ES-modules specific things that apply here? @sigma-andex any ideas about this?

**Comment by sigma-andex** [comment]
so the spago —source-map flag is the one that gets passed to esbuild to generate the source map for the bundle. I guess this should then be passed to the purs build actually.
Regarding the purs build failing: afaik the source-maps are currently largely broken right now and @j-nava is working on a fix: https://github.com/purescript/purescript/pull/4273. Maybe @j-nava can shed some light on how the purs sourcemaps should work together with the esbuild generated sourcemap.

**Comment by j-nava** [comment]
I've tested a few things and I think this is actually an issue. 

When I run `spago bundle-app --source-maps`, it looks like esbuild bundles an `index.js.map` file based on whatever .map files it can find, and if there's not one for a particular file, it will generate a "placeholder" for it, mapping javascript to javascript. I speculate it does that in case only some of the sources to be bundled have source maps. 

If I build first with `--purs-args "-g sourcemaps"`, the .map files will be there and esbuild will correctly include them. 

I think it's reasonable to expect that if `spago bundle-app` natively supports a `--source-maps` option and compiles the files for me, it would compile them with `-g sourcemaps`. 

So, in my opinion, either removing the `--source-maps` option from `bundle-app`, or making the build phase of `bundle-app` call purs compile with `-g sourcemaps` in case the `--source-maps` option is selected would be fine. 

On a side note, it would be great to see a `--source-maps` option for `spago build` too! 😄

**Comment by f-f** [comment]
> So, in my opinion, either removing the --source-maps option from bundle-app, or making the build phase of bundle-app call purs compile with -g sourcemaps in case the --source-maps option is selected would be fine.
> On a side note, it would be great to see a --source-maps option for spago build too!

I think both of these sound great!

**Comment by f-f** [comment]
I'll mark this as a bug since it's functionality that we advertise having but it's currently broken

**Comment by sigma-andex** [comment]
I agree, I think the `--source-maps` option should pass the argument to `purs`  so the user doesn't have to care about it, and it should be available for `spago build`.

**Comment by andys8** [comment]
If I understand correctly than one issue is that arguments could be improved so that the user doesn't need to run `spago build --source-maps --purs-args "-g sourcemaps"`, right?

But is the actual issue - not related to spago - "afaik the source-maps are currently largely broken right now" likely the reason to end up with:
![image](https://user-images.githubusercontent.com/13085980/167515497-ac1e6491-d662-41db-8b7f-0aa3aeb799f6.png)

Is it expected before https://github.com/purescript/purescript/pull/4273 or worth looking into if the current state of tooling could produce usable source maps? :)

**Comment by JordanMartinez** [comment]
Unfortunately, I think that is expected. The PR you mentioned also fixes https://github.com/purescript/purescript/issues/4034, which is what's causing the above issue.

**Comment by andys8** [comment]
Thanks for letting me know and pointing me to the issue about negative lines 🙂

**Comment by JordanMartinez** [comment]
Just FYI. The negative line/column issue was fixed in purescript/purescript#4343 and was published as `0.15.3-5`. There's a few other changes in this pre-release, but you can try it out via `npm i purescript@0.15.3-5`.

**Comment by f-f** [comment]
In the meantime I forgot everything I knew about sourcemaps, and the new Spago does not implement anything about them, but it's something that we should support.

I'd love if someone in this thread could help with a summary of what we need to do to properly support sourcemaps end-to-end - as in: one can pass the `--sourcemaps` flag to spago and expect to have it working right away

**Comment by CharlesTaylor7** [comment]
I reread this thread a few times, I think it's fair to summarize as follows:

## Problem Statement
(1) Old spago docs recommended manually passing extra `--purs-args "-g sourcemaps"`. This may have been necessary at some point.
(2) If spago builds without sourcemaps, then the bundling step produces unusable source maps. 
(3) If `purs` creates invalid source maps, then the bundling step produces unusable sourcemaps. 


## Resolution
(1) Is no longer part of the spago readme
(2) New Spago builds with the source map codegen target automatically enabled
(3) The reported issue with `purs` source maps has been fixed: https://github.com/purescript/purescript/issues/4034


I experimented with simply passing  `--sourcemap` to esbuild, and no other changes were required to get end to end source maps in my hobby project. 

So with that mind I have a PR here to re-introduce source map support for `spago bundle`: #1030
