### ISSUE TITLE
Installing latest `spago` and `purs` -- incompatible and can't run `init`

### ISSUE THREAD

**Issue by sezna** [purescript/spago#878]
Hello! I'm new here, but loving my interactions with PS/the PS ecosystem.

I think I am encountering another manifestation of #777. I tried installing `purs` with `brew`, and it installed version `0.14.9`. When I run `spago init`, I get the following message:
```
[error] It seems that you're using a compiler version that is not supported by package-sets at the moment.
Please install one of the following versions of the compiler and try again:
- 0.15.0
- 0.14.7
- 0.14.6
- 0.14.5
- 0.14.4
- 0.14.3
- 0.14.2
- 0.14.1
- 0.14.0
- 0.13.8
- 0.13.6
- 0.13.5
- 0.13.4
- 0.13.3
- 0.13.2
- 0.13.0
- 0.12.5
- 0.12.4
- 0.12.3
- 0.12.2
- 0.12.1
- 0.12.0
```

I'm unable to install `purs`/`purescript` via `npm` or `yarn` either. I do have `stack` installed, and I'm on an m1 mac.  
```
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/purs/node_modules/purescript
npm ERR! command failed
npm ERR! command sh -c install-purescript --purs-ver=0.12.5
npm ERR! /usr/local/lib/node_modules/purs/node_modules/zen-observable/lib/Observable.js:65
npm ERR!       throw e;
npm ERR!       ^
npm ERR!
npm ERR! TypeError: Cannot read properties of undefined (reading 'has')
npm ERR!     at getCurrentTask (/usr/local/lib/node_modules/purs/node_modules/install-purescript-cli/index.js:326:24)
npm ERR!     at Object.error (/usr/local/lib/node_modules/purs/node_modules/install-purescript-cli/index.js:480:17)
npm ERR!     at notifySubscription (/usr/local/lib/node_modules/purs/node_modules/zen-observable/lib/Observable.js:140:18)
npm ERR!     at onNotify (/usr/local/lib/node_modules/purs/node_modules/zen-observable/lib/Observable.js:179:3)
npm ERR!     at SubscriptionObserver.error (/usr/local/lib/node_modules/purs/node_modules/zen-observable/lib/Observable.js:240:7)
npm ERR!     at Object.error (/usr/local/lib/node_modules/purs/node_modules/install-purescript/index.js:173:14)
npm ERR!     at notifySubscription (/usr/local/lib/node_modules/purs/node_modules/zen-observable/lib/Observable.js:140:18)
npm ERR!     at onNotify (/usr/local/lib/node_modules/purs/node_modules/zen-observable/lib/Observable.js:179:3)
npm ERR!     at SubscriptionObserver.error (/usr/local/lib/node_modules/purs/node_modules/zen-observable/lib/Observable.js:240:7)
npm ERR!     at Object.error (/usr/local/lib/node_modules/purs/node_modules/download-or-build-purescript/index.js:91:14)

npm ERR! A complete log of this run can be found in:
```

## Versions
```
% spago --version
0.20.8
% purs --version
0.14.9
```

Thanks for your time reading this issue and working on this project. 😄

**Comment by thomashoneyman** [comment]
@f-f We never ended up releasing a 0.14.9 package set. Is there a way to associate 0.14.9 with the latest 0.14.7 package sets as far as Spago is concerned?

**Comment by sezna** [comment]
> Sorry about this! You should definitely be able to use Spago and PureScript 0.14.9 together.


No problem! I appreciate the tooling and I'm excited to help call attention to this. Let me know if there's a workaround I can use in the meanwhile. I'm just now getting into PS so I'm a noob when it comes to debugging the tooling and finding my own workarounds.

**Comment by f-f** [comment]
> We never ended up releasing a 0.14.9 package set. Is there a way to associate 0.14.9 with the latest 0.14.7 package sets as far as Spago is concerned?

Uhm, right now I can't think of any way that is not complicated and hacky :smile:

**Comment by sezna** [comment]
Hmmm…is there anything I can do to unblock myself here? I’m unable to create any spago project

**Comment by thomashoneyman** [comment]
@sezna You can use PureScript 0.14.7 or 0.15.0 without issue. If you really want to use 0.14.9 then you could init a new project with 0.14.7, and then switch to 0.14.9 from there.

**Comment by sezna** [comment]
Hm, using `brew` I don't see a way to install those versions. `brew install purescript@0.14.7` doesn't find anything -- `npm` doesn't work for the above mentioned reason. I guess the only option left is to check out that release and build from source? I'll get going on that! 😄

**Comment by thomashoneyman** [comment]
@sezna I’m surprised the NPM installation is failing for you. What system are you on? If you use Nix, there’s [easy-purescript-nix](https://github.com/justinwoo/easy-purescript-nix).

**Comment by sezna** [comment]
I'm on an m1 mac. Since `npm` was failing for unknown reasons, I built from source which was painless and very easy. 😄 it even copied it into a `bin` folder for me.
