### ISSUE TITLE
Change wording of "Some of your project files import modules from packages that are not in the direct dependencies"

### ISSUE THREAD

**Issue by klntsky** [purescript/spago#886]
I tried to see which modules actually use on one of the dependencies in my `spago.dhall`. I removed it and tried to compile, hoping I'll get compile errors.

But instead I've got this message with recommendation to install the package again.

> [error] Some of your project files import modules from packages that are not in the direct dependencies of your project.

I think it would be useful to support my use-case by including a list of modules that import modules from missing package in the error message.

**Comment by JordanMartinez** [comment]
I believe this is already supported. Which version of `spago` are you using?

**Comment by klntsky** [comment]
@JordanMartinez at least in master spago lists package dependencies, not my project modules.

**Comment by f-f** [comment]
The new Spago written in PureScript will list the modules that you are importing from the offending packages:

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/5480361/213765265-3a8f6648-d132-40f4-8ad2-544616667f06.png">

This should be enough to be able to search for these and see where they are imported.

**Comment by f-f** [comment]
Well, it turns out that adding provenance makes the code easier to write and it's more informative:

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/5480361/213915567-351e96cb-a89a-49c3-a560-30bf4b287166.png">

**Comment by f-f** [comment]
Leaving this open as a reminder that we should document the `--pedantic-packages` flag better.

**Comment by f-f** [comment]
This is now fully shipped, closing
