### ISSUE TITLE
Remote package without specifying the dependencies

### ISSUE THREAD

**Issue by CGenie** [purescript/spago#895]
Hello,

There is a nice option for adding local packages to the package set:

https://github.com/purescript/spago#override-a-package-in-the-package-set-with-a-local-one

I'd like the same for remote packages. Thing is that I suddenly have to specify the dependencies which is cumbersome. With larger projects I have to update things all around.

I was thinking of creating my own custom package set as well: is that a good way to overcome the problem?

**Comment by f-f** [comment]
This is now possible with the new Spago, as long as the upstream package that we want to import has a `spago.yaml` file - see [the new docs](https://github.com/purescript/spago#add-a-package-to-the-package-set) for more info
