### ISSUE TITLE
spago bundle-app should look for esbuild in node_modules

### ISSUE THREAD

**Issue by denizdogan** [purescript/spago#897]
The `findExecutable` looks for the executable only on path, but I think it would be useful if it could look in `node_modules/.bin/` as well, even if it's not on PATH.

**Comment by f-f** [comment]
The usual suggestion here is to use `npx spago`, or to add spago commands to the `package.json` scripts, so that spago starts with the local NPM packages in the path. Would that work for you?

**Comment by denizdogan** [comment]
@f-f That works, thanks!
