### ISSUE TITLE
"Downloading the spago binary failed" - Ubuntu + Docker

### ISSUE THREAD

**Issue by marer** [purescript/spago#908]
I had a "Downloading the spago binary failed." issue on my build server running Ubuntu. 

```
spago bundle-app --main Main --to build/boot.js --source-maps
Downloading the spago binary failed. Please try reinstalling the spago npm package.
purs-tidy check "src/**/*.purs"
All files are formatted.
purs-tidy check "test/**/*.purs"
All files are formatted.
spago test
Downloading the spago binary failed. Please try reinstalling the spago npm package.
[🎉] Build successful.
```

It's strange, because I'm using Ubuntu on host and in docker image, and the only occurrence of this specific error string is in a file that supposed to be used exclusively on Windows.

Both `spago bundle-app` and `spago test` returned exit code 0, so the build was successful although id didn't actually do anything.
I couldn't reproduce this error on the build server nor my local machine.

Versions I'm using:
Spago: 0.20.3
Npm: 6.14.4
Docker: 20.10.9
Ubuntu: 20.04

**Comment by f-f** [comment]
The new Spago does not have a binary anymore (it's all JS), closing
