### ISSUE TITLE
Create `./test/Test/Main.purs` instead of `./test/Main.purs` with `spago init`

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript/spago#923]
I would like to eventually add a warning/info to the Language Server that helps the user when a module name does not fit the directory structure it is in (until a parent's folder name starts with a lower case character).

We already have the functionality that it creates a module name based on the same rule when you create a new file.

With the new features, the machine could then help spot typos in either the folder structure or the module name. Further, when changing a module name, the Language Server could also offer to move the file into the respective folder structure on disk, doing the gruntwork that they were created to do.

Therefore it would be nice if the default project that spago creates with `spago init` wouldn't break this rule. 

Given that there will be a new major version of spago, I thought this could be a nice point in time to fix this.

**Comment by f-f** [comment]
Great idea!
