### ISSUE TITLE
Allow passing options to esbuild

### ISSUE THREAD

**Issue by fkj** [purescript/spago#926]
While attempting to migrate an existing project to PS 0.15.6, I also upgraded spago to 0.20.9.
My project uses the Monaco Editor via FFI, and the version of spago breaks my build process due to the change to esbuild.

The issue is that the Monaco Editor packages TTF fonts, which esbuild do not know how to load by default.
When I call `spago bundle-app` I thus get an error like `No loader is configured for ".ttf" files: node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf`.
Usually there would be an easy fix by simply telling esbuild to load the TTF files as external files, but this is not possible because there is currently no way to pass options to esbuild through spago.
The issue did not exist prior to the move to the esbuild bundler.

I am thus requesting to add an option to pass custom arguments/options to the underlying esbuild call.
A similar option is already available for passing custom arguments/options to the compiler (`--purs-args`).
Adding an option to pass arguments to esbuild was also suggested as a possible fix to #916.

**Comment by MonoidMusician** [comment]
If you want to configure `esbuild` with custom options, it's recommend to run it separately after using `spago build` (instead of `bundle-app`). See this discourse thread for more information:
https://discourse.purescript.org/t/spago-bundle-app-no-loader-for-image-files/3245

**Comment by f-f** [comment]
Perhaps we should document this?

**Comment by andys8** [comment]
Is there a chance that a PR could land that would allow passing esbuild arguments to `bundle-module`?

I stumbled upcross one of these issues where passing `--external:electron` would likely have resolved the issue. But since passing arguments like with `purs` is not possible, it was necessary to modify the build of the project which was more complicated. 

```shell
> spago bundle-module --platform=node -t psvm.js

[info] Build succeeded.
✘ [ERROR] Could not resolve "electron"

    node_modules/.pnpm/got@8.3.2/node_modules/got/index.js:91:28:
      91 │       const electron = require('electron');
         ╵                                ~~~~~~~~~~

  You can mark the path "electron" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

1 error
[error] Bundle failed.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by f-f** [comment]
No chance it would land in the Haskell codebase, which is effectively frozen until we ship the new PureScript release. Much more likely it would land in the PureScript rewrite, [the source for the Bundle command is here](https://github.com/purescript/spago/blob/master/spaghetto/src/Spago/Command/Bundle.purs).

However, why not call esbuild explicitly as suggested by @MonoidMusician above?

**Comment by andys8** [comment]
> However, why not call esbuild explicitly as suggested by @MonoidMusician above?

I can't say exactly what made it complicated in my case, but in a situation where one is dealing with a broken build, es modules and different JS build steps, having to change from `bundle-module` to calling `esbuild` directly and providing some configuration doesn't make the situation to try out if a config option would solve the issue easier. I assume the implementation of `bundle-module` is quite simple, but the information what it's doing under the hood is encapsulated and its configuration somewhat hidden from the user. Then the default could be to always use external build tools and recommend against `spago bundle-module`.    I think in my case being able to pass an argument to esbuild through spago would have been slightly easier.

**Comment by f-f** [comment]
Makes sense. The new Spago supports configuring the bundle via the config file, like this:
```yaml
bundle:
  minify: true
  module: Main
  outfile: index.js
  platform: node
  type: module
```

I guess we could add an `extra_options` config there?

**Comment by f-f** [comment]
This is now supported as we have `package.bundle.extra_args`, see [the docs](https://github.com/purescript/spago#the-configuration-file)
