### ISSUE TITLE
Getting `Error: Remote host not found` despite `--no-install`

### ISSUE THREAD

**Issue by hyphenrf** [purescript/spago#927]
version 0.20.9
purescript 0.14.5
Running `spago bundle-app -sync skip` inside a sandboxed environment still attempts to make a network call.
`output` and `node_modules` directories are already present and contain proper build artifacts. Why is spago attempting to pull package sets? what's missing for it to work with what it has?

**Comment by hyphenrf** [comment]
maybe it's worth mentioning that the sandboxed environment is a nix build, could it be that because the mtimes of all files in a nix build are reset to epoch, that messes with spago's recompilation triggers?

**Comment by f-f** [comment]
I'll close this as duplicate of #575
