### ISSUE TITLE
spago@next: Non-descriptive error if esbuild is missing

### ISSUE THREAD

**Issue by andys8** [purescript/spago#946]
If `esbuild` is installed globally, `spago@next` works fine. But if it not installed, the error message is only "Failed to bundle".  `-v` gives you more information, though.

## Solution

Tell the user that esbuild is missing and needs to be installed.

## Issue

```shell
./bin/bundle.js bundle -p spago-bin
Refreshing the Registry Index...
Reading Spago workspace configuration...
Read the package set from the registry

✅ Selecting package to build: spago-bin

Downloading dependencies...
Building...

✅ Build succeeded.

Bundling...
Failed to bundle.
```

```shell
./bin/bundle.js bundle -p spago-bin -v

Bundling...
Running esbuild: ["--bundle","--outfile=bin/bundle.js","--platform=node","--format=esm","--minify","--banner:js=import __module from 'module';import __path from 'path';import __url from 'url';const require = __module.createRequire(import.meta.url);"]
{ escapedCommand: "esbuild --bundle \"--outfile=bin/bundle.js\" \"--platform=node\" \"--format=esm\" --minify \"--banner:js=import __module from 'module';import __path from 'path';import __url from 'url';const require = __module.createRequire(import.meta.url);\"", exitCode: Nothing, failed: true, isCanceled: false, killed: false, message: "Command failed with ENOENT: esbuild --bundle --outfile=bin/bundle.js --platform=node --format=esm --minify --banner:js=import __module from 'module';import __path from 'path';import __url from 'url';const require = __module.createRequire(import.meta.url);\nspawn esbuild ENOENT\n\n", originalMessage: (Just "spawn esbuild ENOENT"), shortMessage: "Command failed with ENOENT: esbuild --bundle --outfile=bin/bundle.js --platform=node --format=esm --minify --banner:js=import __module from 'module';import __path from 'path';import __url from 'url';const require = __module.createRequire(import.meta.url);\nspawn esbuild ENOENT", signal: Nothing, signalDescription: Nothing, stderr: "", stdout: "", timedOut: false }
Failed to bundle.
```

**Comment by f-f** [comment]
What happens if esbuild is installed in the project? (as opposed to globally?)

I ask because spago should be able to see executables for dependencies that are installed in the local npm project.

**Comment by andys8** [comment]
When I test inside the `spaghetto` folder it doesn't seem to work with local `esbuild`, but this might be on the way it's called or on me.

The issue itself is less about the build failing, but with regards to that `esbuild` is necessary, can be missing and there should be a more informative message, in case it can't be spawned. Currently it's "Failed to bundle.".

**Comment by f-f** [comment]
Right, we could handle it in the same way we do for `purs`:
https://github.com/purescript/spago/blob/243099f29ff5aec77ef236ee07f5213667cc0719/spaghetto/src/Spago/Purs.purs#L26-L31

**Comment by andys8** [comment]
Yep, and here is the old check and error message.

https://github.com/purescript/spago/blob/310a7096b0d3e86f6464c667aa2339045d85d505/src/Spago/Build.hs#L452

**Comment by andys8** [comment]
Btw. this is off topic, but we could also include esbuild and use it with the JavaScript API (in comparison to spawning a process and using the cli).

https://esbuild.github.io/api/#js-async


The suer wouldn't need to install esbuild, but also can't decide the version.

**Comment by f-f** [comment]
> we could also include esbuild and use it with the JavaScript API

I would like this and I have attempted this before, but did not manage - I can't find a link that talks about it, but I could not have `esbuild` in Spago's dependency because the bundle would refuse to run otherwise, as `esbuild` is not written in JS so it can't be included in the bundle.
I'm not going to attempt this myself anymore, but I would accept a patch that implements it.

**Comment by andys8** [comment]
> `esbuild` is not written in JS so it can't be included in the bundle.

Okay, I wasn't aware of that. I assumed the implementation is JS/TS and would be bundled. If the JavaScript bindings are just a wrapper and forking different binaries depending on the system, it might lead to more trouble than benefits in case we include it in spago.
