### ISSUE TITLE
How to output 2 compatible bundles with bundle-module?

### ISSUE THREAD

**Issue by zmrocze** [purescript/spago#961]
# Problem description 

Hey, 
it looks like - because spago of course includes all the necessary definitions in the produced bundle - that it's impossible (or just error-prone) to import two different bundles into one js project.

Say we have module A:

```purescript
module A (arg) where
arg = Nothing
```

and module B

```purescript
module B (func) where 
func :: Maybe Int -> Int
```

and produce two bundles: `A.js` and `B.js`. Then on js side we can't just do:

```js
import {arg} from './A.js'
import {func} from './B.js'
console.log(func arg);
```

because both bundles contain fresh definition for `Maybe`. Is my assumption even right? I base it on some experimentation during debugging, but I don't know how to verify it directly.

# Question

Is it possible to achieve this sort of compatibility and compile parts of purescript code into seperate bundles?

If not out of the box with spago, then how would I eject from spago and just use it to compile source, but do the bundling myself?

Thanks in advance

**Comment by MonoidMusician** [comment]
You're right that two bundles are incompatible. Bundling is a replacement for import mechanisms. If you're using a different import mechanism (ESM, nodejs `require`, etc.), don't bundle and simply use the compilation artifacts from `./output` directly.

**Comment by f-f** [comment]
I think the above is a good answer to the question, so I'll close for now. Let's reopen if we find something actionable about this (e.g. improve docs)
