### ISSUE TITLE
Revisit the README for spago-next

### ISSUE THREAD

**Issue by f-f** [purescript/spago#965]
We should have a new readme for spago-next, where we can revisit the current readme, and:
- adapt the current docs to the new commands/workflow/config
- remove stale content
- park somewhere documentation for features that we wish for, but are not currently implemented
- document new features (there are a bunch of TODOs in the codebase along these lines)

**Comment by natefaubion** [comment]
One issue I found in the docs is that extra_packages is shown to be an array, but should be an object.

**Comment by f-f** [comment]
Fixed in 5a2c2ca2620c243243ed910af0832c2792b56b91
