### ISSUE TITLE
`spago install --test-deps`

### ISSUE THREAD

**Issue by thought2** [purescript/spago#983]
spago@next configured with `pedantic_packages: true` errors when a package imports a transitive dependency.
In a normal package it logs the suggestion like:

`spago install -p my-package console`

Running the command works. However, if the same happens with a missing dependency in the tests of a package, the following command is suggested:
`spago install --test-deps -p my-package console`

This command seems to be not implemented yet.

**Comment by f-f** [comment]
Yeah, this flag is not wired in yet, see this TODO: https://github.com/purescript/spago/blob/master/spaghetto/src/Spago/Purs/Graph.purs#L213
