### ISSUE TITLE
Make psa options (e.g. `pedantic`, `strict`) options for each package, not for the entire workspace

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#988]
In [`language-purescript`](https://github.com/JordanMartinez/purescript-language-purescript), I've defined two scripts that are helpful for that project. One is a single file whereas another has multiple files that encompass the script.

For the main library, I want to enable the `pedantic` and `strict` options. But for the scripts themselves, I don't want these enabled because they interfere with my development. However, these options can only be enabled/disabled globally on the entire workspace rather than each package individually. As a result, these scripts, which may have more imports than needed or produce warnings, cause CI to fail despite such failures being irrelevant.

Rather than defining those two options on the workspace, can they be defined on each package individually?

**EDIT**: Current status of this issue is here: https://github.com/purescript/spago/issues/988#issuecomment-1734388070

**Comment by f-f** [comment]
It sounds like we'd be better off moving these options (and presumably all the psa options as well) to be a package property, rather than a workspace property - that's all good by me, as long as we don't end up with both (which is why we only have the workspace ones at the moment)

It might be a good occasion to write some tests for this psa integration, given that it doesn't seem to trigger sometimes, see #982

**Comment by JordanMartinez** [comment]
If we move those into the package config, then there's some interplay there. For single-package repo, this change makes no difference. For multi-package repo, some interplay arises. These cases are described below.

```mermaid
flowchart TD
  subgraph "Case 1"
    A ---> DepsA
    B ---> DepsB
  end
  
  subgraph "Case 2"
    A2 ---> Deps1
    B2 ---> Deps1
  end

  subgraph "Case 3"
    A3 ---> Deps3
    A3 ---> B3
    B3 ---> Deps3
  end
```

In case 1, A and B both depend on different dependencies (e.g. none for A and `prelude` for B). In this case, censoring lib warnings works no differently than it does now.

In case 2, censoring lib warnings may need to work a bit differently. If A2's configuration is to censor `Deps1` warnings whereas B2 does not, what happens when one runs `spago build`, which builds both packages? In this conflict, do we censor or do we not? I assume we do not.

In case 3, if B3 has `censor-warnings` enabled but `A3` does not censor its library dependencies' warnings, and the user runs `spago build`, do we censor B3's warnings or not?

**Comment by f-f** [comment]
A solution that would tackle all situation is that we would stop building all the packages in a monorepo in a single glob, but we'd build each one of them sequentially. In this way we'd be able to apply different building options (PSA options, or the graph check) to them.

In fact there is another issue that we have right now due to the fact that we build all the globs together: if I have a package A that depends on package B (as declared in the configuration), package B can import a module from package A (since we just merge all the globs, the compiler does not have the concept of a package so things are fine if there's no circular module dependency), and you'd never figure out unless you try to build package B by itself. Sequentially building all of them would solve this too.

There are a few issues that we'd have to figure out to achieve this though:
- we would need to figure out a topological sort of the workspace packages, so we can build them in order
- we would not be "building all the packages together" anymore, which means that in the Case1 above the two packages could have modules with clashing names, while that's not allowed right now. I am on the fence on whether we should be allowing this or not - we could take care of it by running a graph check at the end of the build, but that's an additional `purs` invocation that we could save.

**Comment by JordanMartinez** [comment]
> the two packages could have modules with clashing names, while that's not allowed right now. I am on the fence on whether we should be allowing this or not

Why? Is it just because of the additional `purs` invocation? Or are there usecases this would prevent that you don't want to allow?

**Comment by thomashoneyman** [comment]
Personally I think it’s perfectly fine for two packages to have the same module name. You couldn’t publish them both or build them together, but that’s well-understood. I can imagine having two Main modules, for example, which are never included together but are often used separately (scripts, etc).

**Comment by thomashoneyman** [comment]
I also think it’s reasonable to interpret “spago build” as “build each project” sorted topologically rather than “compile the combined globs”. Since a workspace shares an output directory, shared dependencies won’t be rebuilt, right?

**Comment by f-f** [comment]
> Since a workspace shares an output directory, shared dependencies won’t be rebuilt, right?

The monorepo assumption of "there's one shared output directory" is exactly the problem here - colliding module names will bust the cache. This is not a big issue if we are only dealing with multiple `Main` modules, but it will have bigger effects if left unchecked.
I also don't think there needs to exist a constraint for unique module names per build, but until the compiler knows anything about packages (i.e. the usual https://github.com/purescript/purescript/issues/3493) we are pretty much stuck with this set of tradeoffs.

**Comment by JordanMartinez** [comment]
I think this work should be broken up into 2 PRs:
- building each project separately
- relocating the psa options from the workspace to the packages

**Comment by JordanMartinez** [comment]
> Personally I think it’s perfectly fine for two packages to have the same module name. You couldn’t publish them both or build them together, but that’s well-understood. I can imagine having two Main modules, for example, which are never included together but are often used separately (scripts, etc).

Just a thought, but we could add a flag to the package section in `spago.yaml` that means "Don't build me when building all packages. I can only be built when selected specifically". This would allow the IDE to use `spago build` without causing issues for the dev's normal experience. Thoughts?

**Comment by f-f** [comment]
The IDE still builds in the output folder, so I don't see how this changes anything?

**Comment by JordanMartinez** [comment]
If packages Prod and Dev both define a module `Foo`, it would prevent the IDE from overwriting Dev's version with Prod's version. Overwriting could still occur, but only if one built that package specifically.

**Comment by JordanMartinez** [comment]
Now that #1018 has been merged, onto the next task:
> Relocating the psa options from the workspace to the packages

There's a few design questions to think through here:
1. Which PSA options are moved and which stay in the workspace?
2. How should the PSA code be changed to account for the new design?
3. How does a CLI value that overrides a `spago.yaml` configuration value work in the context of multi-package repos?

For 1, currently we have the following PSA options. I propose changing them in the following way:
- `showSource` - whether to show source code location in errors. Keep in workspace configuration? I honestly don't know why anyone would set this to false. Maybe this setting should be dropped entirely?
- `strict` - promotes warnings to errors. Move to package configuration.
- `statVerbosity` - whether to show stats at end of build. Move to package configuration.
- `stashFile` - persist compiler warnings. Move to package configuration.
- Warning censoring/filtering related:
    - `censorBuildWarnings` - used to censor warnings from dependency, project, both, or neither (i.e none). This should be split into two new values:
        - `censorLibraryWarnings`: (workspace configuration) censor warnings from any `.spago` dependency, but not any workspace packages that are dependencies
        - `censorPackageWarnings`: (package configuration) censor warnings from code specific to this package. This value is used when building this package specifically or building this package because the selected workspace package depends on it.
    - `censorCodes` - when `censorBuildWarnings` is not `none`, array of warning codes to censor. This should be split into two new values:
        - `censorLibraryCodes`: (workspace configuration) same as above but only for files from `.spago`.
        - `censorProjectCodes`: (package configuration) same as above but only for files from this package
    - `filterCodes` - array of warning codes to exclusively show. This should be split into two new values:
        - `filterLibraryCodes`: (workspace configuration) same as above but only for files from `.spago`.
        - `filterProjectCodes`: (package configuration) same as above but only for files from this package

For 2, I propose the following changes:
- Add another case to `PsaPath` called `WorkspaceLib` that distinguishes a `.spago` dependency (i.e. `Lib`) from a workspace package this is a dependency of the selected one (i.e. `WOrkspaceLib`).
- Update the stats outputted at the end of the build to include a third column, `WLib` for `WorkspaceLib` as the PSA options used
- Update the code to account for the `censorBuildWarnings`/`censorCodes`/`filterCodes` changes above

For 3, currently, the CLI value can be used to override the `spago.yaml` configuration's value. When all such values were defined in the workspace `spago.yaml`, it was straightforward what should occur when the CLI value overrides the workspace one. In the new design, packages can have different values for this configuration. When dealing with single-package repos, `spago build --strict` works the same as before. But, when working with multi-package repos, what does `spago build --strict` mean? Presumably, the CLI flag in this case would override the config values for all packages.

**Comment by f-f** [comment]
Great analysis. Answering to your points:

1. Your spec is great, and yes let's drop `showSource`
2. I think for this we need to take into account the "duplicate build succeeded" issue - I would like to shink the Psa tables into a single one for all packages. In this sense, all the workspace packages are "source", and all the external dependencies are "lib". I don't think we need to add another column, because we are building the packages in topological order, so the warnings from workspace-local dependencies of the current package are "consumed" (and dealt with) when building that package, before getting to build the current one
3. I think it makes sense to have the CLI flag override the setting for all packages

**Comment by JordanMartinez** [comment]
>  so the warnings from workspace-local dependencies of the current package are "consumed" (and dealt with) when building that package, before getting to build the current one

Hm... Another design issue will be how to deal with stash files. Ideally, the compiler will always output warnings. But until that's done, we will need to persist package-specific warnings to a package-specific file. Otherwise, there will be issues with the stash files. 

For example, let's say I have package A and B where B depends on A. If I run `spago build`, such that Package A is compiled and then Package B, then package A emits its warnings and errors and we record that. Then Package B is built, and we record its warnings and errors. However, how do we stash this information? Let's say after this prior run we then call `spago build -p package-a`. If we stash both packages' info in the same stash file (which I believe is how it's done today), then Package A's warnings may not be re-emitted in this second call and so `--strict` may not cause the build to fail in this case whereas it would have in the previous case. If we stash them separately, then the same information should persist regardless of how the calls are made.

**Comment by JordanMartinez** [comment]
We got rid of them in #1045.

Ok, on to the third part now. Given all of the changes done so far, what should the ideal output be for a single- and multi-package build?

**Comment by f-f** [comment]
I'll take Spago's build as an example. The current build output is this:

```console
Refreshing the Registry Index...
Reading Spago workspace configuration...
Read the package set from the registry

✅ Selecting 6 packages to build:
    docs-search-client-halogen
    docs-search-common
    docs-search-index
    spago
    spago-bin
    spago-core

Writing a new lockfile
Downloading dependencies...
Building...
Building packages in the following order:
1) docs-search-common
2) docs-search-client-halogen
3) docs-search-index
4) spago-core
5) spago
6) spago-bin
Building package: docs-search-common
⚠️ Failed to decode PsaResult at index '0': Unexpected end of JSON input
Json was: 

✅ Build succeeded.

Building package: docs-search-client-halogen
[ 1 of 22] Compiling Spago.Generated.BuildInfo
[ 2 of 22] Compiling Docs.Search.JsonCodec
[ 3 of 22] Compiling Docs.Search.DocTypes
[ 4 of 22] Compiling Docs.Search.DocsJson
[ 5 of 22] Compiling Docs.Search.Types
[ 6 of 22] Compiling Docs.Search.Loader
[ 7 of 22] Compiling Docs.Search.Config
[ 8 of 22] Compiling Docs.Search.Score
[ 9 of 22] Compiling Docs.Search.TypeDecoder
[11 of 22] Compiling Docs.Search.Meta
[10 of 22] Compiling Docs.Search.PackageIndex
[13 of 22] Compiling Docs.Search.SearchResult
[12 of 22] Compiling Docs.Search.TypeQuery
[15 of 22] Compiling Docs.Search.TypeShape
[14 of 22] Compiling Docs.Search.Declarations
[16 of 22] Compiling Docs.Search.ModuleIndex
[17 of 22] Compiling Docs.Search.TypeIndex
[18 of 22] Compiling Docs.Search.App.Sidebar
[19 of 22] Compiling Docs.Search.Engine
[20 of 22] Compiling Docs.Search.BrowserEngine
[21 of 22] Compiling Docs.Search.App.SearchResults
[22 of 22] Compiling Docs.Search.App
           Src    Lib   All 
Warnings   0/82     0   0/82
Errors        0     0      0

✅ Build succeeded.

Building package: docs-search-index
[1 of 9] Compiling Docs.Search.ModuleParser
[2 of 9] Compiling Test.Declarations
[3 of 9] Compiling Test.ModuleIndex
[5 of 9] Compiling Docs.Search.NodeEngine
[4 of 9] Compiling Test.TypeQuery
[6 of 9] Compiling Docs.Search.IndexBuilder
[8 of 9] Compiling Test.IndexBuilder
[7 of 9] Compiling Test.ModuleParser
[9 of 9] Compiling Test.Docs.Search.Main
           Src   Lib   All
Warnings   0/3     0   0/3
Errors       0     0     0

✅ Build succeeded.

Building package: spago-core
[1 of 3] Compiling Spago.Core.Prelude
[2 of 3] Compiling Spago.FS
[3 of 3] Compiling Spago.Core.Config
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.

Building package: spago
[ 1 of 49] Compiling Spago.Psa.Types
[ 2 of 49] Compiling Spago.Prelude
[ 3 of 49] Compiling Spago.Lock
[ 4 of 49] Compiling Spago.Tar
[ 5 of 49] Compiling Spago.Cmd
[ 6 of 49] Compiling Spago.Db
[ 7 of 49] Compiling Spago.Git
[ 8 of 49] Compiling Spago.Esbuild
[ 9 of 49] Compiling Test.Prelude
[11 of 49] Compiling Test.Spago.Unit.FindFlags
[10 of 49] Compiling Spago.Purs
[12 of 49] Compiling Spago.Psa.Output
[13 of 49] Compiling Test.Spago.Init
[14 of 49] Compiling Test.Spago.Upgrade
[15 of 49] Compiling Test.Spago.Lock
[16 of 49] Compiling Test.Spago.Bundle
[17 of 49] Compiling Test.Spago.Registry
[18 of 49] Compiling Test.Spago.Run
[19 of 49] Compiling Test.Spago.Publish
[20 of 49] Compiling Test.Spago.Docs
[21 of 49] Compiling Spago.Registry
[22 of 49] Compiling Spago.Config
[23 of 49] Compiling Spago.Command.Registry
[24 of 49] Compiling Spago.Psa.Printer
[25 of 49] Compiling Spago.Psa
[26 of 49] Compiling Spago.Command.Init
[27 of 49] Compiling Test.Spago.Unit.CheckInjectivity
[28 of 49] Compiling Spago.BuildInfo
[29 of 49] Compiling Spago.Repl
[30 of 49] Compiling Spago.Command.Bundle
[31 of 49] Compiling Spago.Command.Fetch
[32 of 49] Compiling Test.Spago.Unit
[33 of 49] Compiling Test.Spago.Install
[34 of 49] Compiling Test.Spago.Ls
[35 of 49] Compiling Test.Spago.Sources
[37 of 49] Compiling Test.Spago.Test
[36 of 49] Compiling Test.Spago.Build.Polyrepo
[38 of 49] Compiling Test.Spago.Build
[39 of 49] Compiling Test.Spago
[40 of 49] Compiling Spago.Command.Upgrade
[41 of 49] Compiling Spago.Command.Ls
[42 of 49] Compiling Spago.Command.Sources
[43 of 49] Compiling Spago.Purs.Graph
[44 of 49] Compiling Spago.Command.Build
[45 of 49] Compiling Spago.Command.Repl
[46 of 49] Compiling Spago.Command.Docs
[48 of 49] Compiling Spago.Command.Run
[47 of 49] Compiling Spago.Command.Publish
[49 of 49] Compiling Spago.Command.Test
           Src    Lib   All 
Warnings   0/10     0   0/10
Errors        0     0      0

✅ Build succeeded.

Building package: spago-bin
[1 of 2] Compiling Spago.Bin.Flags
[2 of 2] Compiling Main
           Src   Lib   All
Warnings   0/5     0   0/5
Errors       0     0     0

✅ Build succeeded.
```

I would like to instead just report a build success/fail at the end, together with an aggregated PSA display, like this:

```console
Refreshing the Registry Index...
Reading Spago workspace configuration...
Read the package set from the registry

✅ Selecting 6 packages to build:
    docs-search-client-halogen
    docs-search-common
    docs-search-index
    spago
    spago-bin
    spago-core

Writing a new lockfile
Downloading dependencies...
Building...
Building packages in the following order:
1) docs-search-common
2) docs-search-client-halogen
3) docs-search-index
4) spago-core
5) spago
6) spago-bin

Building package: docs-search-common

Building package: docs-search-client-halogen
[ 1 of 22] Compiling Spago.Generated.BuildInfo
[ 2 of 22] Compiling Docs.Search.JsonCodec
[ 3 of 22] Compiling Docs.Search.DocTypes
[ 4 of 22] Compiling Docs.Search.DocsJson
[ 5 of 22] Compiling Docs.Search.Types
[ 6 of 22] Compiling Docs.Search.Loader
[ 7 of 22] Compiling Docs.Search.Config
[ 8 of 22] Compiling Docs.Search.Score
[ 9 of 22] Compiling Docs.Search.TypeDecoder
[11 of 22] Compiling Docs.Search.Meta
[10 of 22] Compiling Docs.Search.PackageIndex
[13 of 22] Compiling Docs.Search.SearchResult
[12 of 22] Compiling Docs.Search.TypeQuery
[15 of 22] Compiling Docs.Search.TypeShape
[14 of 22] Compiling Docs.Search.Declarations
[16 of 22] Compiling Docs.Search.ModuleIndex
[17 of 22] Compiling Docs.Search.TypeIndex
[18 of 22] Compiling Docs.Search.App.Sidebar
[19 of 22] Compiling Docs.Search.Engine
[20 of 22] Compiling Docs.Search.BrowserEngine
[21 of 22] Compiling Docs.Search.App.SearchResults
[22 of 22] Compiling Docs.Search.App

Building package: docs-search-index
[1 of 9] Compiling Docs.Search.ModuleParser
[2 of 9] Compiling Test.Declarations
[3 of 9] Compiling Test.ModuleIndex
[5 of 9] Compiling Docs.Search.NodeEngine
[4 of 9] Compiling Test.TypeQuery
[6 of 9] Compiling Docs.Search.IndexBuilder
[8 of 9] Compiling Test.IndexBuilder
[7 of 9] Compiling Test.ModuleParser
[9 of 9] Compiling Test.Docs.Search.Main

Building package: spago-core
[1 of 3] Compiling Spago.Core.Prelude
[2 of 3] Compiling Spago.FS
[3 of 3] Compiling Spago.Core.Config

Building package: spago
[ 1 of 49] Compiling Spago.Psa.Types
[ 2 of 49] Compiling Spago.Prelude
[ 3 of 49] Compiling Spago.Lock
[ 4 of 49] Compiling Spago.Tar
[ 5 of 49] Compiling Spago.Cmd
[ 6 of 49] Compiling Spago.Db
[ 7 of 49] Compiling Spago.Git
[ 8 of 49] Compiling Spago.Esbuild
[ 9 of 49] Compiling Test.Prelude
[11 of 49] Compiling Test.Spago.Unit.FindFlags
[10 of 49] Compiling Spago.Purs
[12 of 49] Compiling Spago.Psa.Output
[13 of 49] Compiling Test.Spago.Init
[14 of 49] Compiling Test.Spago.Upgrade
[15 of 49] Compiling Test.Spago.Lock
[16 of 49] Compiling Test.Spago.Bundle
[17 of 49] Compiling Test.Spago.Registry
[18 of 49] Compiling Test.Spago.Run
[19 of 49] Compiling Test.Spago.Publish
[20 of 49] Compiling Test.Spago.Docs
[21 of 49] Compiling Spago.Registry
[22 of 49] Compiling Spago.Config
[23 of 49] Compiling Spago.Command.Registry
[24 of 49] Compiling Spago.Psa.Printer
[25 of 49] Compiling Spago.Psa
[26 of 49] Compiling Spago.Command.Init
[27 of 49] Compiling Test.Spago.Unit.CheckInjectivity
[28 of 49] Compiling Spago.BuildInfo
[29 of 49] Compiling Spago.Repl
[30 of 49] Compiling Spago.Command.Bundle
[31 of 49] Compiling Spago.Command.Fetch
[32 of 49] Compiling Test.Spago.Unit
[33 of 49] Compiling Test.Spago.Install
[34 of 49] Compiling Test.Spago.Ls
[35 of 49] Compiling Test.Spago.Sources
[37 of 49] Compiling Test.Spago.Test
[36 of 49] Compiling Test.Spago.Build.Polyrepo
[38 of 49] Compiling Test.Spago.Build
[39 of 49] Compiling Test.Spago
[40 of 49] Compiling Spago.Command.Upgrade
[41 of 49] Compiling Spago.Command.Ls
[42 of 49] Compiling Spago.Command.Sources
[43 of 49] Compiling Spago.Purs.Graph
[44 of 49] Compiling Spago.Command.Build
[45 of 49] Compiling Spago.Command.Repl
[46 of 49] Compiling Spago.Command.Docs
[48 of 49] Compiling Spago.Command.Run
[47 of 49] Compiling Spago.Command.Publish
[49 of 49] Compiling Spago.Command.Test

Building package: spago-bin
[1 of 2] Compiling Spago.Bin.Flags
[2 of 2] Compiling Main

             Src  Lib     All
Warnings   0/100    0   0/100
Errors         0    0       0

✅ Build succeeded.
```

As a sidenote: we are also getting a PSA error when the build output is empty, i.e. nothing to build, so we should also fix that as it will be increasingly common

**Comment by JordanMartinez** [comment]
Since we reverted back to compiling everything in one go, it seems the output issue is no longer relevant, correct?

**Comment by f-f** [comment]
Indeed! And I even think we are done here, since #1049 is tracking the last part of this. I'll close 🙂
