### ISSUE TITLE
`spago publish` issue when root package included in `extra_packages`...?

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#992]
```sh
$ npx spago publish -p language-purescript --verbose
...
Called `purs graph`, decoding..
Reading metadata from file: /home/USER/.cache/spago-nodejs/registry/metadata/json-codecs.json
Reading package from Index: json-codecs
Reading metadata from file: /home/USER/.cache/spago-nodejs/registry/metadata/language-purescript.json
Got error while reading metadata file: ENOENT: no such file or directory, open '/home/USER/.cache/spago-nodejs/registry/metadata/language-purescript.json'
Your package language-purescript is not ready for publishing yet, encountered 1 errors:


❌ Could not find a suitable build plan, the following packages do not point to registry versions: ["json-codecs"]
```

While the main error says the issue is with `json-codecs`, it seems like the real issue is `language-purescript`, possibly because I [include that as an "extra package"](https://github.com/JordanMartinez/purescript-language-purescript/blob/2810b44c88da1cf600011c19135d3666ef0a45e3/spago.yaml#L61-L62)? Before I did some refactoring, I was depending on it in some other script.

**Comment by f-f** [comment]
Yeah, `language-purescript` is a "Workspace package", so things don't work if you tell spago that it's an "Extra package". It looks like we currently don't prevent this from happening, but we should.

**Comment by f-f** [comment]
There's now a (hopefully helpful) error if you try to declare a workspace package as an extra one:

<img width="923" alt="image" src="https://github.com/purescript/spago/assets/5480361/8a3d23db-4728-4172-9b84-9dc60933335f">

**Comment by f-f** [comment]
@JordanMartinez now that this error condition is fixed, I am curious about the reason for adding the package itself as an extra package - is it a workaround for something?

**Comment by JordanMartinez** [comment]
I think I wrote Package A and then wrote Package B and a spago error somewhere in there said it couldn't find Package A in my list of packages and suggested adding to the the 'extra_packages' field.

**Comment by JordanMartinez** [comment]
If I moved `language-purescript`'s `spago.yaml`'s `package` section into the workspace one, but kept the script packages where they are, getting this project structure:
```
ROOT
  /spago.yaml -- workspace & language-purescript package defined
  /src
  /test
  /scripts
    /script1
      /spago.yaml -- script 1 defined
```
Should `spago publish -p language-purescript` work?

**Comment by f-f** [comment]
> suggested adding to the the 'extra_packages' field

The only error that I can find mentioning `extra_packages` is:
```
Some of the packages you specified as `extra_packages` do not point to the Registry.
To be able to publish a package to the registry, all of its dependencies have to be packages registered on the Registry.
Please replace the following packages with versions that are present in the Registry:
```

...did you get a different one?

**Comment by f-f** [comment]
> Should spago publish -p language-purescript work?

Should definitely work

**Comment by JordanMartinez** [comment]
> > suggested adding to the the 'extra_packages' field
> 
> The only error that I can find mentioning `extra_packages` is:
> 
> ```
> Some of the packages you specified as `extra_packages` do not point to the Registry.
> To be able to publish a package to the registry, all of its dependencies have to be packages registered on the Registry.
> Please replace the following packages with versions that are present in the Registry:
> ```
> 
> ...did you get a different one?

Yup. The error I got is the one in the opening thread.

**Comment by JordanMartinez** [comment]
Since https://github.com/purescript/registry/issues/386 worked, I'm guessing there's a caching issue on my side of things?

**Comment by f-f** [comment]
> Yup. The error I got is the one in the opening thread.

I'm aware of that - but that doesn't mention adding things to `extra_packages` either. My point here being that Spago should not try to tell you to add things to `extra_packages`, and I believe it does not at the moment.
So I'm trying to figure out if you got an error message that convinced you to add things to `extra_packages`, because it's something we should fix if that's the case.

> I'm guessing there's a caching issue on my side of things?

What do you mean? The Registry will ignore a lot of the things defined in the spago.yaml, and just pick the dependencies from there (since it's all it needs). Things should work if you remove the root package from the `extra_packages`. If they don't then we have another bug.
