### ISSUE TITLE
Add `--no-fetch` and `--no-build` flags

### ISSUE THREAD

**Issue by f-f** [purescript/spago#999]

**Comment by JordanMartinez** [comment]
@f-f Is this issue self-explanatory? Are there any gotchas you already know about or potential design issues that need to be discussed?

**Comment by f-f** [comment]
Great question - the historical background is that these flags were first added to support Nix builds: if you are providing dependencies through Nix then you can skip the spago installation with `--no-fetch`, and if you previously built your project then you might want to carry that state into a `bundle` run without building again (with the `--no-build`)

I believe that now that we have a real `--offline` flag the `--no-fetch` flag is not needed anymore (since it would do the same thing, but less properly), but the `--no-build` flag might still be useful for the bundling stage in Nix and outside of Nix?
I personally use neither flag, maybe @thomashoneyman has some input on this?

Once we figure out if we want to build this, implementation-wise this is pretty straightforward: conditionally skip the build step in the `Main` if the `no-build` is specified - there are TODO comments in all these places

**Comment by thomashoneyman** [comment]
For me the `--offline` flag supplants these; for Nix I don't need `--no-build` because I'm supplying the pre-built dependencies anyways, and `--no-fetch` is covered by `--offline` (so long as `--offline` isn't going to try and populate the dependency directory with values from cache or something).

**Comment by f-f** [comment]
Wonderful, then this issue is now about "remove mentions of no-fetch and no-build flags" 😄
